DCS Reference: DCSHeaderContainer Class Reference
DCSHeaderContainer Class Reference
A container class for storing header information.
#include <DCSHeaderContainer.h>
Public Member Functions
DCSHeaderContainer ()
Header container constructor.
~DCSHeaderContainer ()
size_t size () const
Indicates size of the DCSHeaderContainer.
bool initialize (const char *filename)
Intialize the DCSHeaderContainer.
bool restore (const char *filename, uint16_t *version=NULL)
Restore the DCSHeaderContainer from a file.
bool insert (const DCSBaseHeader *header)
Add a new header to the container.
bool update (const DCSBaseHeader *header, bool &present)
Update an existing header.
bool remove (uint64_t id)
Remove a header from the container.
DCSBaseHeader * retrieve (uint64_t id, DCSHeaderGroup *hg=NULL) const
Retrieve a header from the container.
void traverse (void(*function)(const DCSBaseHeader *, void *), void *data) const
Traverse the container, executing a user specified function.
bool clean ()
Remove any records marked for deletion from the random access file.
bool getSave () const
Check if the random access file is to be preserved on exit.
void setSave (bool save)
Specify that the random access file should be preserved on exit.
Protected Member Functions
void clearItems ()
Destroy all of the header records in the table.
Protected Attributes
int fd_
Random access file descriptor.
bool save_
Random access file preservation flag;.
char filename_ [PATH_MAX]
Random access file name.
HeaderTable table_
Record table.
Detailed Description
A container class for storing header information.
DCS header data types are stored in a header container. The header container stores the contents of a header object in a random access file, only keeping the header id in memory. This keeps memory usage to a minimum and allows for data recovery, so in the event that a DCS server crashes it may be rstored to the exact state at failure by reading the file. The DCSHeaderContainer is used by the server for distributing headers to the client during a connection negotiation.
Constructor & Destructor Documentation
DCSHeaderContainer::DCSHeaderContainer ()
Header container constructor.
Initializes the contents of DCSHeaderRecord to the default values.
References filename_.
DCSHeaderContainer::~DCSHeaderContainer ()
Destroys all resources allocated for header container and deletes the random access file if the save flag is set to false.
References clearItems(), fd_, filename_, and save_.
Member Function Documentation
bool DCSHeaderContainer::clean ()
Remove any records marked for deletion from the random access file.
Process the random access file in order to remove any records that are marked for deletion. The file will be reorganized to eliminate any gaps caused by the removal of records, and the table will be rebuilt to update the values specifying the location of each record in the file. This function is not thread safe! A clean should not be executed while other execution units are accessing the file.
Returns:
true if successful, false if failure.
References DCSHeaderGroup::beamheader_, DCSBEAMHEADER, DCSGATEHEADER, DCSPLATFORMHEADER, fd_, DCSHeaderGroup::gateheader_, DCSHeaderGroup::platheader_, and table_.
Referenced by DCSServer::cleanDatabaseFile(), DCSServer::idle(), and insert().
void DCSHeaderContainer::clearItems () [protected]
Destroy all of the header records in the table.
Remove and delete each header record contained within the table.
References table_.
Referenced by restore(), and ~DCSHeaderContainer().
bool DCSHeaderContainer::getSave () const
Check if the random access file is to be preserved on exit.
Check to see if the random access file should be saved on container destruction. The default action is to destroy the file when the container is destroyed.
References save_.
bool DCSHeaderContainer::initialize (const char * filename)
Intialize the DCSHeaderContainer.
Creates the random access file. If the file exists, it's contents will be erased and the file will be repaced.
Parameters:
filename a string speciying the name to use when creating the random access file.
Returns:
true if successful, false if failure.
References DCSDBHeader::code_, fd_, filename_, and DCSDBHeader::version_.
Referenced by DCSServer::start().
bool DCSHeaderContainer::insert (const DCSBaseHeader * header)
Add a new header to the container.
Adds a new header to the container. If a header with the same id is already present in the table, the new header will not be added. If it is unknown whether a particular header is already present in the container, it is safer to use the update function. This function makes a copy of the specified header, so it is safe to free the resources used by the specified header after the insertion.
Parameters:
header a pointer to the DCSBaseHeader derived object to be added to the container.
Returns:
true if successful, false if failure.
See also:
insert()
References DCSFileEntryHeader::active_, clean(), fd_, DCSBaseData::getType(), DCSBaseData::id_, DCSHeaderRecord::location_, DCSFileEntryHeader::size_, DCSHeaderRecord::size_, DCSBaseHeader::sizeOf(), table_, and DCSFileEntryHeader::type_.
Referenced by update().
bool DCSHeaderContainer::remove (uint64_t id)
Remove a header from the container.
Removes a header from the container. The header's record will be removed from the table containg the location of the header within the random access file. The entry in the random access file will be marked for deletion, but not deleted. Lazy deletion is used with the random access file to minimize the amount of processing time required for reorganizing the file with the deletion of each entry. Any headers marked for deletion can be cleared from the file with a call to clean.
Parameters:
id an unsigned integer identifying the object to be removed from the container.
Returns:
true if successful, false if failure.
See also:
clean()
References DCSFileEntryHeader::active_, DCSUNKNOWN, fd_, DCSFileEntryHeader::size_, table_, and DCSFileEntryHeader::type_.
Referenced by DCSServer::removeHeader().
bool DCSHeaderContainer::restore (const char * filename, uint16_t * version = NULL)
Restore the DCSHeaderContainer from a file.
Opens an existing random access file. If the file exists, it's contents will be used to (re)build the database. If the file does not exist, function will behave as if a failure was encountered and return false.
Parameters:
filename a string speciying the name for the random access file containing the header data.
version an unsigned short to be filled the DCS version number of the file's creating server. If a restore fails, check this value to make sure it matches the DCS version number of the current server.
Returns:
true if successful, false if failure.
References DCSHeaderGroup::beamheader_, clearItems(), DCSDBHeader::code_, DCSBEAMHEADER, DCSGATEHEADER, DCSPLATFORMHEADER, fd_, filename_, DCSHeaderGroup::gateheader_, DCSHeaderGroup::platheader_, DCSHeaderRecord::size_, table_, and DCSDBHeader::version_.
Referenced by DCSServer::start().
DCSBaseHeader * DCSHeaderContainer::retrieve (uint64_t id, DCSHeaderGroup * hg = NULL) const
Retrieve a header from the container.
Retrieves the requested record from the container and returns a pointer to that record. If a DCSHeaderGroup object is specified, the record will be copied to the appropriate field in the object. If no DCSHeaderGroup object is specified, resources for the returned DCSBaseHeader object are allocated by this function with the new operator. The calling application is responsible for freeing these resources through a subsequent call to the delete operator.
Parameters:
id an unsigned integer identifying the header to retrieve.
hg a DCSHeaderGroup structure to be filled with the retrieved data. This argument is optional. If hg is NULL, retrieve will allocate the memory needed to store the retrieved data. The calling program is responsible for freeing this memory.
Returns:
a pointer to the requested header, or NULL if the header is not found.
References DCSHeaderGroup::baseheader_, DCSHeaderGroup::beamheader_, DCSBEAMHEADER, DCSGATEHEADER, DCSPLATFORMHEADER, fd_, DCSHeaderGroup::gateheader_, DCSHeaderGroup::platheader_, DCSBaseHeader::sizeOf(), table_, and DCSHeaderGroup::type_.
Referenced by DCSServer::inDCSHeaders(), DCSServer::removeHeader(), DCSServer::sendBeamData(), DCSServer::sendBeamHeader(), DCSServer::sendBeamInterpolatePosition(), DCSServer::sendCallsignEvent(), DCSServer::sendCategoryData(), DCSServer::sendColorEvent(), DCSServer::sendExpireEvent(), DCSServer::sendGateData(), DCSServer::sendGateHeader(), DCSServer::sendGateInterpolatePosition(), DCSServer::sendGenericData(), DCSServer::sendIconNameEvent(), DCSServer::sendPlatformData(), DCSServer::sendPlatformHeader(), DCSServer::sendPlatformInterpolate(), DCSServer::sendStateEvent(), DCSServer::sendTargetEvent(), DCSServer::sendTrackQualityEvent(), DCSCom::serverProcessRequests(), and traverse().
void DCSHeaderContainer::setSave (bool save)
Specify that the random access file should be preserved on exit.
Specify whether the random access file should be saved or deleted when the container is destroyed. Setting this value to true makes it possible to save a random access file for (re)loading at a later time.
Parameters:
save flag specifying the preservation status fo a random access file.
References save_.
Referenced by DCSServer::DCSServer().
size_t DCSHeaderContainer::size () const [inline]
Indicates size of the DCSHeaderContainer.
Indicates the number of headers stored within the DCSHeaderContainer.
Returns:
an integer indicating the number of headers stored in the DCSHeaderContainer.
References table_.
Referenced by DCSCom::serverSendHeaders(), and DCSServer::start().
void DCSHeaderContainer::traverse (void(*)(const DCSBaseHeader *, void *) function, void * data) const
Traverse the container, executing a user specified function.
Traverse the container element by element, executing a user specified function upon each element. The function may be used for any purpose except modifying a header, deleting a header, or deallocating the memory segment within which the header is stored.
Parameters:
function a pointer to the function that is to be used for processing a header. This function is shall be deisgned to accept two parameters, the first is pointer to the header object to process, and the second is a pointer to a data object specified by the user in the call to traverse. This function is not expected to return a value.
data a pointer to a data object to be used as a parameter for the specified function.
References DCSHeaderGroup::baseheader_, retrieve(), and table_.
Referenced by DCSCom::serverSendHeaders().
bool DCSHeaderContainer::update (const DCSBaseHeader * header, bool & present)
Update an existing header.
Updates the contents of a header that is present in the container. If the specified header is not present in the container, a new entry for that header will be inserted. For this reason, it is advisable for using update rather than insert when adding/updating headers to the container. This function makes a copy of the specified header, so it is safe to free the resources used by the specified header after the update.
Parameters:
header a pointer to the DCSBaseHeader derived object with which the containers contents are to be updated.
present a boolean value indicating if the specified header was present in the container. This value is set by the function for inspection by the calling process when 'update' returns. If the value is true the object was already present in the container. If value is false the object was not yet present and has been inserted.
Returns:
true if successful, false if failure.
See also:
restore()
References DCSFileEntryHeader::active_, fd_, DCSBaseData::getType(), DCSBaseData::id_, insert(), DCSFileEntryHeader::size_, DCSBaseHeader::sizeOf(), table_, and DCSFileEntryHeader::type_.
Referenced by DCSServer::sendBeamData(), DCSServer::sendBeamHeader(), DCSServer::sendCallsignEvent(), DCSServer::sendColorEvent(), DCSServer::sendExpireEvent(), DCSServer::sendGateData(), DCSServer::sendGateHeader(), DCSServer::sendIconNameEvent(), DCSServer::sendPlatformData(), DCSServer::sendPlatformHeader(), DCSServer::sendStateEvent(), DCSServer::sendTargetEvent(), and DCSServer::sendTrackQualityEvent().
Member Data Documentation
int DCSHeaderContainer::fd_ [protected]
Random access file descriptor.
File descriptor for random access file containting the header data.
Referenced by clean(), initialize(), insert(), remove(), restore(), retrieve(), update(), and ~DCSHeaderContainer().
char DCSHeaderContainer::filename_[PATH_MAX] [protected]
Random access file name.
Name identifying the random access file containing the header data.
Referenced by DCSHeaderContainer(), initialize(), restore(), and ~DCSHeaderContainer().
bool DCSHeaderContainer::save_ [protected]
Random access file preservation flag;.
Flag indicating that the random access file should not be deleted when the container is destroyed.
Referenced by getSave(), setSave(), and ~DCSHeaderContainer().
HeaderTable DCSHeaderContainer::table_ [protected]
Record table.
Table of records containing a header's id, size, and location within the random access file. A record is stored for each entry in the random access file.
Referenced by clean(), clearItems(), insert(), remove(), restore(), retrieve(), size(), traverse(), and update().
The documentation for this class was generated from the following files:
DCSHeaderContainer.h
DCSHeaderContainer.cpp
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.