DCS Reference: DCSBaseData Class Reference
DCSBaseData Class Reference
abstract base class for DCS network data types.
#include <DCSBaseData.h>
Public Member Functions
DCSBaseData (int16_t type=DCSUNKNOWN)
Base data constructor.
DCSBaseData (uint64_t id, int16_t type)
Base data constructor.
virtual ~DCSBaseData ()
Virtual destructor.
virtual void clear ()
Set contents of data object to default values.
int16_t getType () const
Get object type.
int16_t getVersion () const
Get DCS version.
virtual void * pack (void *buffer, int32_t size) const =0
Prepare data for network transmission.
virtual void unpack (const void *buffer, int32_t size)=0
Extract data from network transmission.
virtual int32_t dataSize () const
Determine object's data size.
virtual int32_t dataSize (uint16_t version) const
Determine object's data size.
virtual int32_t sizeOf () const
Determine object's physical size.
Public Attributes
uint64_t id_
Unique id.
Protected Member Functions
int32_t packit (void *buffer) const
Internal packing function.
int32_t unpackit (const void *buffer)
Internal unpacking function.
Detailed Description
abstract base class for DCS network data types.
All DCS data types to be sent to the network are derived from this class.
Constructor & Destructor Documentation
DCSBaseData::DCSBaseData (int16_t type = DCSUNKNOWN) [inline]
Base data constructor.
Initializes the contents of DCSBaseData and sets the data type value.
Parameters:
type a short representing the type of data structure being created.
DCSBaseData::DCSBaseData (uint64_t id, int16_t type) [inline]
Base data constructor.
Initializes the contents of DCSBaseData and sets the id and data type values.
Parameters:
id an unsigned 64-bit integer specifying the object's id.
type a short representing the type of data structure being created.
virtual DCSBaseData::~DCSBaseData () [inline, virtual]
Virtual destructor.
Important for properly destroying derived objects.
Member Function Documentation
virtual void DCSBaseData::clear () [inline, virtual]
Set contents of data object to default values.
Clears contents of data object, setting all fields to default values. Type and version values are never modified.
Reimplemented in DCSPlatformHeader, DCSBeamHeader, DCSEvent, DCSGateHeader, DCSScopeData, DCSScenarioHeader, DCSGateData, DCSGenericData, DCSPlatformData, DCSBeamData, DCSCategoryData, DCSTimeHeader, DCSScenarioData, and DCSTimeData.
References id_.
virtual int32_t DCSBaseData::dataSize () const [inline, virtual]
Determine object's data size.
Returns the total size, in bytes, required by the data members of the current object. Can be used to determine the proper size of buffers for the pack and unpack methods.
Returns:
an integer representing the size of the object's data.
See also:
pack()
unpack()
Reimplemented in DCSPlatformHeader, DCSBeamHeader, DCSEvent, DCSGateHeader, DCSScopeData, DCSScenarioHeader, DCSGateData, DCSGenericData, DCSPlatformData, DCSBeamData, DCSCategoryData, DCSTimeHeader, DCSScenarioData, DCSBaseHeader, and DCSTimeData.
References id_.
Referenced by DCSCom::readTCPData(), DCSCom::readUDPData(), DCSCom::sendTCPData(), and DCSCom::sendUDPData().
virtual int32_t DCSBaseData::dataSize (uint16_t version) const [inline, virtual]
Determine object's data size.
Returns the total size, in bytes, required by the data members of the current object. Can be used to determine the proper size of buffers for the pack and unpack methods.
Parameters:
version Server version if applicable
Returns:
an integer representing the size of the object's data.
See also:
pack()
unpack()
Reimplemented in DCSPlatformHeader, DCSBeamHeader, DCSEvent, DCSGateHeader, DCSScenarioHeader, DCSGenericData, DCSTimeHeader, and DCSBaseHeader.
References dataSize().
Referenced by dataSize().
int16_t DCSBaseData::getType () const [inline]
Get object type.
Returns a word indicating the type of data object.
Returns:
a short representing the type of data object.
Referenced by DCSCom::clientNegotiate(), DCSHeaderContainer::insert(), DCSLogger::log(), DCSServer::sendBeamInterpolatePosition(), DCSServer::sendCallsignEvent(), DCSServer::sendColorEvent(), DCSServer::sendExpireEvent(), DCSServer::sendGateInterpolatePosition(), DCSServer::sendIconNameEvent(), DCSServer::sendPlatformInterpolate(), DCSServer::sendStateEvent(), DCSServer::sendTargetEvent(), DCSServer::sendTrackQualityEvent(), and DCSHeaderContainer::update().
int16_t DCSBaseData::getVersion () const [inline]
Get DCS version.
The version number for the DCS application that generated this data object.
Returns:
a short representing the version number. High order byte is major number and low order byte is minor number.
Referenced by DCSGenericData::dataSize(), DCSGenericData::pack(), DCSScenarioHeader::pack(), DCSGateHeader::pack(), DCSEvent::pack(), DCSBeamHeader::pack(), DCSPlatformHeader::pack(), DCSGenericData::unpack(), DCSScenarioHeader::unpack(), DCSEvent::unpack(), DCSGateHeader::unpack(), DCSBeamHeader::unpack(), and DCSPlatformHeader::unpack().
virtual void* DCSBaseData::pack (void * buffer, int32_t size) const [pure virtual]
Prepare data for network transmission.
Packs the contents of this structure into a network byte ordered buffer. This buffer is then sent out on the network. The buffer is expected to be equal to or larger than the size of the structure. If the buffer is too small to accomodate the contents of the structure an exception will be thrown.
Parameters:
buffer a memory buffer large enough to hold the contents of the data structure.
size the size, in bytes, of buffer.
Returns:
a pointer to the argument 'buffer' for convenience.
See also:
dataSize()
unpack()
Implemented in DCSPlatformHeader, DCSBeamHeader, DCSEvent, DCSGateHeader, DCSScopeData, DCSScenarioHeader, DCSGateData, DCSGenericData, DCSPlatformData, DCSBeamData, DCSCategoryData, DCSTimeHeader, DCSScenarioData, DCSBaseHeader, and DCSTimeData.
Referenced by DCSCom::sendTCPData(), and DCSCom::sendUDPData().
virtual int32_t DCSBaseData::sizeOf () const [inline, virtual]
Determine object's physical size.
Returns actual size of object in memory. May differ from data size for padding, virtual function pointer table, etc.
Returns:
an integer representing the size of the object as returned from sizeof.
Reimplemented in DCSPlatformHeader, DCSBeamHeader, DCSEvent, DCSGateHeader, DCSScopeData, DCSScenarioHeader, DCSGenericData, DCSGateData, DCSPlatformData, DCSTimeHeader, DCSBeamData, DCSCategoryData, DCSBaseHeader, DCSScenarioData, and DCSTimeData.
virtual void DCSBaseData::unpack (const void * buffer, int32_t size) [pure virtual]
Extract data from network transmission.
Extracts the contents of a buffer, received from the network to this structure. The buffer is expected to be equal to or larger than the size of the structure. If the buffer is too small to contain all of the data required by the structure an exception will be thrown.
Parameters:
buffer a memory buffer containing data for the data structure.
size the size, in bytes, of buffer.
See also:
dataSize()
pack()
Implemented in DCSPlatformHeader, DCSBeamHeader, DCSEvent, DCSGateHeader, DCSScopeData, DCSScenarioHeader, DCSGateData, DCSGenericData, DCSPlatformData, DCSBeamData, DCSCategoryData, DCSTimeHeader, DCSScenarioData, DCSBaseHeader, and DCSTimeData.
Referenced by DCSCom::readTCPData(), and DCSCom::readUDPData().
Member Data Documentation
uint64_t DCSBaseData::id_
Unique id.
Each object must have a unique integer id. Using an unsigned integer allows for more than 4 million unique object ids.
Referenced by clear(), dataSize(), DCSHeaderContainer::insert(), packit(), DCSServer::sendBeamData(), DCSServer::sendBeamHeader(), DCSServer::sendGateData(), DCSServer::sendGateHeader(), DCSServer::sendPlatformHeader(), DCSScopeData::unpack(), unpackit(), and DCSHeaderContainer::update().
The documentation for this class was generated from the following files:
DCSBaseData.h
DCSBaseData.cpp
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.