DCS Reference: DCSLogger Class Reference
DCSLogger Class Reference
An abstract class for logging DCS data structures.
#include <DCSLogger.h>
Public Member Functions
virtual ~DCSLogger ()
Virtual destructor.
virtual bool log (const DCSBaseData *item) const
Log DCS data.
virtual bool log (const char *item) const =0
Log text.
Protected Member Functions
virtual bool logPlatformHeader (const DCSPlatformHeader *item) const =0
Log a platform header.
virtual bool logPlatformData (const DCSPlatformData *item) const =0
Log platform data.
virtual bool logBeamHeader (const DCSBeamHeader *item) const =0
Log a beam header.
virtual bool logBeamData (const DCSBeamData *item) const =0
Log beam data.
virtual bool logGateHeader (const DCSGateHeader *item) const =0
Log a gate header.
virtual bool logGateData (const DCSGateData *item) const =0
Log gate data.
virtual bool logScopeData (const DCSScopeData *item) const =0
Log gate data to file.
virtual bool logTimeHeader (const DCSTimeHeader *item) const =0
Log time header.
virtual bool logTimeData (const DCSTimeData *item) const =0
Log time data.
virtual bool logScenarioHeader (const DCSScenarioHeader *item) const =0
Log scenario header.
virtual bool logScenarioData (const DCSScenarioData *item) const =0
Log scenario data.
virtual bool logEvent (const DCSEvent *item) const =0
Log an event.
virtual bool logGenericData (const DCSGenericData *item) const =0
Log generic data.
virtual bool logCategoryData (const DCSCategoryData *item) const =0
Log category data to console.
Detailed Description
An abstract class for logging DCS data structures.
DCS data structures are logged with derivations of this class, created to write data to the console, files, etc.
Constructor & Destructor Documentation
virtual DCSLogger::~DCSLogger () [inline, virtual]
Virtual destructor.
Important for properly destroying derived objects.
Member Function Documentation
bool DCSLogger::log (const DCSBaseData * item) const [virtual]
Log DCS data.
Logs a DCS data structure to file, console, etc depending on the implementation. Determines the type of data and logs the proper data fields to the proper location.
Parameters:
item a pointer to any DCS object derived from DCSBaseData to be logged.
Returns:
true if successful, false if failed.
Reimplemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
References DCSBEAMDATA, DCSBEAMHEADER, DCSCATEGORYDATA, DCSEVENT, DCSGATEDATA, DCSGATEHEADER, DCSGENERICDATA, DCSPLATFORMDATA, DCSPLATFORMHEADER, DCSSCENARIODATA, DCSSCENARIOHEADER, DCSSCOPEDATA, DCSTIMEDATA, DCSTIMEHEADER, DCSUNKNOWN, DCSBaseData::getType(), logBeamData(), logBeamHeader(), logCategoryData(), logEvent(), logGateData(), logGateHeader(), logGenericData(), logPlatformData(), logPlatformHeader(), logScenarioData(), logScenarioHeader(), logScopeData(), logTimeData(), and logTimeHeader().
virtual bool DCSLogger::log (const char * item) const [pure virtual]
Log text.
Pure virtual function to be overridden for logging character strings to file, console, etc.
Parameters:
item character string to be logged.
Returns:
true if successful, false if failed.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
virtual bool DCSLogger::logBeamData (const DCSBeamData * item) const [protected, pure virtual]
Log beam data.
Pure virtual function to be overriden for logging a DCSBeamData structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logBeamHeader (const DCSBeamHeader * item) const [protected, pure virtual]
Log a beam header.
Pure virtual function to be overriden for logging a DCSBeamHeader structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logCategoryData (const DCSCategoryData * item) const [protected, pure virtual]
Log category data to console.
Log the contents of a DCSCategoryData structure to the console. Used by the public DCSLogger::log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logEvent (const DCSEvent * item) const [protected, pure virtual]
Log an event.
Pure virtual function to be overriden for logging a DCSEvent structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logGateData (const DCSGateData * item) const [protected, pure virtual]
Log gate data.
Pure virtual function to be overriden for logging a DCSGateData structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logGateHeader (const DCSGateHeader * item) const [protected, pure virtual]
Log a gate header.
Pure virtual function to be overriden for logging a DCSGateHeader structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logGenericData (const DCSGenericData * item) const [protected, pure virtual]
Log generic data.
Pure virtual function to be overriden for logging a DCSGenericData structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logPlatformData (const DCSPlatformData * item) const [protected, pure virtual]
Log platform data.
Pure virtual function to be overriden for logging a DCSPlatformData structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logPlatformHeader (const DCSPlatformHeader * item) const [protected, pure virtual]
Log a platform header.
Pure virtual function to be overriden for logging a DCSPlatformHeader structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logScenarioData (const DCSScenarioData * item) const [protected, pure virtual]
Log scenario data.
Pure virtual function to be overriden for logging a DCSScenarioData structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logScenarioHeader (const DCSScenarioHeader * item) const [protected, pure virtual]
Log scenario header.
Pure virtual function to be overriden for logging a DCSScenarioHeader structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logScopeData (const DCSScopeData * item) const [protected, pure virtual]
Log gate data to file.
Log the contents of a DCSScopeData structure to the file. Used by the public DCSLogger::log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logTimeData (const DCSTimeData * item) const [protected, pure virtual]
Log time data.
Pure virtual function to be overriden for logging a DCSTimeData structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
virtual bool DCSLogger::logTimeHeader (const DCSTimeHeader * item) const [protected, pure virtual]
Log time header.
Pure virtual function to be overriden for logging a DCSTimeHeader structure to file, console, etc. Will be used by the public log function.
Implemented in DCSFileLogger, DCSStreamLogger, and DCSConsoleLogger.
Referenced by log().
The documentation for this class was generated from the following files:
DCSLogger.h
DCSLogger.cpp
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.