DCS Reference: DCSScenarioHeader Class Reference
DCSScenarioHeader Class Reference
Scenario header class.
#include <DCSScenarioHeader.h>
Public Member Functions
DCSScenarioHeader ()
Default scenario header constructor.
DCSScenarioHeader (const DCSCoordReferenceFrame &refFrame, int16_t referenceyear, const char *classification, uint32_t classColor, const DCSScenarioData &scendata)
Scenario header constructor.
DCSScenarioHeader (double latorigin, double lonorigin, int16_t referenceyear, DCSCoordSystem_t coordsystem, DCSClassification_t classification, const DCSScenarioData &scendata)
Scenario header constructor. (deprecated)
virtual void clear ()
Set contents of data object to default values.
virtual void * pack (void *buffer, int32_t size) const
Prepare data for network transmission.
virtual void unpack (const void *buffer, int32_t size)
Extract data from network transmission.
virtual int32_t dataSize () const
Determine object's data size.
virtual int32_t dataSize (uint16_t version) const
Determine object's data size.
virtual int32_t sizeOf () const
Determine object's physical size.
Public Attributes
int16_t referenceyear_
Scenario reference year.
char classificationstr_ [64]
Data classification string.
uint32_t classcolor_
Classification color in 0xAABBGGRR.
DCSCoordReferenceFrame referenceframe_
Coordinate system reference frame.
DCSScenarioData scendata_
Current data value.
Detailed Description
Scenario header class.
Class containting data for specifying the initial scenario information for the Simdis application.
Constructor & Destructor Documentation
DCSScenarioHeader::DCSScenarioHeader ()
Default scenario header constructor.
Creates a scenario header object with default data values.
References classcolor_, and classificationstr_.
DCSScenarioHeader::DCSScenarioHeader (const DCSCoordReferenceFrame & refFrame, int16_t referenceyear, const char * classification, uint32_t classColor, const DCSScenarioData & scendata)
Scenario header constructor.
Creates a scenario header object with the specified data values.
Parameters:
refFrame Coordinate reference frame specifying scenario origin, default coordinate system, and other settings.
referenceyear a short specifying the calendar year.
classification a string specifying the data classification.
classColor a 32 bit integer specificying the classification color in 0xAABBGGRR
scendata a DCSScenarioData object providing an initial data set for the object associated with this header.
References classificationstr_, and scendata_.
DCSScenarioHeader::DCSScenarioHeader (double latorigin, double lonorigin, int16_t referenceyear, DCSCoordSystem_t coordsystem, DCSClassification_t classification, const DCSScenarioData & scendata)
Scenario header constructor. (deprecated)
Creates a scenario header object with the specified data values.
Parameters:
latorigin a double specifying the latitude topo origin.
lonorigin a double specifying the longitude topo origin.
referenceyear a short specifying the calendar year.
coordsystem a byte specifying the overall coordinate system.
classification a byte specifying the data classification.
scendata a DCSScenarioData object providing an initial data set for the object associated with this header.
References classcolor_, classificationstr_, DCSCoordReferenceFrame::coordsystem_, DCSCoordReferenceFrame::latorigin_, DCSCoordReferenceFrame::lonorigin_, referenceframe_, and scendata_.
Member Function Documentation
void DCSScenarioHeader::clear () [virtual]
Set contents of data object to default values.
Clears contents of data object, setting all fields to default values.
Reimplemented from DCSBaseData.
References classcolor_, classificationstr_, DCSScenarioData::clear(), DCSCoordReferenceFrame::clear(), referenceframe_, referenceyear_, and scendata_.
virtual int32_t DCSScenarioHeader::dataSize () const [inline, virtual]
Determine object's data size.
See also:
DCSBaseData::dataSize()
Reimplemented from DCSBaseData.
References dataSize().
Referenced by DCSCom::clientNegotiate(), dataSize(), and DCSCom::serverSendScenario().
virtual int32_t DCSScenarioHeader::dataSize (uint16_t version) const [inline, virtual]
Determine object's data size.
See also:
DCSBaseData::dataSize()
Reimplemented from DCSBaseData.
References classcolor_, classificationstr_, DCSScenarioData::dataSize(), dataSize(), DCSCoordReferenceFrame::dataSize(), referenceframe_, referenceyear_, and scendata_.
void * DCSScenarioHeader::pack (void * buffer, int32_t size) const [virtual]
Prepare data for network transmission.
See also:
DCSBaseData::pack()
Implements DCSBaseData.
References classcolor_, classificationstr_, DCSCoordReferenceFrame::coordsystem_, DCSCoordReferenceFrame::dataSize(), DCSBaseData::getVersion(), DCSCoordReferenceFrame::latorigin_, DCSCoordReferenceFrame::lonorigin_, DCSScenarioData::pack(), DCSCoordReferenceFrame::pack(), DCSBaseData::packit(), referenceframe_, referenceyear_, and scendata_.
Referenced by DCSCom::serverSendScenario().
virtual int32_t DCSScenarioHeader::sizeOf () const [inline, virtual]
Determine object's physical size.
See also:
DCSBaseData::sizeOf()
Reimplemented from DCSBaseData.
void DCSScenarioHeader::unpack (const void * buffer, int32_t size) [virtual]
Extract data from network transmission.
See also:
DCSBaseData::unpack()
Implements DCSBaseData.
References classcolor_, classificationstr_, DCSCoordReferenceFrame::coordsystem_, DCSCoordReferenceFrame::dataSize(), DCSBaseData::getVersion(), DCSCoordReferenceFrame::latorigin_, DCSCoordReferenceFrame::lonorigin_, referenceframe_, referenceyear_, scendata_, DCSScenarioData::unpack(), DCSCoordReferenceFrame::unpack(), and DCSBaseData::unpackit().
Referenced by DCSCom::clientNegotiate().
Member Data Documentation
DCSCoordReferenceFrame DCSScenarioHeader::referenceframe_
Coordinate system reference frame.
Coordinate reference frame information for scenario
Referenced by clear(), dataSize(), DCSScenarioHeader(), DCSConsoleLogger::logScenarioHeader(), DCSStreamLogger::logScenarioHeader(), DCSFileLogger::logScenarioHeader(), pack(), DCSServer::sendPlatformHeader(), DCSServer::sendScenarioHeader(), and unpack().
int16_t DCSScenarioHeader::referenceyear_
Scenario reference year.
Calendar year for scenario.
Referenced by clear(), dataSize(), DCSConsoleLogger::logScenarioHeader(), DCSStreamLogger::logScenarioHeader(), DCSFileLogger::logScenarioHeader(), pack(), DCSServer::sendScenarioHeader(), and unpack().
DCSScenarioData DCSScenarioHeader::scendata_
Current data value.
An initial data set for the object associated with this header.
Referenced by clear(), dataSize(), DCSScenarioHeader(), pack(), and unpack().
The documentation for this class was generated from the following files:
DCSScenarioHeader.h
DCSScenarioHeader.cpp
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.