DCS Reference: DCSServer Class Reference
DCSServer Class Reference
A top level class for implementing a DCS data server.
#include <DCSServer.h>
Public Member Functions
DCSServer (const char *p_appName=0, int8_t proto=DCSDATA_MULTICAST, int32_t srvPort=5555, int32_t dataPort=5707, const char *p_dataAddr=0, const char *p_iface=0, int32_t ttl=4)
DCSServer constructor.
~DCSServer ()
DCSServer destructor.
void start ()
DCSServer start.
bool removeHeader (uint64_t id, double currentTime)
DCSServer removeHeader.
void idle (double currentTime)
DCSServer idle.
void setExpireTimeLimit (double expireLimit)
DCSServer setExpireTimeLimit.
bool sendScenarioHeader (DCSCoordSystem_t coordsystem, const std::string &classification, uint32_t classColor, int32_t referenceyear=DCS::getyear(), double latorigin=0., double lonorigin=0., double altorigin=0., double time=0., double timemod=1.0, int8_t timesource=DCSTIME_PACKET)
DCSServer sendScenarioHeader.
bool sendScenarioHeader (const DCSCoordReferenceFrame &refFrame, const std::string &classification, uint32_t classColor, int32_t referenceyear=DCS::getyear(), double time=0., double timemod=1.0, int8_t timesource=DCSTIME_PACKET)
DCSServer sendScenarioHeader.
bool sendScenarioHeader (DCSCoordSystem_t coordsystem, DCSClassification_t classification, int32_t referenceyear=DCS::getyear(), double latorigin=0., double lonorigin=0., double time=0., double timemod=1.0, int8_t timesource=DCSTIME_PACKET)
DCSServer sendScenarioHeader.
bool sendPlatformHeader (uint64_t platid, const std::string &callsign, const std::string &iconname, DCSCoordSystem_t coordsystem, double latorigin=0, double lonorigin=0, double altorigin=0, DCSVerticalDatum_t vertDatum=DCSVERTDATUM_WGS84, double vertOffset=0, DCSMagneticVariance_t magVar=DCSMAGVAR_TRUE, double magOffset=0, double eciReference=0, double tangentX=0, double tangentY=0, double tangentAngle=0, double time=0, double x=0, double y=0, double z=0, double c=0, double p=0, double r=0, double vx=0, double vy=0, double vz=0, double ax=0, double ay=0, double az=0)
DCSServer sendPlatformHeader.
bool sendPlatformHeader (uint64_t platid, const std::string &callsign, const std::string &iconname, DCSPlatformType_t plattype=DCSPLATFORM_UNKNOWN, DCSAllegience_t allegience=DCSALLEGIENCE_FRIENDLY, double time=0, double x=0, double y=0, double z=0, double c=0, double p=0, double r=0, double vx=0, double vy=0, double vz=0, double ax=0, double ay=0, double az=0)
DCSServer sendPlatformHeader. (deprecated)
bool sendBeamHeader (uint64_t beamid, uint64_t platid, const std::string &callsign, double hbw, double vbw, int64_t targetId=-1, uint32_t color=0xff800080, double azimoffset=0., double elevoffset=0., double xoffset=0., double yoffset=0., double zoffset=0., DCSBeamType_t beamtype=DCSBEAM_LINEAR, double time=0, double azim=0, double elev=0, double length=0)
DCSServer sendBeamHeader.
bool sendGateHeader (uint64_t gateid, uint64_t beamid, const std::string &callsign, uint32_t color=0xff000000, double azimoffset=0., double elevoffset=0., double xoffset=0., double yoffset=0., double zoffset=0., DCSGateType_t gatetype=DCSGATE_RANGE, double time=0, double azim=0, double elev=0, double width=0, double height=0, double minrange=0, double centroid=0, double maxrange=0)
DCSServer sendGateHeader.
bool sendGateHeader (uint64_t gateid, uint64_t beamid, const std::string &callsign, uint32_t color=0xff000000, double xoffset=0., double yoffset=0., double zoffset=0., DCSGateType_t gatetype=DCSGATE_RANGE, double time=0, double azim=0, double elev=0, double width=0, double height=0, double minrange=0, double centroid=0, double maxrange=0)
DCSServer sendGateHeader. (deprecated)
bool sendPlatformData (uint64_t platid, double time, double x, double y, double z, double c=0, double p=0, double r=0, double vx=0, double vy=0, double vz=0, double ax=0, double ay=0, double az=0)
DCSServer sendPlatformData.
bool sendBeamData (uint64_t beamid, double time, double azim, double elev, double length=10000)
DCSServer sendBeamData.
bool sendGateData (uint64_t gateid, double time, double azim, double elev, double width, double height, double minrange, double centroid, double maxrange)
DCSServer sendGateData.
bool sendScopeData (uint64_t id, UTILS::UnitType_t xUnits, UTILS::UnitType_t yUnits, double time, double xStart, double xStep, double yBias, double yScale, uint32_t numDataPoints, UTILS::VariableType_t dataType, uint16_t numGates, const void *data, const DCSScopeGateData *gates)
Send scope data to the client.
bool sendGenericData (uint64_t objId, const std::string &tag, const std::string &data, double bgntime, double expiretime=-1.)
DCSServer sendGenericData.
bool sendCategoryData (uint64_t objId, const std::string &category, const std::string &data, double timeVal=-1)
DCSServer sendCategoryData.
bool sendTime (double time)
DCSServer sendTime.
bool sendStateEvent (uint64_t objId, bool on, double time)
DCSServer sendStateEvent.
bool sendExpireEvent (uint64_t objId, double time)
DCSServer sendExpireEvent.
bool sendColorEvent (uint64_t objId, uint32_t color, double time)
DCSServer sendColorEvent.
bool sendTrackQualityEvent (uint64_t objId, bool quality, double time)
DCSServer sendTrackQualityEvent.
bool sendTargetEvent (uint64_t objId, int64_t targetId, double time)
DCSServer sendTargetEvent.
bool sendClassificationEvent (DCSClassification_t classification, double time)
DCSServer sendClassificationEvent.
bool sendClassificationEvent (const std::string &classification, uint32_t color, double time)
DCSServer sendClassificationEvent.
bool sendPlatformInterpolate (uint64_t platId, bool interpolate, double time)
DCSServer sendPlatformInterpolate.
bool sendBeamInterpolatePosition (uint64_t beamId, bool interpolate, double time)
DCSServer sendBeamInterpolatePosition.
bool sendGateInterpolatePosition (uint64_t gateId, bool interpolate, double time)
DCSServer sendGateInterpolatePosition.
bool sendIconNameEvent (uint64_t objId, const std::string &iconName, double time)
DCSServer sendIconNameEvent.
bool sendCallsignEvent (uint64_t objId, const std::string &callsign, double time)
DCSServer sendCallsignEvent.
DCSCom::DCSServerInfo * getServerInfo ()
DCS Server getServerInfo.
const std::map< int64_t, double > * getPlatformMap ()
DCS Server getPlatformMap.
const std::map< int64_t,
std::vector< int64_t > > * getBeamMap ()
DCS Server getBeamMap.
const std::map< int64_t,
std::vector< int64_t > > * getGateMap ()
DCS Server getGateMap.
const char * getDatabaseFile () const
DCSServer getDatabaseFile.
bool cleanDatabaseFile ()
DCSServer cleanDatabaseFile.
bool inDCSHeaders (int64_t id_)
DCSServer inDCSHeaders.
Protected Attributes
char AppName_ [BUFSIZ]
char DatabaseFile_ [BUFSIZ]
int8_t Protocol_
int32_t ServerPort_
int32_t DataPort_
int32_t TTL_
char DataAddr_ [DCS_ADDRSTRLEN]
char IfaceAddr_ [DCS_ADDRSTRLEN]
double ExpireTimeLimit_
double LastExpireTime_
bool ServerStarted
std::map< int64_t, double > PlatMap_
std::map< int64_t, std::vector
< int64_t > > BeamMap_
std::map< int64_t, std::vector
< int64_t > > GateMap_
std::vector< int64_t > ScopeList_
DCSDisc::DCSDiscover Discover_
DCSCom::DCSServerInfo DCS_
DCSHeaderContainer DCSHeaders_
DCSScenarioHeader ScenarioHeader_
DCSTimeHeader TimeHeader_
Detailed Description
A top level class for implementing a DCS data server.
The DCSServer class facilitates the creation, setup and sending of data via the NRL developed DCS protocol
Constructor & Destructor Documentation
DCSServer::DCSServer (const char * p_appName = 0, int8_t proto = DCSDATA_MULTICAST, int32_t srvPort = 5555, int32_t dataPort = 5707, const char * p_dataAddr = 0, const char * p_iface = 0, int32_t ttl = 4)
DCSServer constructor.
Initializes the data transport socket, server port number, data port number, data server IP address and time to live
Parameters:
p_appName a string representing the name of the data server.
proto a char representing the type of UDP socket: broadcast, mulitcast, or unicast, to use. See DCSdefs.h for more information.
srvPort an integer representing the client's connection port number to the server.
dataPort an integer representing the port number DCS data is sent.
p_dataAddr a string representing the IP address DCS data is sent.
p_iface a string representing the network address of the network interface to use for data transmission. To use any network interface (INADDR_ANY), set to NULL.
ttl an integer specifying the new time to live value to be used (Multicast only).
The DCSServer class facilitates the creation, setup and sending of data via the NRL developed DCS protocol
References AppName_, DataAddr_, DatabaseFile_, DCSHeaders_, IfaceAddr_, and DCSHeaderContainer::setSave().
DCSServer::~DCSServer ()
DCSServer destructor.
Destroys all created objects and frees resources allocated for the discovery daemon. Also removes the generated DCS database file.
References AppName_, DCS_, Discover_, ServerStarted, and DCSCom::serverStop().
Member Function Documentation
bool DCSServer::cleanDatabaseFile ()
DCSServer cleanDatabaseFile.
Deletes entries from the database file that are no longer used.
References DCSHeaderContainer::clean(), and DCSHeaders_.
const std::map<int64_t, std::vector<int64_t> >* DCSServer::getBeamMap () [inline]
DCS Server getBeamMap.
Retrieves the map of active beams keyed on Platform ID
Returns:
Const pointer to the STL map containter this API instantiation is maintaining
References BeamMap_.
const char* DCSServer::getDatabaseFile () const [inline]
DCSServer getDatabaseFile.
Returns the filename of the DCS database.
Returns:
a char string representing filename of the DCS database.
References DatabaseFile_.
const std::map<int64_t, std::vector<int64_t> >* DCSServer::getGateMap () [inline]
DCS Server getGateMap.
Retrieves the map of active gates keyed on Beam ID
Returns:
Const pointer to the STL map containter this API instantiation is maintaining
References GateMap_.
const std::map<int64_t, double>* DCSServer::getPlatformMap () [inline]
DCS Server getPlatformMap.
Retrieves the map of active platforms keyed on DCS ID
Returns:
Const pointer to the STL map containter this API instantiation is maintaining
References PlatMap_.
DCSCom::DCSServerInfo* DCSServer::getServerInfo () [inline]
DCS Server getServerInfo.
Retrieves the low-level DCSServerInfo struct, available to access advanced functionality that this API might not supply.
Returns:
Pointer to the DCSServerInfo structure this API instantiation is maintaining
References DCS_.
void DCSServer::idle (double currentTime)
DCSServer idle.
Responsible for both servicing new client connection requests and removing expired objects.
Parameters:
currentTime a double specifying the current data time.
References DCSHeaderContainer::clean(), DCS_, DCSHeaders_, Discover_, ExpireTimeLimit_, LastExpireTime_, PlatMap_, removeHeader(), DCSDisc::DCSDiscover::request, ScenarioHeader_, DCSCom::serverAccept(), DCSCom::serverExpelVagrants(), DCSCom::serverNegotiate(), DCSCom::serverProcessRequests(), ServerStarted, DCSCom::serverTerminateClient(), DCSCom::DCSServerInfo::servsock, TimeHeader_, and DCSCom::DCSServerInfo::vagrants.
bool DCSServer::inDCSHeaders (int64_t id_)
DCSServer inDCSHeaders.
Returns whether (true) or not (false) the listed ID is found in the DCS Header Container.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSHeaders_, and DCSHeaderContainer::retrieve().
bool DCSServer::removeHeader (uint64_t id, double currentTime)
DCSServer removeHeader.
Responsible for removing a DCS object from the DCS database, preventing it from being sent. Also handles the creation and restoration of the DCS database.
Parameters:
id an unsigned 64-bit integer specifying the id of an object to remove.
currentTime a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References BeamMap_, DCSHeaders_, GateMap_, PlatMap_, DCSHeaderContainer::remove(), DCSHeaderContainer::retrieve(), sendExpireEvent(), and ServerStarted.
Referenced by idle().
bool DCSServer::sendBeamData (uint64_t beamid, double time, double azim, double elev, double length = 10000)
DCSServer sendBeamData.
Updates beam position information to the server and subsequently to all connected clients. Data is transmitted via the UDP channel.
Parameters:
beamid an unsigned 64-bit integer specifying the unique id of the beam.
time a double specifying the current data time, units are seconds.
azim a double specifying the azimuth pointing direction, units are radians.
elev a double specifying the elevation pointing direction, units are radians.
length a double specifying the beam's length(range), units are meters.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSBeamData::azim_, DCSBeamHeader::beamdata_, DCS_, DCSHeaders_, DCSBeamData::elev_, DCSBaseData::id_, DCSBeamData::length_, DCSHeaderContainer::retrieve(), ServerStarted, DCSBeamData::time_, and DCSHeaderContainer::update().
bool DCSServer::sendBeamHeader (uint64_t beamid, uint64_t platid, const std::string & callsign, double hbw, double vbw, int64_t targetId = -1, uint32_t color = 0xff800080, double azimoffset = 0., double elevoffset = 0., double xoffset = 0., double yoffset = 0., double zoffset = 0., DCSBeamType_t beamtype = DCSBEAM_LINEAR, double time = 0, double azim = 0, double elev = 0, double length = 0)
DCSServer sendBeamHeader.
Sends beam initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
beamid an unsigned 64-bit integer specifying the unique id of the beam.
platid an unsigned 64-bit integer specifying the unique id of the host platform.
callsign a string specifying the beam's description/name, size limited to 64.
hbw a double specifying the horizontal main beam width, units are radians.
vbw a double specifying the vertical main beam width, units are radians.
targetId a 64-bit integer specifying the unique id of the target (-1 means no target).
color an unsigned 32-bit integer specifying the beam color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
azimoffset a double specifying the azimuth pointing direction offset, units are radians.
elevoffset a double specifying the elevation pointing direction offset, units are radians.
xoffset a double specifying the X body system offset (X out the front), units are meters.
yoffset a double specifying the Y body system offset (Y out the left), units are meters.
zoffset a double specifying the Z body system offset (Z out the top), units are meters.
beamtype a char specifying the beam's type. See DCSdefs.h for more information.
time a double specifying the current data time, units are seconds.
azim a double specifying the azimuth pointing direction, units are radians.
elev a double specifying the elevation pointing direction, units are radians.
length a double specifying the beam's length(range), units are meters.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSBeamData::azim_, DCSBeamHeader::azimoffset_, DCSBeamHeader::beamdata_, DCSHeaderGroup::beamheader_, BeamMap_, DCSBeamHeader::beamtype_, DCSBeamHeader::callsign_, DCSBeamHeader::color_, DCS_, DCSHeaders_, DCSSTATE_OFF, DCSBeamData::elev_, DCSBeamHeader::elevoffset_, DCSBeamHeader::hbw_, DCSBeamHeader::hostid_, DCSBaseData::id_, DCSBeamData::length_, DCSBeamHeader::offset_, DCSHeaderContainer::retrieve(), ServerStarted, DCSPoint::set(), DCSBeamHeader::state_, DCSBeamHeader::targetid_, DCSBeamData::time_, DCSHeaderContainer::update(), and DCSBeamHeader::vbw_.
bool DCSServer::sendBeamInterpolatePosition (uint64_t beamId, bool interpolate, double time)
DCSServer sendBeamInterpolatePosition.
Sends command to turn a beam's interpolate position flag on and off. This value defaults to 'on' for new beams. If turned off, then beams will not interpolate between data points during a data playback.
Parameters:
beamId ID of a beam object to set the flag for
interpolate Flag, if true turns on interpolation (default), else if false turns off interpolation
time a double specifying the current data time, units are seconds.
Returns:
Success is true, failure is false
References DCSEvent::data_, DCS_, DCSBEAMHEADER, DCSEVENT_BEAMINTERPPOS, DCSHeaders_, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), and ServerStarted.
bool DCSServer::sendCallsignEvent (uint64_t objId, const std::string & callsign, double time)
DCSServer sendCallsignEvent.
Sends changes to callsigns (names) for platforms, beams and gates to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the object.
callsign a string specifying the new callsign of the object, size limited to 64.
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSBeamHeader::callsign_, DCSGateHeader::callsign_, DCSPlatformHeader::callsign_, DCSEvent::chardata_, DCS_, DCSBEAMHEADER, DCSEVENT_CALLSIGN, DCSGATEHEADER, DCSHeaders_, DCSPLATFORMHEADER, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), ServerStarted, and DCSHeaderContainer::update().
bool DCSServer::sendCategoryData (uint64_t objId, const std::string & category, const std::string & data, double timeVal = -1)
DCSServer sendCategoryData.
Sends a specifed object's category data to the server and subsequently to all connected clients. Data is transmitted via the UDP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the object.
category a string specifying the category data's category.
data a string specifying the category data.
timeVal a double specifying the data's activation time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCS_, DCSHeaders_, DCSHeaderContainer::retrieve(), and ServerStarted.
Referenced by sendPlatformHeader().
bool DCSServer::sendClassificationEvent (DCSClassification_t classification, double time)
DCSServer sendClassificationEvent.
Sends scenario level classification events for beams to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
classification an 8-bit integer specifying the classification. See DCSdefs.h for more information.
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSScenarioHeader::classcolor_, DCSScenarioHeader::classificationstr_, DCSEvent::data_, DCS_, DCSEVENT_CLASSIFICATION, ScenarioHeader_, DCSCom::sendEvent(), and ServerStarted.
bool DCSServer::sendClassificationEvent (const std::string & classification, uint32_t color, double time)
DCSServer sendClassificationEvent.
Sends scenario level classification events for beams to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
classification a string specifying the classification.
color an unsigned 32-bit integer specifying the color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSEvent::chardata_, DCSScenarioHeader::classificationstr_, DCS_, DCSEVENT_CLASSIFICATIONSTR, ScenarioHeader_, DCSCom::sendEvent(), and ServerStarted.
bool DCSServer::sendColorEvent (uint64_t objId, uint32_t color, double time)
DCSServer sendColorEvent.
Sends color change events for all objects to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the object.
color an unsigned 32-bit integer specifying the color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSGateHeader::color_, DCSPlatformHeader::color_, DCSBeamHeader::color_, DCSEvent::data_, DCS_, DCSBEAMHEADER, DCSEVENT_COLOR, DCSGATEHEADER, DCSHeaders_, DCSPLATFORMHEADER, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), ScopeList_, DCSCom::sendEvent(), ServerStarted, and DCSHeaderContainer::update().
bool DCSServer::sendExpireEvent (uint64_t objId, double time)
DCSServer sendExpireEvent.
Sends an expire state event for all objects to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the object.
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSEvent::data_, DCS_, DCSBEAMHEADER, DCSEVENT_STATE, DCSGATEHEADER, DCSHeaders_, DCSPLATFORMHEADER, DCSSTATE_EXPIRE, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), ServerStarted, DCSGateHeader::state_, DCSPlatformHeader::state_, DCSBeamHeader::state_, and DCSHeaderContainer::update().
Referenced by removeHeader().
bool DCSServer::sendGateData (uint64_t gateid, double time, double azim, double elev, double width, double height, double minrange, double centroid, double maxrange)
DCSServer sendGateData.
Updates gate position information to the server and subsequently to all connected clients. Data is transmitted via the UDP channel.
Parameters:
gateid an unsigned 64-bit integer specifying the unique id of the gate.
time a double specifying the current data time, units are seconds.
azim a double specifying the azimuth pointing direction, units are radians.
elev a double specifying the elevation pointing direction, units are radians.
width a double specifying the gate's angular width, units are radians.
height a double specifying the gate's angular height, units are radians.
minrange a double specifying the gate's minimun downrange extent, units are meters.
centroid a double specifying the gate's centroid range, units are meters.
maxrange a double specifying the gate's maximum downrange extent, units are meters.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSGateData::azim_, DCSGateData::centroid_, DCS_, DCSHeaders_, DCSGateData::elev_, DCSGateHeader::gatedata_, DCSGateData::height_, DCSBaseData::id_, DCSGateData::maxrange_, DCSGateData::minrange_, DCSHeaderContainer::retrieve(), ServerStarted, DCSGateData::time_, DCSHeaderContainer::update(), and DCSGateData::width_.
bool DCSServer::sendGateHeader (uint64_t gateid, uint64_t beamid, const std::string & callsign, uint32_t color = 0xff000000, double azimoffset = 0., double elevoffset = 0., double xoffset = 0., double yoffset = 0., double zoffset = 0., DCSGateType_t gatetype = DCSGATE_RANGE, double time = 0, double azim = 0, double elev = 0, double width = 0, double height = 0, double minrange = 0, double centroid = 0, double maxrange = 0)
DCSServer sendGateHeader.
Sends gate initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
gateid an unsigned 64-bit integer specifying the unique id of the gate.
beamid an unsigned 64-bit integer specifying the unique id of the host beam.
callsign a string specifying the gate's description/name, size limited to 64.
color an unsigned 32-bit integer specifying the gate color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
azimoffset a double specifying the azimuth pointing direction offset, units are radians.
elevoffset a double specifying the elevation pointing direction offset, units are radians.
xoffset a double specifying the X body system offset (X out the front), units are meters.
yoffset a double specifying the Y body system offset (Y out the left), units are meters.
zoffset a double specifying the Z body system offset (Z out the top), units are meters.
gatetype a char specifying the gate's type. See DCSdefs.h for more information.
time a double specifying the current data time, units are seconds.
azim a double specifying the azimuth pointing direction, units are radians.
elev a double specifying the elevation pointing direction, units are radians.
width a double specifying the gate's angular width, units are radians.
height a double specifying the gate's angular height, units are radians.
minrange a double specifying the gate's minimun downrange extent, units are meters.
centroid a double specifying the gate's centroid range, units are meters.
maxrange a double specifying the gate's maximum downrange extent, units are meters.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSGateData::azim_, DCSGateHeader::azimoffset_, DCSGateHeader::callsign_, DCSGateData::centroid_, DCSGateHeader::color_, DCS_, DCSHeaders_, DCSSTATE_OFF, DCSGateData::elev_, DCSGateHeader::elevoffset_, DCSGateHeader::gatedata_, DCSHeaderGroup::gateheader_, GateMap_, DCSGateHeader::gatetype_, DCSGateData::height_, DCSGateHeader::hostid_, DCSBaseData::id_, DCSGateData::maxrange_, DCSGateData::minrange_, DCSGateHeader::offset_, DCSHeaderContainer::retrieve(), ServerStarted, DCSPoint::set(), DCSGateHeader::state_, DCSGateData::time_, DCSHeaderContainer::update(), and DCSGateData::width_.
Referenced by sendGateHeader().
bool DCSServer::sendGateHeader (uint64_t gateid, uint64_t beamid, const std::string & callsign, uint32_t color = 0xff000000, double xoffset = 0., double yoffset = 0., double zoffset = 0., DCSGateType_t gatetype = DCSGATE_RANGE, double time = 0, double azim = 0, double elev = 0, double width = 0, double height = 0, double minrange = 0, double centroid = 0, double maxrange = 0)
DCSServer sendGateHeader. (deprecated)
Sends gate initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
gateid an unsigned 64-bit integer specifying the unique id of the gate.
beamid an unsigned 64-bit integer specifying the unique id of the host beam.
callsign a string specifying the gate's description/name, size limited to 64.
color an unsigned 32-bit integer specifying the gate color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
xoffset a double specifying the X body system offset (X out the front), units are meters.
yoffset a double specifying the Y body system offset (Y out the left), units are meters.
zoffset a double specifying the Z body system offset (Z out the top), units are meters.
gatetype a char specifying the gate's type. See DCSdefs.h for more information.
time a double specifying the current data time, units are seconds.
azim a double specifying the azimuth pointing direction, units are radians.
elev a double specifying the elevation pointing direction, units are radians.
width a double specifying the gate's angular width, units are radians.
height a double specifying the gate's angular height, units are radians.
minrange a double specifying the gate's minimun downrange extent, units are meters.
centroid a double specifying the gate's centroid range, units are meters.
maxrange a double specifying the gate's maximum downrange extent, units are meters.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References sendGateHeader().
bool DCSServer::sendGateInterpolatePosition (uint64_t gateId, bool interpolate, double time)
DCSServer sendGateInterpolatePosition.
Sends command to turn a gate's interpolate position flag on and off. This value defaults to 'on' for new gates. If turned off, then gates will not interpolate between data points during a data playback.
Parameters:
gateId ID of a gate object to set the flag for
interpolate Flag, if true turns on interpolation (default), else if false turns off interpolation
time a double specifying the current data time, units are seconds.
Returns:
Success is true, failure is false
References DCSEvent::data_, DCS_, DCSEVENT_GATEINTERPPOS, DCSGATEHEADER, DCSHeaders_, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), and ServerStarted.
bool DCSServer::sendGenericData (uint64_t objId, const std::string & tag, const std::string & data, double bgntime, double expiretime = -1.)
DCSServer sendGenericData.
Sends a specifed object's generic data to the server and subsequently to all connected clients. Data is transmitted via the UDP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the object.
tag a string specifying the generic data's tag.
data a string specifying the generic data.
bgntime a double specifying the data's activation time, units are seconds.
expiretime a double specifying the data's expiration time, units are radians.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCS_, DCSHeaders_, DCSHeaderContainer::retrieve(), and ServerStarted.
bool DCSServer::sendIconNameEvent (uint64_t objId, const std::string & iconName, double time)
DCSServer sendIconNameEvent.
Sends changes to icon names for platforms to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the object.
iconName a string specifying the new icon of the platform, size limited to 64.
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSEvent::chardata_, DCS_, DCSEVENT_ICONNAME, DCSHeaders_, DCSPLATFORMHEADER, DCSBaseData::getType(), DCSPlatformHeader::iconname_, DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), ServerStarted, and DCSHeaderContainer::update().
bool DCSServer::sendPlatformData (uint64_t platid, double time, double x, double y, double z, double c = 0, double p = 0, double r = 0, double vx = 0, double vy = 0, double vz = 0, double ax = 0, double ay = 0, double az = 0)
DCSServer sendPlatformData.
Updates platform position information to the server and subsequently to all connected clients. Data is transmitted via the UDP channel.
Parameters:
platid an unsigned 64-bit integer specifying the unique id of the platform.
time a double specifying the current data time, units are seconds.
x a double specifying the platform's X/Lat location, units are meters, radians for a geodetic (LLA) coordinate system.
y a double specifying the platform's Y/Lon location, units are meters, radians for a geodetic (LLA) coordinate system.
z a double specifying the platform's Z location, units are meters.
c a double specifying the platform's course, units are radians.
p a double specifying the platform's pitch, units are radians.
r a double specifying the platform's roll, units are radians.
vx a double specifying the platform's X velocity component, units are meters/second.
vy a double specifying the platform's Y velocity component, units are meters/second.
vz a double specifying the platform's Z velocity component, units are meters/second.
ax a double specifying the platform's X acceleration component, units are meters/second squared.
ay a double specifying the platform's Y acceleration component, units are meters/second squared.
az a double specifying the platform's Z acceleration component, units are meters/second squared.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSPlatformData::accel_, DCS_, DCSHeaders_, DCSPlatformData::orientation_, DCSPlatformHeader::platdata_, PlatMap_, DCSPlatformData::position_, DCSHeaderContainer::retrieve(), sendPlatformHeader(), ServerStarted, DCSPoint::set(), DCSPlatformData::time_, DCSHeaderContainer::update(), and DCSPlatformData::velocity_.
bool DCSServer::sendPlatformHeader (uint64_t platid, const std::string & callsign, const std::string & iconname, DCSCoordSystem_t coordsystem, double latorigin = 0, double lonorigin = 0, double altorigin = 0, DCSVerticalDatum_t vertDatum = DCSVERTDATUM_WGS84, double vertOffset = 0, DCSMagneticVariance_t magVar = DCSMAGVAR_TRUE, double magOffset = 0, double eciReference = 0, double tangentX = 0, double tangentY = 0, double tangentAngle = 0, double time = 0, double x = 0, double y = 0, double z = 0, double c = 0, double p = 0, double r = 0, double vx = 0, double vy = 0, double vz = 0, double ax = 0, double ay = 0, double az = 0)
DCSServer sendPlatformHeader.
Sends platform initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
platid an unsigned 64-bit integer specifying the unique id of the platform.
callsign a string specifying the platform's callsign/name, size limited to 64.
iconname a string specifying the platform's 3D icon name, size limited to 64.
coordsystem a byte specifying the coordinate system.
latorigin a double specifying the latitude topo origin in radians.
lonorigin a double specifying the longitude topo origin in radians.
altorigin a double specifying the altitude topo origin in meters.
vertDatum Vertical datum of the platform data
vertOffset Vertical datum offset, if vertDatum set to DCSVERTDATUM_USER
magVar Magnetic variance to apply to orientation data
magOffset Magnetic variance offset, if magVar set to DCSMAGVAR_USER
eciReference ECI Reference time in seconds since beginning of scenario reference year
tangentX Tangent plane offset for Generic Tangent Plane (GTP) coordinate systems
tangentY Tangent plane offset for Generic Tangent Plane (GTP) coordinate systems
tangentAngle Tangent plane rotation angle in radians for Generic Tangent Plane (GTP) coordinate systems
time a double specifying the current data time, units are seconds.
x a double specifying the platform's X/Lat location, units are meters, radians for a geodetic (LLA) coordinate system.
y a double specifying the platform's Y/Lon location, units are meters, radians for a geodetic (LLA) coordinate system.
z a double specifying the platform's Z location, units are meters.
c a double specifying the platform's course, units are radians.
p a double specifying the platform's pitch, units are radians.
r a double specifying the platform's roll, units are radians.
vx a double specifying the platform's X velocity component, units are meters/second.
vy a double specifying the platform's Y velocity component, units are meters/second.
vz a double specifying the platform's Z velocity component, units are meters/second.
ax a double specifying the platform's X acceleration component, units are meters/second squared.
ay a double specifying the platform's Y acceleration component, units are meters/second squared.
az a double specifying the platform's Z acceleration component, units are meters/second squared.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSPlatformData::accel_, DCSCoordReferenceFrame::altorigin_, DCSPlatformHeader::callsign_, DCSCoordReferenceFrame::coordsystem_, DCS_, DCSHeaders_, DCSSTATE_ON, DCSSTATUS_LIVE, DCSPlatformHeader::iconname_, DCSBaseData::id_, DCSCoordReferenceFrame::latorigin_, DCSCoordReferenceFrame::lonorigin_, DCSCoordReferenceFrame::magneticOffset_, DCSCoordReferenceFrame::magneticVariance_, DCSPlatformData::orientation_, DCSPlatformHeader::platdata_, DCSHeaderGroup::platheader_, PlatMap_, DCSPlatformData::position_, DCSPlatformHeader::referenceframe_, DCSCoordReferenceFrame::referenceTimeECI_, DCSHeaderContainer::retrieve(), ServerStarted, DCSPoint::set(), DCSPlatformHeader::state_, DCSPlatformHeader::status_, DCSCoordReferenceFrame::tangentAngle_, DCSCoordReferenceFrame::tangentOffsetX_, DCSCoordReferenceFrame::tangentOffsetY_, DCSPlatformData::time_, DCSHeaderContainer::update(), DCSPlatformData::velocity_, DCSCoordReferenceFrame::verticalDatum_, and DCSCoordReferenceFrame::verticalOffset_.
Referenced by sendPlatformData(), and sendPlatformHeader().
bool DCSServer::sendPlatformHeader (uint64_t platid, const std::string & callsign, const std::string & iconname, DCSPlatformType_t plattype = DCSPLATFORM_UNKNOWN, DCSAllegience_t allegience = DCSALLEGIENCE_FRIENDLY, double time = 0, double x = 0, double y = 0, double z = 0, double c = 0, double p = 0, double r = 0, double vx = 0, double vy = 0, double vz = 0, double ax = 0, double ay = 0, double az = 0)
DCSServer sendPlatformHeader. (deprecated)
Sends platform initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
platid an unsigned 64-bit integer specifying the unique id of the platform.
callsign a string specifying the platform's callsign/name, size limited to 64.
iconname a string specifying the platform's 3D icon name, size limited to 64.
plattype a char specifying the platform's type. See DCSdefs.h for more information.
allegience a char specifying the platform's allegience (friendly, hostile, or neutral). See DCSdefs.h for more information.
time a double specifying the current data time, units are seconds.
x a double specifying the platform's X/Lat location, units are meters, radians for a geodetic (LLA) coordinate system.
y a double specifying the platform's Y/Lon location, units are meters, radians for a geodetic (LLA) coordinate system.
z a double specifying the platform's Z location, units are meters.
c a double specifying the platform's course, units are radians.
p a double specifying the platform's pitch, units are radians.
r a double specifying the platform's roll, units are radians.
vx a double specifying the platform's X velocity component, units are meters/second.
vy a double specifying the platform's Y velocity component, units are meters/second.
vz a double specifying the platform's Z velocity component, units are meters/second.
ax a double specifying the platform's X acceleration component, units are meters/second squared.
ay a double specifying the platform's Y acceleration component, units are meters/second squared.
az a double specifying the platform's Z acceleration component, units are meters/second squared.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSPlatformData::accel_, DCSPlatformHeader::callsign_, DCS_, DCSHeaders_, DCSSTATE_ON, DCSSTATUS_LIVE, DCSPlatformHeader::iconname_, DCSBaseData::id_, DCSPlatformData::orientation_, DCSPlatformHeader::platdata_, DCSHeaderGroup::platheader_, PlatMap_, DCSPlatformData::position_, DCSScenarioHeader::referenceframe_, DCSPlatformHeader::referenceframe_, DCSHeaderContainer::retrieve(), ScenarioHeader_, sendCategoryData(), sendPlatformHeader(), ServerStarted, DCSPoint::set(), DCSPlatformHeader::state_, DCSPlatformHeader::status_, DCSPlatformData::time_, DCSHeaderContainer::update(), and DCSPlatformData::velocity_.
bool DCSServer::sendPlatformInterpolate (uint64_t platId, bool interpolate, double time)
DCSServer sendPlatformInterpolate.
Sends command to turn a platform's interpolate orientation flag on and off. This value defaults to 'on' for new platforms. If turned off, then platforms will not interpolate orientation between data points during a data playback.
Parameters:
platId ID of a beam object to set the flag for
interpolate Flag, if true turns on interpolation (default) of position and orientation, else if false turns off interpolation
time a double specifying the current data time, units are seconds.
Returns:
Success is true, failure is false
References DCSEvent::data_, DCS_, DCSEVENT_PLATFORMINTERPOLATE, DCSHeaders_, DCSPLATFORMHEADER, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), and ServerStarted.
bool DCSServer::sendScenarioHeader (DCSCoordSystem_t coordsystem, const std::string & classification, uint32_t classColor, int32_t referenceyear = DCS::getyear(), double latorigin = 0., double lonorigin = 0., double altorigin = 0., double time = 0., double timemod = 1.0, int8_t timesource = DCSTIME_PACKET)
DCSServer sendScenarioHeader.
Sends scenario initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
coordsystem a char specifying the scenario data's coordinate system. See DCSdefs.h for more information.
classification a string specifying the scenario data's classification.
classColor 0xAABBGGRR color value for the classification
referenceyear an integer specifying the scenario data's current year, i.e. 2003.
latorigin a double specifying the scenario data's reference latitude, units are radians.
lonorigin a double specifying the scenario data's reference longitude, units are radians.
altorigin a double specifying the scenario data's reference altitude, units are meters HAE.
time a double specifying the current data time, units are seconds.
timemod a double specifying the percentage of real-time in which the current time is being specified (1. = 1x, 2. = 2x, 0.5 = .5x, etc).
timesource a char specifying the type of time source to use. See DCSdefs.h for more information.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSCoordReferenceFrame::altorigin_, DCSScenarioHeader::classcolor_, DCSScenarioHeader::classificationstr_, DCSCoordReferenceFrame::coordsystem_, DCSCoordReferenceFrame::latorigin_, DCSCoordReferenceFrame::lonorigin_, DCSTimeHeader::realtimemod_, DCSScenarioHeader::referenceframe_, DCSScenarioHeader::referenceyear_, ScenarioHeader_, ServerStarted, DCSTimeData::time_, DCSTimeHeader::timedata_, TimeHeader_, and DCSTimeHeader::timetype_.
bool DCSServer::sendScenarioHeader (const DCSCoordReferenceFrame & refFrame, const std::string & classification, uint32_t classColor, int32_t referenceyear = DCS::getyear(), double time = 0., double timemod = 1.0, int8_t timesource = DCSTIME_PACKET)
DCSServer sendScenarioHeader.
Sends scenario initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
refFrame Coordinate reference frame specifying scenario origin, default coordinate system, and other settings.
classification a string specifying the scenario data's classification. See DCSdefs.h for more information.
classColor 0xAABBGGRR color value for the classification
referenceyear an integer specifying the scenario data's current year, i.e. 2003.
time a double specifying the current data time, units are seconds.
timemod a double specifying the percentage of real-time in which the current time is being specified (1. = 1x, 2. = 2x, 0.5 = .5x, etc).
timesource a char specifying the type of time source to use. See DCSdefs.h for more information.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSScenarioHeader::classcolor_, DCSScenarioHeader::classificationstr_, DCSTimeHeader::realtimemod_, DCSScenarioHeader::referenceframe_, DCSScenarioHeader::referenceyear_, ScenarioHeader_, ServerStarted, DCSTimeData::time_, DCSTimeHeader::timedata_, TimeHeader_, and DCSTimeHeader::timetype_.
bool DCSServer::sendScenarioHeader (DCSCoordSystem_t coordsystem, DCSClassification_t classification, int32_t referenceyear = DCS::getyear(), double latorigin = 0., double lonorigin = 0., double time = 0., double timemod = 1.0, int8_t timesource = DCSTIME_PACKET)
DCSServer sendScenarioHeader.
Sends scenario initialization information to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
coordsystem a char specifying the scenario data's coordinate system. See DCSdefs.h for more information.
classification a char specifying the scenario data's classification. See DCSdefs.h for more information.
referenceyear an integer specifying the scenario data's current year, i.e. 2003.
latorigin a double specifying the scenario data's reference latitude, units are radians.
lonorigin a double specifying the scenario data's reference longitude, units are radians.
time a double specifying the current data time, units are seconds.
timemod a double specifying the percentage of real-time in which the current time is being specified (1. = 1x, 2. = 2x, 0.5 = .5x, etc).
timesource a char specifying the type of time source to use. See DCSdefs.h for more information.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSScenarioHeader::classcolor_, DCSScenarioHeader::classificationstr_, DCSCoordReferenceFrame::coordsystem_, DCSCoordReferenceFrame::latorigin_, DCSCoordReferenceFrame::lonorigin_, DCSTimeHeader::realtimemod_, DCSScenarioHeader::referenceframe_, DCSScenarioHeader::referenceyear_, ScenarioHeader_, ServerStarted, DCSTimeData::time_, DCSTimeHeader::timedata_, TimeHeader_, and DCSTimeHeader::timetype_.
bool DCSServer::sendScopeData (uint64_t id, UTILS::UnitType_t xUnits, UTILS::UnitType_t yUnits, double time, double xStart, double xStep, double yBias, double yScale, uint32_t numDataPoints, UTILS::VariableType_t dataType, uint16_t numGates, const void * data, const DCSScopeGateData * gates)
Send scope data to the client.
Send a DCSScopeData object, created from the specified values, from the server to the client. Scope data is transmitted via the UDP channel.
Parameters:
id an unsigned integer specifying the object's id.
xUnits an int16 specifying the object's x-units.
yUnits an int16 specifying the object's y-units.
time a double specifying the object's time.
xStart a double specifying the start of the object's x values.
xStep a double specifying the object's x step.
yBias a double specifying the object's y bias.
yScale a double specifying the object's y scale.
numDataPoints an int32 specifying the number of data points in the data array.
dataType an int8 specifying the data type of the object's array data.
numGates an unsigned int16 specifying the object's number of gates.
data a char array containing the object's data points.
gates a DCSCopeGateData array containing the object's gates.
Returns:
true if successful, false if failed.
References DCS_, ScopeList_, and ServerStarted.
bool DCSServer::sendStateEvent (uint64_t objId, bool on, double time)
DCSServer sendStateEvent.
Sends on|off state events for all objects to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the object.
on a boolean specifying the object's state, true(on), false(off).
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSEvent::data_, DCS_, DCSBEAMHEADER, DCSEVENT_STATE, DCSGATEHEADER, DCSHeaders_, DCSPLATFORMHEADER, DCSSTATE_OFF, DCSSTATE_ON, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), ServerStarted, DCSGateHeader::state_, DCSPlatformHeader::state_, DCSBeamHeader::state_, and DCSHeaderContainer::update().
bool DCSServer::sendTargetEvent (uint64_t objId, int64_t targetId, double time)
DCSServer sendTargetEvent.
Sends target events for beams to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the beam.
targetId a 64-bit integer specifying the unique id of the target (-1 means no target).
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSBeamHeader::beamtype_, DCSEvent::data_, DCS_, DCSBEAM_STEADY, DCSBEAMHEADER, DCSEVENT_TARGETID, DCSGATEHEADER, DCSHeaders_, DCSPLATFORMHEADER, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), ServerStarted, DCSBeamHeader::targetid_, and DCSHeaderContainer::update().
bool DCSServer::sendTime (double time)
DCSServer sendTime.
Updates the current scenario time to the server and subsequently to all connected clients. Data is transmitted via the UDP channel.
Parameters:
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCS_, DCSCom::sendTimeData(), ServerStarted, DCSTimeData::time_, DCSTimeHeader::timedata_, and TimeHeader_.
bool DCSServer::sendTrackQualityEvent (uint64_t objId, bool quality, double time)
DCSServer sendTrackQualityEvent.
Sends good|bad track quality events for platforms to the server and subsequently to all connected clients. Data is transmitted via the TCP channel.
Parameters:
objId an unsigned 64-bit integer specifying the unique id of the platform.
quality a boolean specifying the platforms's track quality, true(good), false(bad).
time a double specifying the current data time, units are seconds.
Returns:
a bool representing the success(true) or failure(false) status of the method call.
References DCSEvent::data_, DCS_, DCSBEAMHEADER, DCSEVENT_STATUS, DCSGATEHEADER, DCSHeaders_, DCSPLATFORMHEADER, DCSSTATUS_DROPPED, DCSSTATUS_LIVE, DCSBaseData::getType(), DCSHeaderContainer::retrieve(), DCSCom::sendEvent(), ServerStarted, DCSPlatformHeader::status_, and DCSHeaderContainer::update().
void DCSServer::setExpireTimeLimit (double expireLimit) [inline]
DCSServer setExpireTimeLimit.
Sets expiration time limit (secs) for all objects, value must be > 0, otherwise default to 300 seconds. Also handles the creation and restoration of the DCS database.
Parameters:
expireLimit a double specifying the expiration time limit, units are seconds.
References ExpireTimeLimit_.
void DCSServer::start ()
DCSServer start.
Responsible for starting the DCS server based on values set in the constructor. Also handles the creation and restoration of the DCS database.
References AppName_, DataAddr_, DatabaseFile_, DataPort_, DCS_, DCSDATA_BROADCAST, DCSDATA_MULTICAST, DCSDATA_UNICAST, DCSHeaders_, Discover_, IfaceAddr_, DCSHeaderContainer::initialize(), LastExpireTime_, Protocol_, DCSHeaderContainer::restore(), ServerPort_, DCSCom::serverStart(), ServerStarted, DCSCom::DCSServerInfo::servsock, DCSHeaderContainer::size(), and TTL_.
Member Data Documentation
char DCSServer::AppName_[BUFSIZ] [protected]
your application's name
Referenced by DCSServer(), start(), and ~DCSServer().
std::map<int64_t, std::vector<int64_t> > DCSServer::BeamMap_ [protected]
map of beams keyed on DCS Platform ID,
Referenced by getBeamMap(), removeHeader(), and sendBeamHeader().
char DCSServer::DataAddr_[DCS_ADDRSTRLEN] [protected]
data delivery address
Referenced by DCSServer(), and start().
char DCSServer::DatabaseFile_[BUFSIZ] [protected]
filename of your DCS database
Referenced by DCSServer(), getDatabaseFile(), and start().
int32_t DCSServer::DataPort_ [protected]
data delivery port number
Referenced by start().
DCSCom::DCSServerInfo DCSServer::DCS_ [protected]
stores information relevant to the actual DCS server
Referenced by getServerInfo(), idle(), sendBeamData(), sendBeamHeader(), sendBeamInterpolatePosition(), sendCallsignEvent(), sendCategoryData(), sendClassificationEvent(), sendColorEvent(), sendExpireEvent(), sendGateData(), sendGateHeader(), sendGateInterpolatePosition(), sendGenericData(), sendIconNameEvent(), sendPlatformData(), sendPlatformHeader(), sendPlatformInterpolate(), sendScopeData(), sendStateEvent(), sendTargetEvent(), sendTime(), sendTrackQualityEvent(), start(), and ~DCSServer().
DCSHeaderContainer DCSServer::DCSHeaders_ [protected]
provides functionality for inserting, updating, retrieving, and removing header objects
Referenced by cleanDatabaseFile(), DCSServer(), idle(), inDCSHeaders(), removeHeader(), sendBeamData(), sendBeamHeader(), sendBeamInterpolatePosition(), sendCallsignEvent(), sendCategoryData(), sendColorEvent(), sendExpireEvent(), sendGateData(), sendGateHeader(), sendGateInterpolatePosition(), sendGenericData(), sendIconNameEvent(), sendPlatformData(), sendPlatformHeader(), sendPlatformInterpolate(), sendStateEvent(), sendTargetEvent(), sendTrackQualityEvent(), and start().
DCSDisc::DCSDiscover DCSServer::Discover_ [protected]
provides functionality for discovering new clients looking for a server
Referenced by idle(), start(), and ~DCSServer().
double DCSServer::ExpireTimeLimit_ [protected]
platform expiration limit
Referenced by idle(), and setExpireTimeLimit().
std::map<int64_t, std::vector<int64_t> > DCSServer::GateMap_ [protected]
map of gates keyed on DCS Beam ID
Referenced by getGateMap(), removeHeader(), and sendGateHeader().
char DCSServer::IfaceAddr_[DCS_ADDRSTRLEN] [protected]
network interface address
Referenced by DCSServer(), and start().
double DCSServer::LastExpireTime_ [protected]
last time platform expiration check was performed
Referenced by idle(), and start().
std::map<int64_t, double> DCSServer::PlatMap_ [protected]
map of platforms keyed on DCS ID, used for checking expired platforms
Referenced by getPlatformMap(), idle(), removeHeader(), sendPlatformData(), and sendPlatformHeader().
int8_t DCSServer::Protocol_ [protected]
data delivery protocol
Referenced by start().
DCSScenarioHeader DCSServer::ScenarioHeader_ [protected]
initialization parameters for scenario. Specifies classification, reference coordinate, etc.
Referenced by idle(), sendClassificationEvent(), sendPlatformHeader(), and sendScenarioHeader().
std::vector<int64_t> DCSServer::ScopeList_ [protected]
list of Scope Data keyed on DCS ID
Referenced by sendColorEvent(), and sendScopeData().
int32_t DCSServer::ServerPort_ [protected]
server port number
Referenced by start().
bool DCSServer::ServerStarted [protected]
flag to denote if server has been started
Referenced by idle(), removeHeader(), sendBeamData(), sendBeamHeader(), sendBeamInterpolatePosition(), sendCallsignEvent(), sendCategoryData(), sendClassificationEvent(), sendColorEvent(), sendExpireEvent(), sendGateData(), sendGateHeader(), sendGateInterpolatePosition(), sendGenericData(), sendIconNameEvent(), sendPlatformData(), sendPlatformHeader(), sendPlatformInterpolate(), sendScenarioHeader(), sendScopeData(), sendStateEvent(), sendTargetEvent(), sendTime(), sendTrackQualityEvent(), start(), and ~DCSServer().
DCSTimeHeader DCSServer::TimeHeader_ [protected]
initialization parameters for time. Specifies time source (e.g. DCS server or client workstation's system clock)
Referenced by idle(), sendScenarioHeader(), and sendTime().
int32_t DCSServer::TTL_ [protected]
time to live (multicast only)
Referenced by start().
The documentation for this class was generated from the following files:
DCSServer.h
DCSServer.cpp
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.