DCS Reference: DCSTimeData Class Reference
DCSTimeData Class Reference
Time data class.
#include <DCSTimeData.h>
Public Member Functions
DCSTimeData ()
Default time data constructor.
DCSTimeData (double time)
Time data constructor.
virtual void clear ()
Set contents of data object to default values.
virtual void * pack (void *buffer, int32_t size) const
Prepare data for network transmission.
virtual void unpack (const void *buffer, int32_t size)
Extract data from network transmission.
virtual int32_t dataSize () const
Determine object's data size.
virtual int32_t sizeOf () const
Determine object's physical size.
Public Attributes
double time_
Current time.
Detailed Description
Time data class.
Class containting information for specifying the time in the Simdis application.
Constructor & Destructor Documentation
DCSTimeData::DCSTimeData ()
Default time data constructor.
Creates a time data object with default data values.
DCSTimeData::DCSTimeData (double time)
Time data constructor.
Creates a time data object with the specified data values.
Parameters:
time a double specifying the current time.
Member Function Documentation
void DCSTimeData::clear () [virtual]
Set contents of data object to default values.
Clears contents of data object, setting all fields to default values.
Reimplemented from DCSBaseData.
References time_.
Referenced by DCSTimeHeader::clear().
virtual int32_t DCSTimeData::dataSize () const [inline, virtual]
Determine object's data size.
See also:
DCSBaseData::dataSize()
Reimplemented from DCSBaseData.
References time_.
Referenced by DCSTimeHeader::dataSize().
void * DCSTimeData::pack (void * buffer, int32_t size) const [virtual]
Prepare data for network transmission.
See also:
DCSBaseData::pack()
Implements DCSBaseData.
References DCSBaseData::packit(), and time_.
Referenced by DCSTimeHeader::pack().
virtual int32_t DCSTimeData::sizeOf () const [inline, virtual]
Determine object's physical size.
See also:
DCSBaseData::sizeOf()
Reimplemented from DCSBaseData.
void DCSTimeData::unpack (const void * buffer, int32_t size) [virtual]
Extract data from network transmission.
See also:
DCSBaseData::unpack()
Implements DCSBaseData.
References time_, and DCSBaseData::unpackit().
Referenced by DCSTimeHeader::unpack().
Member Data Documentation
double DCSTimeData::time_
Current time.
Current time in seconds (with an optional fraction of a second).
Referenced by clear(), dataSize(), DCSConsoleLogger::logTimeData(), DCSStreamLogger::logTimeData(), DCSFileLogger::logTimeData(), pack(), DCSServer::sendScenarioHeader(), DCSServer::sendTime(), DCSCom::serverProcessRequests(), and unpack().
The documentation for this class was generated from the following files:
DCSTimeData.h
DCSTimeData.cpp
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.