DCS Reference: DCSBaseHeader Class Reference
DCSBaseHeader Class Reference
An abstract base class for DCS network header data types.
#include <DCSBaseHeader.h>
Public Member Functions
DCSBaseHeader (int16_t type)
Base header constructor.
DCSBaseHeader (uint64_t id, int16_t type)
Base header constructor.
virtual ~DCSBaseHeader ()
Virtual destructor.
virtual void * pack (void *buffer, int32_t size) const =0
Prepare data for network transmission.
virtual void unpack (const void *buffer, int32_t size)=0
Extract data from network transmission.
virtual int32_t dataSize () const
Determine object's data size.
virtual int32_t dataSize (uint16_t version) const
Determine object's data size.
virtual int32_t sizeOf () const
Determine object's physical size.
Detailed Description
An abstract base class for DCS network header data types.
All DCS header data types to be sent to the network are derived from this class. Headers are sepearted from general data because they require special processing for storage and client server connection negotiations. The main purpose of using a base header class is to limit the types of data that can be stored in the DCSHeaderContainer.
Constructor & Destructor Documentation
DCSBaseHeader::DCSBaseHeader (int16_t type) [inline]
Base header constructor.
Initializes the contents of DCSBaseHeader and sets the data type value.
Parameters:
type a short representing the type of data structure being created.
DCSBaseHeader::DCSBaseHeader (uint64_t id, int16_t type) [inline]
Base header constructor.
Initializes the contents of DCSBaseHeader and sets the id and data type values.
Parameters:
id an unsigned 64-bit integer specifying the object's id.
type a short representing the type of data structure being created.
virtual DCSBaseHeader::~DCSBaseHeader () [inline, virtual]
Virtual destructor.
Important for properly destroying derived objects.
Member Function Documentation
virtual int32_t DCSBaseHeader::dataSize () const [inline, virtual]
Determine object's data size.
See also:
DCSBaseData::dataSize()
Reimplemented from DCSBaseData.
Reimplemented in DCSPlatformHeader, DCSBeamHeader, and DCSGateHeader.
Referenced by DCSCom::serverHCFunc(), and DCSCom::serverProcessRequests().
virtual int32_t DCSBaseHeader::dataSize (uint16_t version) const [inline, virtual]
Determine object's data size.
See also:
DCSBaseData::dataSize()
Reimplemented from DCSBaseData.
Reimplemented in DCSPlatformHeader, DCSBeamHeader, and DCSGateHeader.
References dataSize().
Referenced by dataSize().
virtual void* DCSBaseHeader::pack (void * buffer, int32_t size) const [pure virtual]
Prepare data for network transmission.
See also:
DCSBaseData::pack()
Implements DCSBaseData.
Implemented in DCSPlatformHeader, DCSBeamHeader, and DCSGateHeader.
Referenced by DCSCom::serverHCFunc(), and DCSCom::serverProcessRequests().
virtual int32_t DCSBaseHeader::sizeOf () const [inline, virtual]
Determine object's physical size.
See also:
DCSBaseData::sizeOf()
Reimplemented from DCSBaseData.
Reimplemented in DCSPlatformHeader, DCSBeamHeader, and DCSGateHeader.
Referenced by DCSHeaderContainer::insert(), DCSHeaderContainer::retrieve(), and DCSHeaderContainer::update().
virtual void DCSBaseHeader::unpack (const void * buffer, int32_t size) [pure virtual]
Extract data from network transmission.
See also:
DCSBaseData::unpack()
Implements DCSBaseData.
Implemented in DCSPlatformHeader, DCSBeamHeader, and DCSGateHeader.
The documentation for this class was generated from the following file:
DCSBaseHeader.h
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.