DCS Reference: DCSTimeHeader Class Reference
DCSTimeHeader Class Reference
Time header class.
#include <DCSTimeHeader.h>
Public Member Functions
DCSTimeHeader ()
Default time header constructor.
DCSTimeHeader (double realtimemod, int8_t timetype, const DCSTimeData &timedata)
Time header constructor.
virtual void clear ()
Set contents of data object to default values.
virtual void * pack (void *buffer, int32_t size) const
Prepare data for network transmission.
virtual void unpack (const void *buffer, int32_t size)
Extract data from network transmission.
virtual int32_t dataSize () const
Determine object's data size.
virtual int32_t dataSize (uint16_t version) const
Determine object's data size.
virtual int32_t sizeOf () const
Determine object's physical size.
Public Attributes
double realtimemod_
Real time modification.
int8_t timetype_
Type of time source.
DCSTimeData timedata_
Current data value.
Detailed Description
Time header class.
Class containting initial information for specifying the time in the Simdis application.
Constructor & Destructor Documentation
DCSTimeHeader::DCSTimeHeader ()
Default time header constructor.
Creates a time header object with default data values.
DCSTimeHeader::DCSTimeHeader (double realtimemod, int8_t timetype, const DCSTimeData & timedata)
Time header constructor.
Creates a time header object with the specified data values.
Parameters:
realtimemod a double specifying the percentage of real-time.
timetype a byte specifying the time source to use.
timedata a DCSTimeData object providing an initial data set for the object associated with this header.
References timedata_.
Member Function Documentation
void DCSTimeHeader::clear () [virtual]
Set contents of data object to default values.
Clears contents of data object, setting all fields to default values.
Reimplemented from DCSBaseData.
References DCSTimeData::clear(), realtimemod_, timedata_, and timetype_.
virtual int32_t DCSTimeHeader::dataSize () const [inline, virtual]
Determine object's data size.
See also:
DCSBaseData::dataSize()
Reimplemented from DCSBaseData.
References DCSTimeData::dataSize(), realtimemod_, timedata_, and timetype_.
Referenced by DCSCom::clientNegotiate(), and DCSCom::serverSendTime().
virtual int32_t DCSTimeHeader::dataSize (uint16_t version) const [inline, virtual]
Determine object's data size.
See also:
DCSBaseData::dataSize()
Reimplemented from DCSBaseData.
References dataSize().
Referenced by dataSize().
void * DCSTimeHeader::pack (void * buffer, int32_t size) const [virtual]
Prepare data for network transmission.
See also:
DCSBaseData::pack()
Implements DCSBaseData.
References DCSTimeData::pack(), DCSBaseData::packit(), realtimemod_, timedata_, and timetype_.
Referenced by DCSCom::serverSendTime().
virtual int32_t DCSTimeHeader::sizeOf () const [inline, virtual]
Determine object's physical size.
See also:
DCSBaseData::sizeOf()
Reimplemented from DCSBaseData.
void DCSTimeHeader::unpack (const void * buffer, int32_t size) [virtual]
Extract data from network transmission.
See also:
DCSBaseData::unpack()
Implements DCSBaseData.
References realtimemod_, timedata_, timetype_, DCSTimeData::unpack(), and DCSBaseData::unpackit().
Referenced by DCSCom::clientNegotiate().
Member Data Documentation
double DCSTimeHeader::realtimemod_
Real time modification.
Percentage of real-time in which the current time is being specified (as a double: 1.0 = 100%, 2.0 = 200%, 0.5 = 50%, etc).
Referenced by clear(), dataSize(), DCSConsoleLogger::logTimeHeader(), DCSStreamLogger::logTimeHeader(), DCSFileLogger::logTimeHeader(), pack(), DCSServer::sendScenarioHeader(), and unpack().
DCSTimeData DCSTimeHeader::timedata_
Current data value.
An initial data set for the object associated with this header.
Referenced by clear(), dataSize(), DCSTimeHeader(), pack(), DCSServer::sendScenarioHeader(), DCSServer::sendTime(), DCSCom::serverProcessRequests(), and unpack().
int8_t DCSTimeHeader::timetype_
Type of time source.
Source from which time is to be aquired.
See also:
Time Sources.
Referenced by clear(), dataSize(), DCSConsoleLogger::logTimeHeader(), DCSStreamLogger::logTimeHeader(), DCSFileLogger::logTimeHeader(), pack(), DCSServer::sendScenarioHeader(), and unpack().
The documentation for this class was generated from the following files:
DCSTimeHeader.h
DCSTimeHeader.cpp
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.