DCS Reference: DCSCom Namespace Reference
DCSCom Namespace Reference
DCS namespace.
Classes
struct DCSClientInfo
Client info record.
struct DCSServerInfo
Server info record.
Typedefs
typedef std::vector< SockClient * > ClientList
Client list for server.
typedef std::vector
< DCSBaseData * > HeaderList
Header list for client.
Functions
char * getServerID (const DCSServerInfo &info, char *id, int32_t len)
Retrieve server id from a server record.
char * getServerID (const DCSClientInfo &info, char *id, int32_t len)
Retrieve server id from a client record.
char * getServerIDString (const DCSServerInfo &info, char *str, int32_t len)
Retrieve server id from a server record as a human readable string.
char * getServerIDString (const DCSClientInfo &info, char *str, int32_t len)
Retrieve server id from a client record as a human readable string.
bool serverStart (DCSServerInfo &info, uint16_t servport, int8_t datamode, uint16_t dataport, const char *dataaddr, const char *iface=NULL, TTL_T ttl=1)
Server creation/initialization.
void serverStop (DCSServerInfo &info)
Server shutdown.
SockClient * serverAccept (const DCSServerInfo &info)
Accept connections from clients.
bool serverNegotiate (DCSServerInfo &info, SockClient *client, const DCSTimeHeader &time, const DCSScenarioHeader &scenario, const DCSHeaderContainer &headers)
Negotiate a new client connection.
bool serverSendDataParams (const DCSServerInfo &info, const SockClient *client)
Send information for UDP data transmission.
bool serverSendTime (const SockClient *client, const DCSTimeHeader &time)
Send time header to a client.
bool serverSendScenario (const SockClient *client, const DCSScenarioHeader &scenario)
Send scenario header to a client.
bool serverSendHeaders (const SockClient *client, const DCSHeaderContainer &headers)
Send all known platform headers to a client.
void serverHCFunc (const DCSBaseHeader *header, void *data)
Function for DCSHeaderContainer to send a header to a client.
bool serverTerminateClient (DCSServerInfo &info, SockClient *client)
Terminate a client connection.
bool serverTerminateAllClients (DCSServerInfo &info)
Terminates all client connections.
bool serverExpelVagrants (DCSServerInfo &info)
Clear out any sockets that appear in the vagrant list.
int8_t serverReadRequest (const SockClient *client)
Receive request from client.
void serverProcessRequests (DCSServerInfo &info, DCSTimeHeader &time, DCSScenarioHeader &scenario, DCSHeaderContainer &headers)
Process any requests from all clients in client list.
bool sendPlatformHeader (const DCSServerInfo &info, uint64_t id, const char *iconname, const char *callsign, const DCSPoint &dims, const DCSPoint &offset, uint32_t color, DCSObjectState_t state, DCSTrackStatus_t status, bool interpolate, const DCSCoordReferenceFrame &refFrame, const DCSPlatformData &platdata)
Send a platform header to the client.
bool sendPlatformHeader (const DCSServerInfo &info, uint64_t id, const char *iconname, const char *callsign, const DCSPoint &dims, const DCSPoint &offset, double latorigin, double lonorigin, uint32_t color, DCSObjectState_t state, DCSTrackStatus_t status, DCSCoordSystem_t coordsystem, DCSAllegience_t allegience, DCSPlatformType_t plattype, const DCSPlatformData &platdata)
Send a platform header to the client. (Deprecated)
bool sendPlatformData (const DCSServerInfo &info, uint64_t id, const DCSPoint &position, const DCSPoint &orientation, const DCSPoint &velocity, const DCSPoint &accel, double time)
Send platform data to the client.
bool sendBeamHeader (const DCSServerInfo &info, uint64_t id, const char *callsign, const DCSPoint &offset, double azimoffset, double elevoffset, bool missileOffset, double hbw, double vbw, int32_t hostid, int32_t targetid, uint32_t color, DCSObjectState_t state, DCSBeamType_t beamtype, bool interpolate, const DCSBeamData &beamdata)
Send a beam header to the client.
bool sendBeamHeader (const DCSServerInfo &info, uint64_t id, const char *callsign, const DCSPoint &offset, double azimoffset, double elevoffset, double hbw, double vbw, int32_t hostid, int32_t targetid, uint32_t color, DCSObjectState_t state, DCSBeamType_t beamtype, const DCSBeamData &beamdata)
Send a beam header to the client. (deprecated)
bool sendBeamData (const DCSServerInfo &info, uint64_t id, double time, double azim, double elev, double length)
Send beam data to the client.
bool sendGateHeader (const DCSServerInfo &info, uint64_t id, const char *callsign, const DCSPoint &offset, int32_t hostid, uint32_t color, DCSObjectState_t state, DCSGateType_t gatetype, bool interpolate, const DCSGateData &gatedata)
Send a gate header to the client.
bool sendGateHeader (const DCSServerInfo &info, uint64_t id, const char *callsign, const DCSPoint &offset, int32_t hostid, uint32_t color, DCSObjectState_t state, DCSGateType_t gatetype, const DCSGateData &gatedata)
Send a gate header to the client. (deprecated)
bool sendGateData (const DCSServerInfo &info, uint64_t id, double time, double azim, double elev, double width, double height, double minrange, double maxrange, double centroid)
Send gate data to the client.
bool sendScopeData (const DCSServerInfo &info, uint64_t id, UTILS::UnitType_t xUnits, UTILS::UnitType_t yUnits, double time, double xStart, double xStep, double yBias, double yScale, uint32_t numDataPoints, UTILS::VariableType_t dataType, uint16_t numGates, const void *data, const DCSScopeGateData *gates)
Send scope data to the client.
bool sendTimeHeader (const DCSServerInfo &info, double realtimemod, int8_t timetype, const DCSTimeData &timedata)
Send a time header to the client.
bool sendTimeData (const DCSServerInfo &info, double time)
Send time data to the client.
bool sendScenarioHeader (const DCSServerInfo &info, const DCSCoordReferenceFrame &refFrame, int16_t referenceyear, const char *classificationStr, uint32_t classificationColor, const DCSScenarioData &scendata)
Send a scenario header to the client.
bool sendScenarioHeader (const DCSServerInfo &info, double latorigin, double lonorigin, int16_t referenceyear, DCSCoordSystem_t coordsystem, DCSClassification_t classification, const DCSScenarioData &scendata)
Send a scenario header to the client. (deprecated)
bool sendScenarioData (const DCSServerInfo &info, double winddirection, double windspeed)
Send scenario data to the client.
bool sendEvent (const DCSServerInfo &info, uint64_t id, double time, int32_t data, int8_t eventtype)
Send an event to the client.
bool sendGenericData (const DCSServerInfo &info, uint64_t id, double begintime, double expiretime, const char *tag, const char *data)
Send generic data to the client.
bool sendCategoryData (const DCSServerInfo &info, uint64_t id, double timeValue, const char *name, const char *value)
Send generic data to the client.
bool sendUDPData (const DCSServerInfo &info, const DCSBaseData *data)
Send data to the client via UDP.
bool sendTCPData (const DCSServerInfo &info, int8_t type, const DCSBaseData *data)
Send data to the client via TCP.
bool sendPlatformHeader (const DCSServerInfo &info, const DCSPlatformHeader *data)
Send a platform header to the client.
bool sendPlatformData (const DCSServerInfo &info, const DCSPlatformData *data)
Send platform data to the client.
bool sendBeamHeader (const DCSServerInfo &info, const DCSBeamHeader *data)
Send a beam header to the client.
bool sendBeamData (const DCSServerInfo &info, const DCSBeamData *data)
Send beam data to the client.
bool sendGateHeader (const DCSServerInfo &info, const DCSGateHeader *data)
Send a gate header to the client.
bool sendGateData (const DCSServerInfo &info, const DCSGateData *data)
Send gate data to the client.
bool sendScopeData (const DCSServerInfo &info, const DCSScopeData *data)
Send gate data to the client.
bool sendTimeHeader (const DCSServerInfo &info, const DCSTimeHeader *data)
Send a time header to the client.
bool sendTimeData (const DCSServerInfo &info, const DCSTimeData *data)
Send time data to the client.
bool sendScenarioHeader (const DCSServerInfo &info, const DCSScenarioHeader *data)
Send a scenario header to the client.
bool sendScenarioData (const DCSServerInfo &info, const DCSScenarioData *data)
Send scenario data to the client.
bool sendEvent (const DCSServerInfo &info, const DCSEvent *data)
Send an event to the client.
bool sendGenericData (const DCSServerInfo &info, const DCSGenericData *data)
Send generic data to the client.
bool sendCategoryData (const DCSServerInfo &info, const DCSCategoryData *data)
Send category data to the client.
bool clientConnect (DCSClientInfo &info, uint16_t port, const char *addr, const char *iface=NULL, bool block=true)
Connect to server.
bool clientNegotiate (DCSClientInfo &info, DCSTimeHeader &time, DCSScenarioHeader &scenario, uint32_t *headers=NULL, uint16_t *version=NULL)
Negotiate a new connection with server - without reading headers.
bool clientNegotiate (DCSClientInfo &info, DCSTimeHeader &time, DCSScenarioHeader &scenario, HeaderList &headers, uint16_t *version=NULL)
Negotiate a new connection with server - reading all headers.
void clientDisconnect (DCSClientInfo &info)
Close an active connection.
bool clientRequest (const DCSClientInfo &info, int8_t request)
Request data from server.
bool clientHeaderRequest (const DCSClientInfo &info, uint64_t id)
Request a platform, beam, or gate header from server.
DCSBaseData * readTCPData (const DCSClientInfo &info)
Receive data from TCP data channel.
DCSBaseData * readUDPData (const DCSClientInfo &info)
Receive data from UDP data channel.
Detailed Description
DCS namespace.
Namespace defining functions for basic connection and communication with DCS server and clients.
Typedef Documentation
typedef std::vector<SockClient*> DCSCom::ClientList
Client list for server.
A list of addresses for SockClient objects representing client connections to the server.
typedef std::vector<DCSBaseData*> DCSCom::HeaderList
Header list for client.
A list of headers retrieved from the server during a connection negotiation.
Function Documentation
bool DCSCom::clientConnect (DCSClientInfo & info, uint16_t port, const char * addr, const char * iface = NULL, bool block = true)
Connect to server.
Establish a connection to a listening server. This operation may be performed with either blocking or non-blcoking I/O.
Parameters:
info a DCSClientInfo structure to be filled with data specific too the client being created. Resources required by DCSClientInfo will be allocated by this function. A matching call to clientDisconnect is required to properly free these resources, when finished.
port an unsinged integer specifying the port with which to connect.
addr network address of server with which to connect (eg. "192.168.44.5").
iface interface to connect and receive data through (eg. "127.0.0.1" for loopback or the ip address of an installed network card).
block a boolean value specifying that the connection operation be performed with blocking or non-blocking I/O. A non blocking operation may return before the connection is established, requiring the calling process to test for a completed connection before the socket may be used.
Returns:
true if successful, false if failed. On failure, no resources will have been allocated, so a call to clientDisconnect is unnecessary.
See also:
clientDisconnect()
References DCSCom::DCSClientInfo::servsock.
void DCSCom::clientDisconnect (DCSClientInfo & info)
Close an active connection.
Closes connection and frees resources allocated for DCSClientInfo by clientConnect.
Parameters:
info a DCSClientInfo structure containing data sepcific to the client to be disconnected. Resources allocated for this structure by clientConnect will be freed.
Returns:
true if successful, false if failed. Failure indicates that one or both of the data and client sockets did not exist.
See also:
clientConnect()
References clientRequest(), DCSCom::DCSClientInfo::datasock, DCSCom::DCSClientInfo::datatype, DCSDATA_UNCONNECTED, DCSREQUEST_DISCONNECT, and DCSCom::DCSClientInfo::servsock.
bool DCSCom::clientHeaderRequest (const DCSClientInfo & info, uint64_t id)
Request a platform, beam, or gate header from server.
Send a header request to server. Data sent by server as a result of this request is to be read with the readTCPData function. Prior to using this function the client must be connected to the server and the DCSClientInfo structure initialized through a call to clientConnect.
Parameters:
info a DCSClientInfo structure specifying the socket with which data requests are to be sent.
id a 64-bit unsigned integer specifying the id for the header to retrieve.
Returns:
true if successful, false if failed.
See also:
Client Requests
clientConnect()
readTCPData()
References DCSREQUEST_HEADER, and DCSCom::DCSClientInfo::servsock.
bool DCSCom::clientNegotiate (DCSClientInfo & info, DCSTimeHeader & time, DCSScenarioHeader & scenario, uint32_t * headers = NULL, uint16_t * version = NULL)
Negotiate a new connection with server - without reading headers.
Negotiates a connection with a server. This function is used to negotiate a client connection that was made by clientConnect(). The negotiation is handled separately from clientConnect for use by clients that want to read the headers separately. This is useful for clients that want to process headers while performing other operations simultaneously. This operation may only be performed with blocking I/O. If the function receives a non-blocking socket, it will set the socket to blocking mode before performing the operation and reset it to the non-blocking mode after the operation has completed.
Parameters:
info a DCSClientInfo structure to receive the UDP data mode for the connection.
time a DCSTimeHeader structure to be received by the client as part of the connection negotiation.
scenario a DCSScenarioHeader structure to be received by the client as part of the connection negotiation.
headers a pointer to integer for retrieving the number of DCSBaseData derived objects to be subsequently received by the client as part of the connection negotiation.
version an unsigned short to be filled the DCS protocol version number supported by the DCS server. If a client negotiaion fails, check this value to make sure it matches the version of the DCS protocol employed by the client.
Returns:
true if successful, false if failed. On failure, client connection is not closed by this function. The application should close the socket explicitly with a call to clientDisconnect if this function fails. The contents of the HeaderList, if any, will also have ot be destroyed explicitly through use of the 'delete' operator.
See also:
clientConnect()
clientDisconnect()
DCSHeaderInfo
References clientRequest(), DCSTimeHeader::dataSize(), DCSScenarioHeader::dataSize(), DCSCom::DCSClientInfo::datasock, DCSCom::DCSClientInfo::datatype, DCSDATA_BROADCAST, DCSDATA_MULTICAST, DCSDATA_UNCONNECTED, DCSDATA_UNICAST, DCSREQUEST_CONNECT, DCSREQUEST_DATAMODE, DCSREQUEST_HEADERS, DCSREQUEST_SCENARIO, DCSREQUEST_TIME, DCSREQUEST_VERSION, DCSCom::DCSClientInfo::server_id, DCSCom::DCSClientInfo::serverVersion, DCSCom::DCSClientInfo::servsock, DCSTimeHeader::unpack(), and DCSScenarioHeader::unpack().
bool DCSCom::clientNegotiate (DCSClientInfo & info, DCSTimeHeader & time, DCSScenarioHeader & scenario, HeaderList & headers, uint16_t * version = NULL)
Negotiate a new connection with server - reading all headers.
Negotiates a connection with a server. This function is used to negotiate a client connection that was made by clientConnect(). The negotiation is handled separately from clientConnect for use by clients that are designed to be multithreaded. The function will not return until all platform, beam, and gate headers have been retrieved from the server. This operation may only be performed with blocking I/O. If the function receives a non-blocking socket, it will set the socket to blocking mode before performing the operation and reset it to the non-blocking mode after the operation has completed.
Parameters:
info a DCSClientInfo structure to receive the UDP data mode for the connection.
time a DCSTimeHeader structure to be received by the client as part of the connection negotiation.
scenario a DCSScenarioHeader structure to be received by the client as part of the connection negotiation.
headers a HeaderList object to be filled with DCSBaseData derived objects received by the client as part of the connection negotiation.
version an unsigned short to be filled the DCS protocol version number supported by the DCS server. If a client negotiaion fails, check this value to make sure it matches the version of the DCS protocol employed by the client.
Returns:
true if successful, false if failed. On failure, client connection is not closed by this function. The application should close the socket explicitly with a call to clientDisconnect if this function fails. The contents of the HeaderList, if any, will also have ot be destroyed explicitly through use of the 'delete' operator.
See also:
clientConnect()
clientDisconnect()
DCSHeaderInfo
References clientRequest(), DCSTimeHeader::dataSize(), DCSScenarioHeader::dataSize(), DCSCom::DCSClientInfo::datasock, DCSCom::DCSClientInfo::datatype, DCSBEAMHEADER, DCSDATA_BROADCAST, DCSDATA_MULTICAST, DCSDATA_UNCONNECTED, DCSDATA_UNICAST, DCSGATEHEADER, DCSREQUEST_CONNECT, DCSREQUEST_DATAMODE, DCSREQUEST_HEADERS, DCSREQUEST_SCENARIO, DCSREQUEST_TIME, DCSREQUEST_VERSION, DCSBaseData::getType(), readTCPData(), DCSCom::DCSClientInfo::server_id, DCSCom::DCSClientInfo::serverVersion, DCSCom::DCSClientInfo::servsock, DCSTimeHeader::unpack(), and DCSScenarioHeader::unpack().
bool DCSCom::clientRequest (const DCSClientInfo & info, int8_t request)
Request data from server.
Send a data request to server. Data sent by server as a result of this request is to be read with the readUDPData and readTCPData functions. Prior to using this function the client must be connected to the server and the DCSClientInfo structure initialized through a call to clientConnect. Attempts to send DCSREQUEST_HEADER thorugh this function will result in error. DCSREQUEST_HEADER must be made through clientHeaderRequest.
Parameters:
info a DCSClientInfo structure specifying the socket with which data requests are to be sent.
request an unsinged byte specifying the type of data request being made.
Returns:
true if successful, false if failed.
See also:
Client Requests
clientConnect()
clientHeaderRequest()
readTCPData()
readUPPData()
References DCSREQUEST_EVENT, DCSREQUEST_HEADER, and DCSCom::DCSClientInfo::servsock.
Referenced by clientDisconnect(), and clientNegotiate().
char * DCSCom::getServerID (const DCSServerInfo & info, char * id, int32_t len)
Retrieve server id from a server record.
Retrieve ID for server defined by the specified server info record.
Parameters:
info a DCSServerInfo structure from which the id will be retrieved.
id a character buffer to be filled with the server id.
len an integer specifying the size of the 'id' parameter. The length should be at least DCS_SERVERIDSZ.
Returns:
a pointer to the 'id' parameter.
References DCSCom::DCSServerInfo::server_id.
char * DCSCom::getServerID (const DCSClientInfo & info, char * id, int32_t len)
Retrieve server id from a client record.
Retrieve ID for the server associated with the client defined by the specified client info record.
Parameters:
info a DCSClientInfo structure from which the id will be retrieved.
id a character buffer to be filled with the server id.
len an integer specifying the size of the 'id' parameter. The length should be at least DCS_SERVERIDSZ.
Returns:
a pointer to the 'id' parameter.
References DCSCom::DCSClientInfo::server_id.
char * DCSCom::getServerIDString (const DCSServerInfo & info, char * str, int32_t len)
Retrieve server id from a server record as a human readable string.
Retrieve ID for server defined by the specified server info record as a human readable string.
Parameters:
info a DCSServerInfo structure from which the id will be retrieved.
str a character buffer to be filled with the server id string.
len an integer specifying the size of the 'str' parameter.
Returns:
a pointer to the 'str' parameter.
References DCSCom::DCSServerInfo::server_id.
char * DCSCom::getServerIDString (const DCSClientInfo & info, char * str, int32_t len)
Retrieve server id from a client record as a human readable string.
Retrieve ID for the server associated with the client defined by the specified client info record as a human readable string.
Parameters:
info a DCSClientInfo structure from which the id will be retrieved.
str a character buffer to be filled with the server id string.
len an integer specifying the size of the 'str' parameter.
Returns:
a pointer to the 'str' parameter.
References DCSCom::DCSClientInfo::server_id.
DCSBaseData * DCSCom::readTCPData (const DCSClientInfo & info)
Receive data from TCP data channel.
Reads a single data object from the TCP data channel.
Parameters:
info a DCSClientInfo structure specifying the socket with which data is to be received.
Returns:
a pointer to a DCBaseData object. The object's type may be indentified with a call to DCSBeamData::getType(). The application is responsible for freeing the memory allocated for the object through use of the 'delete' operator.
See also:
DCSBeamData::getType()
References DCSBaseData::dataSize(), DCSBEAMHEADER, DCSCATEGORYDATA, DCSEVENT, DCSGATEHEADER, DCSGENERICDATA, DCSPLATFORMHEADER, DCSSCENARIOHEADER, DCSTIMEHEADER, DCSUNKNOWN, DCSCom::DCSClientInfo::serverVersion, DCSCom::DCSClientInfo::servsock, and DCSBaseData::unpack().
Referenced by clientNegotiate().
DCSBaseData * DCSCom::readUDPData (const DCSClientInfo & info)
Receive data from UDP data channel.
Reads a single data object from the UDP data channel.
Parameters:
info a DCSClientInfo structure specifying the socket with which data is to be received.
Returns:
a pointer to a DCBaseData object. The object's type may be indentified with a call to DCSBeamData::getType(). The application is responsible for freeing the memory allocated for the object through use of the 'delete' operator.
See also:
DCSBeamData::getType()
References DCSBaseData::dataSize(), DCSCom::DCSClientInfo::datasock, DCSBEAMDATA, DCSCATEGORYDATA, DCSGATEDATA, DCSGENERICDATA, DCSPLATFORMDATA, DCSSCENARIODATA, DCSSCOPEDATA, DCSTIMEDATA, DCSUNKNOWN, DCSCom::DCSClientInfo::server_id, DCSCom::DCSClientInfo::serverVersion, and DCSBaseData::unpack().
bool DCSCom::sendBeamData (const DCSServerInfo & info, uint64_t id, double time, double azim, double elev, double length)
Send beam data to the client.
Send a DCSBeamData object, created from the specified values, from the server to the client. Beam data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
time a double specifying the time at which the data is valid.
azim a double specifying the beam's azimuth.
elev a double specifying the beam's elevation.
length a double specifying the beam's length.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendBeamData (const DCSServerInfo & info, const DCSBeamData * data)
Send beam data to the client.
Send a DCSBeamData object from the server to the client. Beam data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSBeamData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendBeamHeader (const DCSServerInfo & info, uint64_t id, const char * callsign, const DCSPoint & offset, double azimoffset, double elevoffset, bool missileOffset, double hbw, double vbw, int32_t hostid, int32_t targetid, uint32_t color, DCSObjectState_t state, DCSBeamType_t beamtype, bool interpolate, const DCSBeamData & beamdata)
Send a beam header to the client.
Send a DCSBeamHeader object, created from the specified values, from the server to the client. Beam headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
callsign a string specifying the call sign.
offset a DCSPoint specifying the beam's offset from the center of the host platform.
azimoffset a double specifying the azimuth offset.
elevoffset a double specifying the elevation offset.
missileOffset Applies an offset to the beam to eminate from edge of icon, useful for missiles
hbw a double specifying the horizontal beam width.
vbw a double specifying the vertical beam width.
hostid an integer specifying the id of the platform with which the beam is attached.
targetid an integer specifying the id of the target to which the beam is tracking.
color an unsigned 32-bit integer specifying the beam's color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
state a byte specifying the beam's DCS state: no change(0), on(1), off(2), expired(3)
beamtype a byte specifying the beam type.
interpolate Indicates whether position should be interpolated between data points
beamdata a DCSBeamData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendBeamHeader (const DCSServerInfo & info, uint64_t id, const char * callsign, const DCSPoint & offset, double azimoffset, double elevoffset, double hbw, double vbw, int32_t hostid, int32_t targetid, uint32_t color, DCSObjectState_t state, DCSBeamType_t beamtype, const DCSBeamData & beamdata)
Send a beam header to the client. (deprecated)
Send a DCSBeamHeader object, created from the specified values, from the server to the client. Beam headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
callsign a string specifying the call sign.
offset a DCSPoint specifying the beam's offset from the center of the host platform.
azimoffset a double specifying the azimuth offset.
elevoffset a double specifying the elevation offset.
hbw a double specifying the horizontal beam width.
vbw a double specifying the vertical beam width.
hostid an integer specifying the id of the platform with which the beam is attached.
targetid an integer specifying the id of the target to which the beam is tracking.
color an unsigned 32-bit integer specifying the beam's color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
state a byte specifying the beam's DCS state: no change(0), on(1), off(2), expired(3)
beamtype a byte specifying the beam type.
beamdata a DCSBeamData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendBeamHeader (const DCSServerInfo & info, const DCSBeamHeader * data)
Send a beam header to the client.
Send a DCSBeamHeader object from the server to the client. Beam headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSBeamHeader object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendCategoryData (const DCSServerInfo & info, uint64_t id, double timeValue, const char * name, const char * value)
Send generic data to the client.
Send a DCSCategoryData object, created from the specified values, from the server to the client. Category data is transmitted via the TCP channel. This function currently has the requirement that both the tag and data arguments be provided as null terminated strings.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
timeValue a double specifying the time of validity.
name an array of bytes specifying the category data category name.
value an array of bytes specifying the category data value.
Returns:
true if successful, false if failed.
References sendCategoryData().
Referenced by sendCategoryData(), and sendPlatformHeader().
bool DCSCom::sendCategoryData (const DCSServerInfo & info, const DCSCategoryData * data)
Send category data to the client.
Send a DCSCategoryData object from the server to the client. Category data is transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSCategoryData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendEvent (const DCSServerInfo & info, uint64_t id, double time, int32_t data, int8_t eventtype)
Send an event to the client.
Send a DCSEvent object, created from the specified values, from the server to the client. Event data is transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
time a double specifying the execution time of the event.
data an integer containing variant data specifying either a target id, color, state, or status.
eventtype a byte specifying the event type, also indicating the type of data.
Returns:
true if successful, false if failed.
References DCSREQUEST_EVENT, and sendTCPData().
Referenced by DCSServer::sendBeamInterpolatePosition(), DCSServer::sendCallsignEvent(), DCSServer::sendClassificationEvent(), DCSServer::sendColorEvent(), DCSServer::sendExpireEvent(), DCSServer::sendGateInterpolatePosition(), DCSServer::sendIconNameEvent(), DCSServer::sendPlatformInterpolate(), DCSServer::sendStateEvent(), DCSServer::sendTargetEvent(), and DCSServer::sendTrackQualityEvent().
bool DCSCom::sendEvent (const DCSServerInfo & info, const DCSEvent * data)
Send an event to the client.
Send a DCSEvent object from the server to the client. Event data is transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSEvent object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSREQUEST_EVENT, and sendTCPData().
bool DCSCom::sendGateData (const DCSServerInfo & info, uint64_t id, double time, double azim, double elev, double width, double height, double minrange, double maxrange, double centroid)
Send gate data to the client.
Send a DCSGateData object, created from the specified values, from the server to the client. Gate data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
time a double specifying the time at which the data is valid.
azim a double specifying the gate's azimuth.
elev a double specifying the gate's elevation.
width a double specifying the gate's width.
height a double specifying the gate's height.
minrange a double specifying the gate's start distance.
maxrange a double specifying the gate's end distance.
centroid a double specifying the gate's centroid distance.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendGateData (const DCSServerInfo & info, const DCSGateData * data)
Send gate data to the client.
Send a DCSGateData object from the server to the client. Gate data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSGateData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendGateHeader (const DCSServerInfo & info, uint64_t id, const char * callsign, const DCSPoint & offset, int32_t hostid, uint32_t color, DCSObjectState_t state, DCSGateType_t gatetype, bool interpolate, const DCSGateData & gatedata)
Send a gate header to the client.
Send a DCSGateHeader object, created from the specified values, from the server to the client. Gate headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
callsign a string specifying the call sign.
offset a DCSPoint specifying the gate's offset from the centroid's position.
hostid an integer specifying the id of the associated beam.
color an unsigned 32-bit integer specifying the gate's color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
state a byte specifying the gate's DCS state: no change(0), on(1), off(2), expired(3)
gatetype a byte specifying the gate type.
interpolate Indicates whether position should be interpolated between data points
gatedata a DCSGateData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendGateHeader (const DCSServerInfo & info, uint64_t id, const char * callsign, const DCSPoint & offset, int32_t hostid, uint32_t color, DCSObjectState_t state, DCSGateType_t gatetype, const DCSGateData & gatedata)
Send a gate header to the client. (deprecated)
Send a DCSGateHeader object, created from the specified values, from the server to the client. Gate headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
callsign a string specifying the call sign.
offset a DCSPoint specifying the gate's offset from the centroid's position.
hostid an integer specifying the id of the associated beam.
color an unsigned 32-bit integer specifying the gate's color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
state a byte specifying the gate's DCS state: no change(0), on(1), off(2), expired(3)
gatetype a byte specifying the gate type.
gatedata a DCSGateData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendGateHeader (const DCSServerInfo & info, const DCSGateHeader * data)
Send a gate header to the client.
Send a DCSGateHeader object from the server to the client. Gate headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSGateHeader object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendGenericData (const DCSServerInfo & info, uint64_t id, double begintime, double expiretime, const char * tag, const char * data)
Send generic data to the client.
Send a DCSGenericData object, created from the specified values, from the server to the client. Generic data is transmitted via the UDP channel. This function currently has the requirement that both the tag and data arguments be provided as null terminated strings.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
begintime a double specifying the activation time.
expiretime a double specifying the deactivation time.
tag an array of bytes specifying the generic data tag.
data an array of bytes specifying the generic data.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendGenericData (const DCSServerInfo & info, const DCSGenericData * data)
Send generic data to the client.
Send a DCSGenericData object from the server to the client. Generic data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSGenericData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendPlatformData (const DCSServerInfo & info, uint64_t id, const DCSPoint & position, const DCSPoint & orientation, const DCSPoint & velocity, const DCSPoint & accel, double time)
Send platform data to the client.
Send a DCSPlatformData object, created from the specified values, from the server to the client. Platform data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
position a DCSPoint specifying the object's position.
orientation a DCSPoint specifying the object's orientation.
velocity a DCSPoint specifying the object's velocity.
accel a DCSPoint specifying the object's acceleration.
time a double specifying the time at which the data is valid.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendPlatformData (const DCSServerInfo & info, const DCSPlatformData * data)
Send platform data to the client.
Send a DCSPlatformData object from the server to the client. Platform data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSPlatformData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendPlatformHeader (const DCSServerInfo & info, uint64_t id, const char * iconname, const char * callsign, const DCSPoint & dims, const DCSPoint & offset, uint32_t color, DCSObjectState_t state, DCSTrackStatus_t status, bool interpolate, const DCSCoordReferenceFrame & refFrame, const DCSPlatformData & platdata)
Send a platform header to the client.
Send a DCSPlatformHeader object, created from the specified values, from the server to the client. Platform headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
iconname a string specifying the icon name.
callsign a string specifying the call sign.
dims a DCSPoint structure specifying the icon dimensions.
offset a DCSPoint structure specifying the platform's offset from it's specified position.
color an unsigned 32-bit integer specifying the platform's color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
state a byte specifying the platform's DCS state: no change(0), on(1), off(2), expired(3)
status a byte specifying the platform's current status from the server: dropped(0), live(1)
interpolate Indicates whether position and orientation should be interpolated between data points
refFrame Coordinate reference frame of the platform's data.
platdata a DCSPlatformData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendPlatformHeader (const DCSServerInfo & info, uint64_t id, const char * iconname, const char * callsign, const DCSPoint & dims, const DCSPoint & offset, double latorigin, double lonorigin, uint32_t color, DCSObjectState_t state, DCSTrackStatus_t status, DCSCoordSystem_t coordsystem, DCSAllegience_t allegience, DCSPlatformType_t plattype, const DCSPlatformData & platdata)
Send a platform header to the client. (Deprecated)
Send a DCSPlatformHeader object, created from the specified values, from the server to the client. Platform headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
iconname a string specifying the icon name.
callsign a string specifying the call sign.
dims a DCSPoint structure specifying the icon dimensions.
offset a DCSPoint structure specifying the platform's offset from it's specified position.
latorigin a double specifying the latitude topo origin.
lonorigin a double specifying the longitude topo origin.
color an unsigned 32-bit integer specifying the platform's color in RRGGBBAA hexadecimal(00-FF) notation: RR=red, GG=green, BB=blue, AA=alpha component.
state a byte specifying the platform's DCS state: no change(0), on(1), off(2), expired(3)
status a byte specifying the platform's current status from the server: dropped(0), live(1)
coordsystem a byte specifying the coordinate system.
allegience a byte specifying the allegience of the platform.
plattype a byte specifying the platform type.
platdata a DCSPlatformData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, sendCategoryData(), sendTCPData(), and DCSPlatformData::time_.
bool DCSCom::sendPlatformHeader (const DCSServerInfo & info, const DCSPlatformHeader * data)
Send a platform header to the client.
Send a DCSPlatformHeader object from the server to the client. Platform headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSPlatformHeader object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSREQUEST_HEADER, and sendTCPData().
bool DCSCom::sendScenarioData (const DCSServerInfo & info, double winddirection, double windspeed)
Send scenario data to the client.
Send a DCSScenarioData object, created from the specified values, from the server to the client. Scenario data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
winddirection a double specifying the wind direction.
windspeed a double specifying the wind speed.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendScenarioData (const DCSServerInfo & info, const DCSScenarioData * data)
Send scenario data to the client.
Send a DCSScenarioData object from the server to the client. Scenario data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSScenarioData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendScenarioHeader (const DCSServerInfo & info, const DCSCoordReferenceFrame & refFrame, int16_t referenceyear, const char * classificationStr, uint32_t classificationColor, const DCSScenarioData & scendata)
Send a scenario header to the client.
Send a DCSScenarioHeader object, created from the specified values, from the server to the client. Scenario headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
refFrame Default coordinate reference frame of the scenario and other scenario options
referenceyear a short specifying the calendar year.
classificationStr character array for the classification text
classificationColor 0xAABBGGRR color of the classification text
scendata a DCSScenarioData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_SCENARIO, and sendTCPData().
bool DCSCom::sendScenarioHeader (const DCSServerInfo & info, double latorigin, double lonorigin, int16_t referenceyear, DCSCoordSystem_t coordsystem, DCSClassification_t classification, const DCSScenarioData & scendata)
Send a scenario header to the client. (deprecated)
Send a DCSScenarioHeader object, created from the specified values, from the server to the client. Scenario headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
latorigin a double specifying the latitude topo origin.
lonorigin a double specifying the longitude topo origin.
referenceyear a short specifying the calendar year.
coordsystem a byte specifying the overall coordinate system.
classification a byte specifying the data classification.
scendata a DCSScenarioData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_SCENARIO, and sendTCPData().
bool DCSCom::sendScenarioHeader (const DCSServerInfo & info, const DCSScenarioHeader * data)
Send a scenario header to the client.
Send a DCSScenarioHeader object from the server to the client. Scenario headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSScenarioHeader object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSREQUEST_SCENARIO, and sendTCPData().
bool DCSCom::sendScopeData (const DCSServerInfo & info, uint64_t id, UTILS::UnitType_t xUnits, UTILS::UnitType_t yUnits, double time, double xStart, double xStep, double yBias, double yScale, uint32_t numDataPoints, UTILS::VariableType_t dataType, uint16_t numGates, const void * data, const DCSScopeGateData * gates)
Send scope data to the client.
Send a DCSScopeData object, created from the specified values, from the server to the client. Scope data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
id an unsigned integer specifying the object's id.
xUnits an int16 specifying the object's x-units.
yUnits an int16 specifying the object's y-units.
time a double specifying the object's time.
xStart a double specifying the start of the object's x values.
xStep a double specifying the object's x step.
yBias a double specifying the object's y bias.
yScale a double specifying the object's y scale.
numDataPoints an int32 specifying the number of data points in the data array.
dataType an int8 specifying the data type of the object's array data.
numGates an unsigned int16 specifying the object's number of gates.
data a char array containing the object's data points.
gates a DCSCopeGateData array containing the object's gates.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendScopeData (const DCSServerInfo & info, const DCSScopeData * data)
Send gate data to the client.
Send a DCSScopeData object from the server to the client. Gate data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSScopeData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendTCPData (const DCSServerInfo & info, int8_t type, const DCSBaseData * data)
Send data to the client via TCP.
Send a DCSBaseData derived object from the server to the client via the TCP channel.
Parameters:
info a DCSServerInfo structure containing the socket to be used for data transmission.
type a byte specifying the type of data be sent (as a DCS request type). To be sent prior to transmission of actual data so client knows what to expect.
data a pointer to the DCSBaseData derived object to be transmitted to the client.
Returns:
true if successful, false if failed.
See also:
Client Requests
References DCSCom::DCSServerInfo::clientlist, DCSBaseData::dataSize(), DCSBaseData::pack(), and DCSCom::DCSServerInfo::serverVersion.
Referenced by sendBeamHeader(), sendCategoryData(), sendEvent(), sendGateHeader(), sendPlatformHeader(), sendScenarioHeader(), and sendTimeHeader().
bool DCSCom::sendTimeData (const DCSServerInfo & info, double time)
Send time data to the client.
Send a DCSTimeData object, created from the specified values, from the server to the client. Time data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
time a double specifying the current time.
Returns:
true if successful, false if failed.
References sendUDPData().
Referenced by DCSServer::sendTime().
bool DCSCom::sendTimeData (const DCSServerInfo & info, const DCSTimeData * data)
Send time data to the client.
Send a DCSTimeData object from the server to the client. Time data is transmitted via the UDP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSTimeData object to be transmitted to the client.
Returns:
true if successful, false if failed.
References sendUDPData().
bool DCSCom::sendTimeHeader (const DCSServerInfo & info, double realtimemod, int8_t timetype, const DCSTimeData & timedata)
Send a time header to the client.
Send a DCSTimeHeader object, created from the specified values, from the server to the client. Time headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
realtimemod a double specifying the percentage of real-time.
timetype a byte specifying the time source to use.
timedata a DCSTimeData object providing an initial data set for the object associated with this header.
Returns:
true if successful, false if failed.
References DCSREQUEST_TIME, and sendTCPData().
bool DCSCom::sendTimeHeader (const DCSServerInfo & info, const DCSTimeHeader * data)
Send a time header to the client.
Send a DCSTimeHeader object from the server to the client. Time headers are transmitted via the TCP channel.
Parameters:
info a DCSServerInfo structure specifying the socket to be used for data transmission.
data a pointer to the DCSTimeHeader object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSREQUEST_TIME, and sendTCPData().
bool DCSCom::sendUDPData (const DCSServerInfo & info, const DCSBaseData * data)
Send data to the client via UDP.
Send a DCSBaseData derived object from the server to the client via the UDP channel.
Parameters:
info a DCSServerInfo structure containing the socket to be used for data transmission.
data a pointer to the DCSBaseData derived object to be transmitted to the client.
Returns:
true if successful, false if failed.
References DCSCom::DCSServerInfo::clientlist, DCSCom::DCSServerInfo::dataport, DCSBaseData::dataSize(), DCSCom::DCSServerInfo::datasock, DCSCom::DCSServerInfo::datatype, DCSDATA_UNCONNECTED, DCSDATA_UNICAST, DCSBaseData::pack(), DCSCom::DCSServerInfo::server_id, and DCSCom::DCSServerInfo::serverVersion.
Referenced by sendBeamData(), sendGateData(), sendGenericData(), sendPlatformData(), sendScenarioData(), sendScopeData(), and sendTimeData().
SockClient * DCSCom::serverAccept (const DCSServerInfo & info)
Accept connections from clients.
Accepts a client connection, creating a new SockClient object for the client. Prior to using this function the server must be started and the DCSServerInfo structure initialized through a call to serverStart. A new client connection must processed with a call to serverNegotiate.
Parameters:
info a DCSServerInfo structure specifying the server socket to accept connections with.
Returns:
NULL if unsuccessful or a pointer to a SockClient object for the newly accepted connection if successful.
See also:
serverStart()
References DCSCom::DCSServerInfo::servsock.
Referenced by DCSServer::idle().
bool DCSCom::serverExpelVagrants (DCSServerInfo & info)
Clear out any sockets that appear in the vagrant list.
Removes the vagrant client sockets from the client and vagrant lists maintained by DCSServerInfo, and frees resources allocated for the SockClient by serverAccept. It's a good idea to use this function whenever a failed connection is detected, in order to keep the contents of the client and vagrant lists maintained by DCSServerInfo in sync with each other.
Parameters:
info a DCSServerInfo structure containing the client list and the vagrant list that the vagrant sockets are to be removed from.
Returns:
true if successful, false if failed.
References serverTerminateClient(), and DCSCom::DCSServerInfo::vagrants.
Referenced by DCSServer::idle().
void DCSCom::serverHCFunc (const DCSBaseHeader * header, void * data)
Function for DCSHeaderContainer to send a header to a client.
Sends a single header to a client. This function is supplied as an argument to the traverse method provided by DCSHeaderContainer. It is used by serverNegotiate for distributing headers.
Parameters:
header a DCSBaseData derived object to be sent to the client.
data a pointer to the socket to be used for transmitting the header.
References DCSBaseHeader::dataSize(), and DCSBaseHeader::pack().
Referenced by serverSendHeaders().
bool DCSCom::serverNegotiate (DCSServerInfo & info, SockClient * client, const DCSTimeHeader & time, const DCSScenarioHeader & scenario, const DCSHeaderContainer & headers)
Negotiate a new client connection.
Negotiates a connection with a newly accepeted client. This function is used to process a client that was accepted by serverAccept(). The negotiation is handled separately from serverAccept for use by servers that are designed to be multithreaded. With the accept and negotiate functions being handled separately, a new thread can be spawned everytime a client is received by serverAccept. This new thread will call serverNegotiate and handle any future client requests. This way the thread responsible for accepting connections can accept a new client and go right back to listening for new connections without having to take the time to process the newly accepted connection. Special care must be taken with this function when used in multithreaded servers. It is very important that the DCSHeaderContainer not be modified while the negotiation is taking place. Because DCSHeaderContainer is not itself re-entrant, the server application will be required to add the approproate mutual exclusion locks for reads and writes to the DCSHeaderContainer database. The client socket will be added to the client list found in DCSServerInfo if the negotiation is successful.
Parameters:
info a DCSServerInfo structure specifying the UDP data mode for the connection.
client a newly accepted SockClient that needs to be connected to the server.
time a DCSTimeHeader structure to be sent to the new client as part of the connection negotiation.
scenario a DCSScenarioHeader structure to be sent to the new client as part of the connection negotiation.
headers a DCSHeaderContainer providing the headers to be sent to the new client as part of the connection negotiation.
Returns:
true if successful, false if failed. On success, the socket is added to the client list found in DCSServerInfo. On failure, client connection is not closed by this function. The application should close the connection explicitly with a call to serverTerminateClient if this function fails. serverTerminateClient will free the resources allocated by serverAccept.
See also:
serverAccept()
serverTerminateClient()
References DCSCom::DCSServerInfo::clientlist, DCSREQUEST_CONNECT, DCSREQUEST_DATAMODE, DCSREQUEST_HEADERS, DCSREQUEST_SCENARIO, DCSREQUEST_TIME, DCSREQUEST_VERSION, DCSCom::DCSServerInfo::server_id, serverReadRequest(), serverSendDataParams(), serverSendHeaders(), serverSendScenario(), and serverSendTime().
Referenced by DCSServer::idle().
void DCSCom::serverProcessRequests (DCSServerInfo & info, DCSTimeHeader & time, DCSScenarioHeader & scenario, DCSHeaderContainer & headers)
Process any requests from all clients in client list.
Test each client in the client list for a pending request, and, if a request is pending, process that request. This function is rather simple, and is provided only as a convenience for processing client requests. If a more detailed request handler is required (eg. needs to log requests, etc) this function can easily be extended. Note that this function will add vagrant clients to the vagrant list, but will not expel them.
Parameters:
info a DCSServerInfo structure containing the client list that the client sockets to process.
time a DCSTimeHeader structure to be sent to a client upon request.
scenario a DCSScenarioHeader structure to be sent to a client upon request.
headers a DCSHeaderContainer providing the headers to be sent to a client upon request.
References DCSHeaderGroup::baseheader_, DCSCom::DCSServerInfo::clientlist, DCSBaseHeader::dataSize(), DCSEVENT_STATE, DCSREQUEST_DATAMODE, DCSREQUEST_DISCONNECT, DCSREQUEST_EVENT, DCSREQUEST_HEADER, DCSREQUEST_HEADERS, DCSREQUEST_KEEPALIVE, DCSREQUEST_SCENARIO, DCSREQUEST_TIME, DCSSTATE_EXPIRE, DCSBaseHeader::pack(), DCSEvent::pack(), DCSHeaderContainer::retrieve(), serverReadRequest(), serverSendDataParams(), serverSendHeaders(), serverSendScenario(), serverSendTime(), DCSCom::DCSServerInfo::serverVersion, DCSTimeData::time_, DCSTimeHeader::timedata_, and DCSCom::DCSServerInfo::vagrants.
Referenced by DCSServer::idle().
int8_t DCSCom::serverReadRequest (const SockClient * client)
Receive request from client.
Read a data request from a client. Prior to calling this function, the client socket must be accepted by a call to serverAccept.
Parameters:
client a SockClient object specifying the socket from which data request is being received.
Returns:
client request code if successful, -1 if failed.
See also:
Client Requests
serverAccept()
Referenced by serverNegotiate(), and serverProcessRequests().
bool DCSCom::serverSendDataParams (const DCSServerInfo & info, const SockClient * client)
Send information for UDP data transmission.
Sends the UDP type, address, and port number to be used for UDP data communications. This information is sent via TCP. The serverNegotiate function uses this function for transmitting data communication settings to the client.
Parameters:
info a DCSServerInfo structure containing the settings for UDP type, address, and port to be used for data transmission.
client a SockClient with which the data is to be sent.
Returns:
true if successful, false if failed. On failure, client connection is not closed by this function. The application should close the socket explicitly with a call to serverTerminateClient if this function fails.
See also:
serverNegotiate()
serverTerminateClient()
References DCSCom::DCSServerInfo::dataport, DCSCom::DCSServerInfo::datasock, DCSCom::DCSServerInfo::datatype, and DCSREQUEST_DATAMODE.
Referenced by serverNegotiate(), and serverProcessRequests().
bool DCSCom::serverSendHeaders (const SockClient * client, const DCSHeaderContainer & headers)
Send all known platform headers to a client.
Sends the headers stored in a DCSHeaderContainer to the client. This information is sent via TCP. The serverNegotiate function uses this function for transmitting the headers to the client.
Parameters:
client a SockClient with which the headers are to be sent.
headers a DCSHeaderContainer structure containing headers to be sent to the client.
Returns:
true if successful, false if failed. On failure, client connection is not closed by this function. The application should close the socket explicitly with a call to serverTerminateClient if this function fails.
See also:
serverNegotiate()
serverTerminateClient()
References DCSREQUEST_HEADERS, serverHCFunc(), DCSHeaderContainer::size(), and DCSHeaderContainer::traverse().
Referenced by serverNegotiate(), and serverProcessRequests().
bool DCSCom::serverSendScenario (const SockClient * client, const DCSScenarioHeader & scenario)
Send scenario header to a client.
Sends the DCSScenarioHeader to the client. This information is sent via TCP. The serverNegotiate function uses this function for transmitting the scenario header to the client.
Parameters:
client a SockClient with which the scenario header is to be sent.
scenario a DCSScenarioHeader structure to be sent to the client.
Returns:
true if successful, false if failed. On failure, client connection is not closed by this function. The application should close the socket explicitly with a call to serverTerminateClient if this function fails.
See also:
serverNegotiate()
serverTerminateClient()
References DCSScenarioHeader::dataSize(), DCSREQUEST_SCENARIO, and DCSScenarioHeader::pack().
Referenced by serverNegotiate(), and serverProcessRequests().
bool DCSCom::serverSendTime (const SockClient * client, const DCSTimeHeader & time)
Send time header to a client.
Sends the DCSTimeHeader to the client. This information is sent via TCP. The serverNegotiate function uses this function for transmitting the time header to the client.
Parameters:
client a SockClient with which the time header is to be sent.
time a DCSTimeHeader structure to be sent to the client.
Returns:
true if successful, false if failed. On failure, client connection is not closed by this function. The application should close the socket explicitly with a call to serverTerminateClient if this function fails.
See also:
serverNegotiate()
serverTerminateClient()
References DCSTimeHeader::dataSize(), DCSREQUEST_TIME, and DCSTimeHeader::pack().
Referenced by serverNegotiate(), and serverProcessRequests().
bool DCSCom::serverStart (DCSServerInfo & info, uint16_t servport, int8_t datamode, uint16_t dataport, const char * dataaddr, const char * iface = NULL, TTL_T ttl = 1)
Server creation/initialization.
Creates a listening server. Allocates some resources for fields of the DCSServerInfo structure.
Parameters:
info a DCSServerInfo structure to be filled with data specific too the server being started. Resources required by DCSServerInfo will be allocated by this function. A matching call to serverStop is required to properly free these resources, when finished.
servport an unsinged integer specifying the port that the server should listen on.
datamode a byte specifying the UDP mode: Broadcast, Multicast, or unicast. If this value is DCSDATA_UNICAST, dataaddr is ignored.
dataport an unsinged integer specifying the port that the server should transmit UDP data on.
dataaddr a string specifying the UDP address for transimitting data. If datamode is DCSDATA_UNICAST, this value is ignored.
iface an optional argument that may be used to specify the interface on which the server should listen and transmit data.
ttl a value specifying the TTL for the Multicast UDP mode. If datamode is not set to DCSDATA_MCAST, this value is ignored. The interface is specified as the numerical IP address of the network device to be used for transmitting data (eg. "127.0.0.1" for loopback or the ip address of an installed network card). This will cause the server to only receive and send on this device. Not specifying an interface allows the kernel to determine the proper interface to use.
Returns:
true if successful, false if failed. On failure, no resources will have been allocated, so a call to serverStop is unnecessary.
See also:
Data Modes
serverStop()
References DCSCom::DCSServerInfo::dataport, DCSCom::DCSServerInfo::datasock, DCSCom::DCSServerInfo::datatype, DCSDATA_BROADCAST, DCSDATA_MULTICAST, DCSDATA_UNCONNECTED, DCSDATA_UNICAST, DCSCom::DCSServerInfo::server_id, DCSCom::DCSServerInfo::serverVersion, and DCSCom::DCSServerInfo::servsock.
Referenced by DCSServer::start().
void DCSCom::serverStop (DCSServerInfo & info)
Server shutdown.
Shuts down server and frees resources allocated for DCSServerInfo by serverStart
Parameters:
info a DCSServerInfo structure containing data sepcific to the server to be stopped. Resources allocated for this structure by serverStart will be freed.
See also:
serverStart()
References DCSCom::DCSServerInfo::dataport, DCSCom::DCSServerInfo::datasock, DCSCom::DCSServerInfo::datatype, DCSDATA_UNCONNECTED, serverTerminateAllClients(), and DCSCom::DCSServerInfo::servsock.
Referenced by DCSServer::~DCSServer().
bool DCSCom::serverTerminateAllClients (DCSServerInfo & info)
Terminates all client connections.
Closes all client connections, removes the client sockets from the client list maintained by DCSServerInfo, and frees resources allocated for each SockClient by serverAccept. Should be used for closing all sockets. A socket should never be closed and deleted directly by user code.
Parameters:
info a DCSServerInfo structure containing the client list that the client sockets are to be removed from.
Returns:
true if successful, false if failed. Failure indicates that the socket pointer was NULL or was not present in the client socket list.
References DCSCom::DCSServerInfo::clientlist, DCSREQUEST_DISCONNECT, and DCSCom::DCSServerInfo::vagrants.
Referenced by serverStop().
bool DCSCom::serverTerminateClient (DCSServerInfo & info, SockClient * client)
Terminate a client connection.
Closes a client connection, removes the client socket from the client list maintained by DCSServerInfo, and frees resources allocated for the SockClient by serverAccept. Should be used for closing all sockets. A socket should never be closed and deleted directly by user code.
Parameters:
info a DCSServerInfo structure containing the client list that the client socket is to be removed from.
client a SockClient object specifying the client socket to be terminated.
Returns:
true if successful, false if failed. Failure indicates that the socket pointer was NULL or was not present in the client socket list.
References DCSCom::DCSServerInfo::clientlist, and DCSREQUEST_DISCONNECT.
Referenced by DCSServer::idle(), and serverExpelVagrants().
2002-2008 U.S. Naval Research Laboratory. The U.S. Government retains all rights to use, duplicate, distribute, disclose, or release this document.
For further information regarding DCS or SIMDIS please visit https://simdis.nrl.navy.mil or send e-mail to simdis@enews.nrl.navy.mil.
Copies of DCS and SIMDIS, as well as this manual and other related information, may be obtained from https://simdis.nrl.navy.mil.
Generated at Mon Mar 26 2012 08:06:29 for the DCS API by doxygen 1.7.6.1.