.TH "SockSupportException" 3 "Mon Mar 26 2012" "Version 1.0" "NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SockSupportException \- 
.PP
Socket support exception class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SockException\&.h>\fP
.PP
Inherits \fBSockException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSockSupportException\fP ()"
.br
.RI "\fIDefault socket support exception constructor\&. \fP"
.ti -1c
.RI "\fBSockSupportException\fP (const char *msg)"
.br
.RI "\fISocket support exception constructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Socket support exception class\&. 

A socket support exception class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSockSupportException::SockSupportException\fP ()\fC [inline]\fP"
.PP
Default socket support exception constructor\&. Creates a socket support exception object with a default message\&. 
.SS "\fBSockSupportException::SockSupportException\fP (const char *msg)\fC [inline]\fP"
.PP
Socket support exception constructor\&. Creates a socket support exception object with a user specified error message\&. 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP a character string containing an error message\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NET from the source code\&.
