.TH "SockValueException" 3 "Mon Mar 26 2012" "Version 1.0" "NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SockValueException \- 
.PP
Socket value exception class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SockException\&.h>\fP
.PP
Inherits \fBSockException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSockValueException\fP ()"
.br
.RI "\fIDefault socket value exception constructor\&. \fP"
.ti -1c
.RI "\fBSockValueException\fP (const char *msg)"
.br
.RI "\fISocket value exception constructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Socket value exception class\&. 

A socket value exception class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSockValueException::SockValueException\fP ()\fC [inline]\fP"
.PP
Default socket value exception constructor\&. Creates a socket value exception object with a default message\&. 
.SS "\fBSockValueException::SockValueException\fP (const char *msg)\fC [inline]\fP"
.PP
Socket value exception constructor\&. Creates a socket value exception object with a user specified error message\&. 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP a character string containing an error message\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NET from the source code\&.
