NET: SockAddrFactory Class Reference
SockAddrFactory Class Reference
Socket address creator.
#include <SockAddrFactory.h>
Static Public Member Functions
static SockAddrInet * create (int32_t family)
Detailed Description
Socket address creator.
A class to create a socket address object for a desired socket address family. Currently only AF_INET is supporter.
Member Function Documentation
SockAddrInet * SockAddrFactory::create (int32_t family) [static]
Creates a new SocketAddrInet object.
Parameters:
family an integer specifying the desired socket address family for the object to be created. Currently only AF_INET is supported.
Returns:
a newly created SocketAddrInet object.
See also:
SockAddrInet
Referenced by SockBroadcast::open(), SockBroadcast::SockBroadcast(), SockClient::SockClient(), SockInet::SockInet(), and SockUDP::SockUDP().
The documentation for this class was generated from the following files:
SockAddrFactory.h
SockAddrFactory.cpp