NET: SockClient Class Reference
SockClient Class Reference
TCP client socket class.
#include <SockClient.h>
Public Member Functions
SockClient ()
Default client socket constructor.
SockClient (uint16_t peerport, const char *peeraddr, uint16_t port=EPHEMERAL_PORT, const char *iface=NULL)
Client socket constructor.
SockClient (SockAddrInet *peeraddr, SockAddrInet *localaddr)
Client socket constructor.
SockClient (SOCKET sockfd)
Client socket constructor.
virtual ~SockClient ()
Destructor.
virtual bool isActive () const
Indicates an active socket.
virtual bool isConnected () const
Indicates a connected socket.
uint16_t getPort () const
Retrieve peer's port value.
const char * getAddress (char *peeraddr, int32_t len) const
Retrieve peer's network address value.
virtual bool open ()
Open socket connection.
virtual bool close ()
Close socket connection.
bool connect (uint16_t peerport, const char *peeraddr)
Connect to peer.
Protected Attributes
bool connected_
Connection indicator.
SockAddrInet * peeraddr_
Peer network address information.
Detailed Description
TCP client socket class.
A TCP client socket that utilizes the TCP network protocol for reliable two-way network communication.
Constructor & Destructor Documentation
SockClient::SockClient ()
Default client socket constructor.
Creates an unconnected client socket object with default data values.
References SockAddrFactory::create(), and peeraddr_.
SockClient::SockClient (uint16_t peerport, const char * peeraddr, uint16_t port = EPHEMERAL_PORT, const char * iface = NULL)
Client socket constructor.
Creates a connected client socket object with the specified data values.
Parameters:
peerport an unsigned 16-bit integer specifying the port of the TCP server socket with which to connect.
peeraddr a character string specifying the network address of the TCP server socket with which to connect.
port an unsigned 16-bit integer specifying the local port with which to bind the client socket.
iface a character string specifying the network interface to use for network transmission.
References SockInet::bind(), connect(), connected_, SockAddrInet::copy(), SockAddrFactory::create(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, peeraddr_, SockAddrInet::setAddress(), SockAddrInet::setPort(), and SockInet::sockfd_.
SockClient::SockClient (SockAddrInet * peeraddr, SockAddrInet * localaddr)
Client socket constructor.
Creates a connected client socket object with the specified data values.
Parameters:
peeraddr a SockAddrInet object specifying the network information for the peer (TCP server socket) to connect with when creating the client socket.
localaddr a SockAddrInet object specifying the network information to be used when creating the client socket.
References SockInet::bind(), connect(), connected_, SockAddrInet::copy(), SockAddrFactory::create(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, peeraddr_, and SockInet::sockfd_.
SockClient::SockClient (SOCKET sockfd)
Client socket constructor.
Creates a client socket object from the specified data value.
Parameters:
sockfd a handle to a previously created socket, to be used by the client socket object.
References connected_, SockAddrInet::copy(), SockAddrFactory::create(), and peeraddr_.
SockClient::~SockClient () [virtual]
Destructor.
Virtual destructor. Will close an open/connected client socket.
References close(), SockInet::isValid(), and peeraddr_.
Member Function Documentation
bool SockClient::close () [virtual]
Close socket connection.
See also:
SockInet::close
Reimplemented from SockInet.
References connected_, peeraddr_, SockAddrInet::setAddress(), and SockAddrInet::setPort().
Referenced by ~SockClient().
bool SockClient::connect (uint16_t peerport, const char * peeraddr)
Connect to peer.
Connects socket to the specified TCP server socket.
Parameters:
peerport an unsigned 16-bit integer specifying the port of the TCP server socket with which to connect.
peeraddr a character string specifying the network address of the TCP server socket with which to connect.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false. If the operation was performed with non-blocking I/O and the function returned before the connection was established, the return value will be false but the isConnected() and isActive() functions will return true, indicating that the connection is pending. The readReady() or writeReady() functions can be used to determine the completion of a pending non-blocking connect. When the non-blocking connection is completed, the getSockErr() function can be used to determine that the connection was successful. If the non-blocking connect failed, the close() function should be used to reset the socket state.
See also:
SockInet::readReady
SockInet::writeReady
SockInet::isBlockingIO
SockInet::setBlockingIO
SockInet::close
getSockErr
References SockInet::block_, connected_, SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, peeraddr_, SockAddrInet::setAddress(), SockAddrInet::setPort(), and SockInet::sockfd_.
Referenced by SockClient().
const char * SockClient::getAddress (char * peeraddr, int32_t len) const
Retrieve peer's network address value.
Returns value of the network address for the server socket that the client is connected to.
Parameters:
peeraddr a character array to be filled with the server socket's IPv4 network address.
len an integer specifying the size, in bytes, of 'addr'.
Returns:
a pointer to an array of characters containing the TCP server socket's IPv4 network address.
References SockAddrInet::getAddress(), and peeraddr_.
uint16_t SockClient::getPort () const
Retrieve peer's port value.
Returns value of the port for the server socket that the client is connected to.
Returns:
an unsigned 16-bit integer specifying the TCP server socket's port number.
References SockAddrInet::getPort(), and peeraddr_.
bool SockClient::isActive () const [virtual]
Indicates an active socket.
See also:
SockTCP::isActive
Implements SockTCP.
References connected_.
bool SockClient::isConnected () const [virtual]
Indicates a connected socket.
Returns:
a boolean value indicating that the socket is connected if true, and is not connected if false.
References connected_.
bool SockClient::open () [virtual]
Open socket connection.
See also:
SockInet::open
Implements SockTCP.
Member Data Documentation
bool SockClient::connected_ [protected]
Connection indicator.
Indicates that the client socket is connected to a peer.
Referenced by close(), connect(), isActive(), isConnected(), and SockClient().
SockAddrInet* SockClient::peeraddr_ [protected]
Peer network address information.
Socket address object containig the information of the socket's peer.
Referenced by close(), connect(), getAddress(), getPort(), SockClient(), and ~SockClient().
The documentation for this class was generated from the following files:
SockClient.h
SockClient.cpp