NET: SockMonitor Class Reference
SockMonitor Class Reference
Socket pending read, write, and error event monitoring class.
#include <SockMonitor.h>
Public Member Functions
SockMonitor ()
Default socket monitor constructor.
virtual ~SockMonitor ()
Destructor.
bool addReadMonitor (SockInet *sock)
bool addWriteMonitor (SockInet *sock)
bool addErrorMonitor (SockInet *sock)
bool removeReadMonitor (SockInet *sock)
bool removeWriteMonitor (SockInet *sock)
bool removeErrorMonitor (SockInet *sock)
void getReadSockets (SocketList &socks) const
void getWriteSockets (SocketList &socks) const
void getErrorSockets (SocketList &socks) const
int32_t watchRead (SocketList &readsocks, uint32_t sec=0, uint32_t usec=0)
int32_t watchWrite (SocketList &writesocks, uint32_t sec=0, uint32_t usec=0)
int32_t watchError (SocketList &errorsocks, uint32_t sec=0, uint32_t usec=0)
int32_t watchAll (SocketList &readsocks, SocketList &writesocks, SocketList &errorsocks, uint32_t sec=0, uint32_t usec=0)
Protected Types
typedef std::map< SOCKET,
SockInet * > SocketMap
Maps a SOCKET structure to a SockInet for internal usage.
Protected Attributes
SocketMap readsocks_
Sockets to observe for read ready on select()
SocketMap writesocks_
Sockets to observe for write ready on select()
SocketMap errorsocks_
Sockets to observe for errors on select()
Detailed Description
Socket pending read, write, and error event monitoring class.
A class for monitoring multiple sockets for pending read, write, and error events. This serves as a cross-platform method for select() calls on multiple sockets.
Constructor & Destructor Documentation
SockMonitor::SockMonitor ()
Default socket monitor constructor.
Creates an empty socket monitor object.
SockMonitor::~SockMonitor () [virtual]
Destructor.
Virtual destructor.
Member Function Documentation
bool SockMonitor::addErrorMonitor (SockInet * sock)
Add a socket to the list of sockets to monitor for errors
References errorsocks_, and SockInet::getDescriptor().
bool SockMonitor::addReadMonitor (SockInet * sock)
Adds a socket to the list of sockets to watch for read ready
References SockInet::getDescriptor(), and readsocks_.
bool SockMonitor::addWriteMonitor (SockInet * sock)
Adds a socket to the list of sockets to watch for write ready
References SockInet::getDescriptor(), and writesocks_.
void SockMonitor::getErrorSockets (SocketList & socks) const
Retrieves sockets in the error monitoring list
References errorsocks_.
void SockMonitor::getReadSockets (SocketList & socks) const
Retrieves sockets in the read list
References readsocks_.
void SockMonitor::getWriteSockets (SocketList & socks) const
Retrieves sockets in the write list
References writesocks_.
bool SockMonitor::removeErrorMonitor (SockInet * sock)
Removes a socket from the error observation list
References errorsocks_, and SockInet::getDescriptor().
bool SockMonitor::removeReadMonitor (SockInet * sock)
Removes a socket from the read list
References SockInet::getDescriptor(), and readsocks_.
bool SockMonitor::removeWriteMonitor (SockInet * sock)
Removes a socket from the write list
References SockInet::getDescriptor(), and writesocks_.
int32_t SockMonitor::watchAll (SocketList & readsocks, SocketList & writesocks, SocketList & errorsocks, uint32_t sec = 0, uint32_t usec = 0)
Watches read, write, and error sockets for appropriate conditions. Selected sockets get returned in appropriate list.
Parameters:
readsocks User supplied list of sockets, that gets filled with sockets ready to read from
writesocks User supplied list of sockets, that gets filled with sockets ready to write to
errorsocks User supplied list of sockets, that gets filled with sockets with pending error conditions
sec Number of seconds to wait
usec Number of microseconds to wait
Returns:
Result of select() -- total number of bits set in the bit mask, or -1 for errors with errno set
References errorsocks_, readsocks_, and writesocks_.
int32_t SockMonitor::watchError (SocketList & errorsocks, uint32_t sec = 0, uint32_t usec = 0)
Watches for error conditions pending on error sockets for up to sec.usec time. Error-ready sockets get returned in errorsocks.
Parameters:
errorsocks User supplied list of sockets, that gets filled with sockets with pending error conditions
sec Number of seconds to wait
usec Number of microseconds to wait
Returns:
Result of select() -- total number of bits set in the bit mask, or -1 for errors with errno set
References errorsocks_.
int32_t SockMonitor::watchRead (SocketList & readsocks, uint32_t sec = 0, uint32_t usec = 0)
Watches for a read on all read sockets for up to sec.usec time. Ready sockets get returned in readsocks.
Parameters:
readsocks User supplied list of sockets, that gets filled with sockets ready to read from
sec Number of seconds to wait for readReady
usec Number of microseconds to wait for readReady
Returns:
Result of select() -- total number of bits set in the bit mask, or -1 for errors with errno set
References readsocks_.
int32_t SockMonitor::watchWrite (SocketList & writesocks, uint32_t sec = 0, uint32_t usec = 0)
Watches for a write ready on all read sockets for up to sec.usec time. Ready sockets get returned in writesocks.
Parameters:
writesocks User supplied list of sockets, that gets filled with sockets ready to write to
sec Number of seconds to wait for writeReady
usec Number of microseconds to wait for writeReady
Returns:
Result of select() -- total number of bits set in the bit mask, or -1 for errors with errno set
References writesocks_.
The documentation for this class was generated from the following files:
SockMonitor.h
SockMonitor.cpp