NET: SockAddrInet Class Reference
SockAddrInet Class Reference
Socket address class.
#include <SockAddrInet.h>
Public Member Functions
SockAddrInet (uint16_t port, const char *addr)
Socket address constructor.
void copy (const SockAddrInet *source)
Copy socket address object.
void copy (const SOCKADDR *source, socklen_t len)
Copy socket address object.
uint16_t getPort () const
Retrieve port value.
void setPort (uint16_t port)
Set port value.
char * getAddress (char *addr, int32_t len) const
Retrieve address value.
void setAddress (const char *addr)
Set address value.
int32_t getFamily () const
Retrieve the socket address family.
const SOCKADDR * getSockAddr () const
Retrieve the socket address structure.
int32_t getSockAddrLen () const
Retrieve the socket address structure size.
Protected Member Functions
SockAddrInet ()
Default socket address constructor.
Protected Attributes
uint16_t port_
Port number.
char addr_ [INET_ADDRSTRLEN]
Network address.
SOCKADDR_IN sa_
Socket address structure.
Friends
class SockAddrFactory
Detailed Description
Socket address class.
An internet socket address class containing a network address and a TCP/UDP port number.
Constructor & Destructor Documentation
SockAddrInet::SockAddrInet () [protected]
Default socket address constructor.
Creates an event object with default data values. Can not be accessed directly, but is used by SockAddrFactory.
See also:
SockAddrFactory::create
References addr_, and sa_.
SockAddrInet::SockAddrInet (uint16_t port, const char * addr)
Socket address constructor.
Creates a socket address object with the specified values.
Parameters:
port an unsigned 16-bit integer specifying a TCP or UDP port number.
addr a character string specifying an IPv4 network address.
References addr_, sa_, setAddress(), and setPort().
Member Function Documentation
void SockAddrInet::copy (const SockAddrInet * source)
Copy socket address object.
Copies the contents of a socket address object into this socket address object.
Parameters:
source a socket address object whose contents are to be copied.
References addr_, getFamily(), port_, and sa_.
Referenced by SockInet::bind(), SockClient::connect(), SockUDP::connect(), SockBroadcast::SockBroadcast(), SockClient::SockClient(), SockInet::SockInet(), SockMulticast::SockMulticast(), SockServer::SockServer(), SockUDP::SockUDP(), and SockUnicast::SockUnicast().
void SockAddrInet::copy (const SOCKADDR * source, socklen_t len)
Copy socket address object.
Copies the contents of a socket address object into this socket address object.
Parameters:
source a standard socket address structure whose contents are to be copied.
len an integer specifying the size of 'source' in bytes.
References addr_, port_, and sa_.
char * SockAddrInet::getAddress (char * addr, int32_t len) const
Retrieve address value.
Returns value of network address.
Parameters:
addr a character array to be filled with the IPv4 network address.
len an integer specifying the size, in bytes, of 'addr'.
Returns:
a pointer to an array of characters containing the IPv4 network address.
See also:
addr_
References addr_.
Referenced by SockClient::getAddress(), SockUDP::getAddress(), and SockInet::getIface().
int32_t SockAddrInet::getFamily () const
Retrieve the socket address family.
Returns the socket address family type.
Returns:
an integer specifying the socket address family. Currently only AF_INET is supported.
Referenced by copy().
uint16_t SockAddrInet::getPort () const
Retrieve port value.
Returns value of port.
Returns:
an unsigned 16-bit integer specifying a TCP or UDP port number.
See also:
port_
References port_.
Referenced by SockInet::getLocalPort(), SockClient::getPort(), and SockUDP::getPort().
const SOCKADDR * SockAddrInet::getSockAddr () const
Retrieve the socket address structure.
Returns the socket address structure.
Returns:
the SOCKADDR structure containing socket address information.
See also:
sa_
References sa_.
Referenced by SockInet::bind(), SockClient::connect(), SockUDP::connect(), SockBroadcast::SockBroadcast(), SockClient::SockClient(), SockMulticast::SockMulticast(), SockServer::SockServer(), SockUnicast::SockUnicast(), and SockUDP::write().
int32_t SockAddrInet::getSockAddrLen () const
Retrieve the socket address structure size.
Returns the size of the socket address structure.
Returns:
an integer specifying the size of the socket address structure.
See also:
sa_
Referenced by SockInet::bind(), SockClient::connect(), SockUDP::connect(), SockBroadcast::SockBroadcast(), SockClient::SockClient(), SockMulticast::SockMulticast(), SockServer::SockServer(), SockUnicast::SockUnicast(), and SockUDP::write().
void SockAddrInet::setAddress (const char * addr)
Set address value.
Sets value of network address.
Parameters:
addr a character string specifying the IPv4 network address with which the network address value is to be set.
See also:
addr_
References addr_, and sa_.
Referenced by SockUDP::attach(), SockInet::bind(), SockClient::close(), SockUDP::close(), SockClient::connect(), SockUDP::connect(), SockUDP::detatch(), SockUDP::disconnect(), SockAddrInet(), SockClient::SockClient(), SockInet::SockInet(), SockMulticast::SockMulticast(), and SockUDP::SockUDP().
void SockAddrInet::setPort (uint16_t port)
Set port value.
Sets value of port.
Parameters:
port an unsigned 16-bit integer specifying the TCP or UDP port number with which the port value is to be set.
See also:
port_
References port_, and sa_.
Referenced by SockUDP::attach(), SockInet::bind(), SockClient::close(), SockUDP::close(), SockClient::connect(), SockUDP::connect(), SockUDP::detatch(), SockUDP::disconnect(), SockAddrInet(), SockClient::SockClient(), SockInet::SockInet(), and SockUDP::SockUDP().
Member Data Documentation
char SockAddrInet::addr_[INET_ADDRSTRLEN] [protected]
Network address.
IPv4 network address, represented as a string (eg 132.250.132.147).
Referenced by copy(), getAddress(), setAddress(), and SockAddrInet().
uint16_t SockAddrInet::port_ [protected]
Port number.
A 16-bit TCP od UDP port number.
Referenced by copy(), getPort(), and setPort().
SOCKADDR_IN SockAddrInet::sa_ [protected]
Socket address structure.
IPv4 socket address structure used by BSD socket routines.
Referenced by copy(), getSockAddr(), setAddress(), setPort(), and SockAddrInet().
The documentation for this class was generated from the following files:
SockAddrInet.h
SockAddrInet.cpp