NET: SockUDP Class Reference
SockUDP Class Reference
UDP socket class.
#include <SockUDP.h>
Public Member Functions
SockUDP ()
Default UDP socket constructor.
SockUDP (uint16_t port, const char *iface=NULL)
UDP socket constructor.
SockUDP (uint16_t peerport, const char *peeraddr, uint16_t port, const char *iface=NULL, bool attach=true)
UDP socket constructor.
SockUDP (const SockAddrInet *localaddr)
UDP socket constructor.
SockUDP (const SockAddrInet *peeraddr, const SockAddrInet *localaddr, bool attach=true)
UDP socket constructor.
SockUDP (SOCKET sockfd)
UDP socket constructor.
virtual ~SockUDP ()
Destructor.
bool isConnected () const
Indicates a connected socket.
bool isAttached () const
Indicates an attached socket.
uint16_t getPort () const
Retrieve attached/connected port value.
char * getAddress (char *peeraddr, int32_t len) const
Retrieve attached/connected network address value.
virtual int32_t read (void *buffer, int32_t size, int32_t flags=0) const
Read data.
virtual int32_t write (const void *buffer, int32_t size, int32_t flags=0) const
Write data.
virtual int32_t readFrom (void *buffer, int32_t size, int32_t flags=0, SOCKADDR *from=NULL, socklen_t *addrlen=NULL) const
Read data.
virtual int32_t writeTo (const void *buffer, int32_t size, int32_t flags=0, const SOCKADDR *to=NULL, socklen_t addrlen=0) const
Write to specified destination.
virtual bool open ()=0
Open connected socket.
virtual bool close ()
Close connected socket.
bool connect (uint16_t peerport, const char *peeraddr)
Connect socket.
bool attach (uint16_t peerport, const char *peeraddr)
Attach socket.
bool disconnect ()
Disconnect socket.
bool detatch ()
Detach socket.
Protected Attributes
bool attached_
Socket is attached.
bool connected_
Socket is connected.
SockAddrInet * peeraddr_
Peer network address information.
Detailed Description
UDP socket class.
An abstract class specifying a UDP internet socket.
Constructor & Destructor Documentation
SockUDP::SockUDP ()
Default UDP socket constructor.
Creates a UDP socket object with default data values.
References SockAddrFactory::create(), and peeraddr_.
SockUDP::SockUDP (uint16_t port, const char * iface = NULL)
UDP socket constructor.
Creates a UDP socket object with the specified data values.
Parameters:
port an unsigned 16-bit integer specifying the port to bind the socket to.
iface a character string specifying the network interface to use for network transmission.
References SockAddrFactory::create(), and peeraddr_.
SockUDP::SockUDP (uint16_t peerport, const char * peeraddr, uint16_t port, const char * iface = NULL, bool attach = true)
UDP socket constructor.
Creates a UDP socket object with the specified data values, and connects it to a specified peer. When a UDP socket object is connected to a peer, data can be sent to that peer with calls to 'write' rather than calls to 'writeTo'. When a UDP socket is connected it can only communicate with the peer.
Parameters:
peerport a 16-bit integer specifying the port of the peer to which the socket is to be connected/attached.
peeraddr a character string specifying the network address of the peer to which the socket is to be connected/attached.
port an unsigned 16-bit integer specifying the port to which the socket is to bind.
iface a character string specifying the network interface to use for network transmission.
attach a boolean value specifying whether the socket is to be attached to the peer or connected to the peer. When the socket is attached, the socket object stores the peerport and peeraddr values and uses them to call 'sendto'. If the socket is connected, the socket object links the socket to the peer on the kernel level with a call to the 'connect' function and sends data with 'send'.
See also:
SockUDP::attached_
SockUDP::write
SockUDP::writeTo
References SockAddrFactory::create(), peeraddr_, SockAddrInet::setAddress(), and SockAddrInet::setPort().
SockUDP::SockUDP (const SockAddrInet * localaddr)
UDP socket constructor.
Creates a UDP socket object with the specified data values.
Parameters:
localaddr a SockAddrInet object specifying the network information to be used when creating the socket.
See also:
SockAddrInet
References SockAddrFactory::create(), and peeraddr_.
SockUDP::SockUDP (const SockAddrInet * peeraddr, const SockAddrInet * localaddr, bool attach = true)
UDP socket constructor.
Creates a UDP socket object with the specified data values, and connects it to a specified peer. When a UDP socket object is connected to a peer, data can be sent to that peer with calls to 'write' rather than calls to 'writeTo'. When a UDP socket is connected it can only communicate with the peer.
Parameters:
peeraddr a SockAddrInet object specifying the network information for the peer to connect with when creating the socket.
localaddr a SockAddrInet object specifying the network information to be used when creating the socket.
attach a boolean value specifying whether the socket is to be attached to the peer or connected to the peer. When the socket is attached, the socket object stores the peerport and peeraddr values and uses them to call 'sendto'. If the socket is connected, the socket object links the socket to the peer on the kernel level with a call to the 'connect' function and sends data with 'send'.
See also:
SockUDP::attached_
SockUDP::write
SockUDP::writeTo
References SockAddrInet::copy(), SockAddrFactory::create(), and peeraddr_.
SockUDP::SockUDP (SOCKET sockfd)
UDP socket constructor.
Creates a socket object from the specified data value.
Parameters:
sockfd a handle to a previously created socket, to be used by the socket object.
References connected_, SockAddrInet::copy(), SockAddrFactory::create(), and peeraddr_.
SockUDP::~SockUDP () [virtual]
Destructor.
Virtual destructor. Will close an open/connected socket.
References close(), SockInet::isValid(), and peeraddr_.
Member Function Documentation
bool SockUDP::attach (uint16_t peerport, const char * peeraddr)
Attach socket.
Attach the socket to a specified port and address.
Parameters:
peerport an unsigned 16-bit integer specifying the port with which to attach.
peeraddr a character string specifying the UDP network address with which to attach.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References attached_, peeraddr_, SockAddrInet::setAddress(), and SockAddrInet::setPort().
bool SockUDP::close () [virtual]
Close connected socket.
See also:
SockInet::close
Reimplemented from SockInet.
References attached_, connected_, peeraddr_, SockAddrInet::setAddress(), and SockAddrInet::setPort().
Referenced by ~SockUDP().
bool SockUDP::connect (uint16_t peerport, const char * peeraddr)
Connect socket.
Connect the socket to a specified port and address.
Parameters:
peerport an unsigned 16-bit integer specifying the port with which to connect.
peeraddr a character string specifying the UDP network address with which to connect.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References connected_, SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, peeraddr_, SockAddrInet::setAddress(), SockAddrInet::setPort(), and SockInet::sockfd_.
Referenced by disconnect(), SockBroadcast::SockBroadcast(), and SockUnicast::SockUnicast().
bool SockUDP::detatch ()
Detach socket.
Detach an attached socket.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References attached_, peeraddr_, SockAddrInet::setAddress(), and SockAddrInet::setPort().
bool SockUDP::disconnect ()
Disconnect socket.
Disconnect a connected socket.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References connect(), connected_, peeraddr_, SockAddrInet::setAddress(), SockAddrInet::setPort(), and SockInet::sockfd_.
char * SockUDP::getAddress (char * peeraddr, int32_t len) const
Retrieve attached/connected network address value.
Returns value of the network address that the socket is attached or connected to.
Parameters:
peeraddr a character array to be filled with the IPv4 network address.
len an integer specifying the size, in bytes, of 'addr'.
Returns:
a pointer to an array of characters containing the TCP server socket's IPv4 network address.
References SockAddrInet::getAddress(), and peeraddr_.
uint16_t SockUDP::getPort () const
Retrieve attached/connected port value.
Returns value of the port that the socket is attached or connected to.
Returns:
an unsigned 16-bit integer specifying the UDP port number.
References SockAddrInet::getPort(), and peeraddr_.
bool SockUDP::isAttached () const
Indicates an attached socket.
Returns:
a boolean value indicating that the socket is attached if true, and is not attached if false.
References attached_.
bool SockUDP::isConnected () const
Indicates a connected socket.
Returns:
a boolean value indicating that the socket is connected if true, and is not connected if false.
References connected_.
virtual bool SockUDP::open () [pure virtual]
Open connected socket.
See also:
SockInet::open
Implements SockInet.
Implemented in SockBroadcast, SockUnicast, and SockMulticast.
int32_t SockUDP::read (void * buffer, int32_t size, int32_t flags = 0) const [virtual]
Read data.
Reads data that is available in the socket input buffer.
Parameters:
buffer a pointer to an object to be filled with the data in the socket buffer.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when reading. These are the flags used by the BSD socket function 'recv'. See the 'recv' man pages or MSDN documentation for more details.
Returns:
the total number of bytes read.
Reimplemented from SockInet.
References attached_, and readFrom().
int32_t SockUDP::readFrom (void * buffer, int32_t size, int32_t flags = 0, SOCKADDR * from = NULL, socklen_t * addrlen = NULL) const [virtual]
Read data.
Reads data that is available in the socket input buffer, and reports the address and port of the sender.
Parameters:
buffer a pointer to an object to be filled with the data in the socket buffer.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when reading. These are the flags used by the BSD socket function 'recvfrom'. See the 'recvfrom' man pages or MSDN documentation for more details.
from a socket address structure specifying the address and port of the peer that sent the data.
addrlen an integer specifying the size of 'to' in bytes.
Returns:
the total number of bytes read.
References SockInet::sockfd_.
Referenced by read().
int32_t SockUDP::write (const void * buffer, int32_t size, int32_t flags = 0) const [virtual]
Write data.
Writes data to the network.
Parameters:
buffer a pointer to an object filled with the data to be written.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when writing. These are the flags used by the BSD socket function 'send'. See the 'send' man pages or MSDN documentation for more details.
Returns:
the total number of bytes written.
Reimplemented from SockInet.
References attached_, SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), peeraddr_, and writeTo().
int32_t SockUDP::writeTo (const void * buffer, int32_t size, int32_t flags = 0, const SOCKADDR * to = NULL, socklen_t addrlen = 0) const [virtual]
Write to specified destination.
Writes data to the specified network address.
Parameters:
buffer a pointer to an object filled with the data to be written.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when writing. These are the flags used by the BSD socket function 'sendto'. See the 'sendto' man pages or MSDN documentation for more details.
to a socket address structure specifying the destination address and port of the data to be written.
addrlen an integer specifying the size of 'to' in bytes.
Returns:
the total number of bytes written.
References SockInet::sockfd_.
Referenced by write().
Member Data Documentation
bool SockUDP::attached_ [protected]
Socket is attached.
Attaching a socket to another address simply means that you no longer have to call 'readFrom' because all reads will use the address from the attach specified address. After attaching, 'write' will call 'writeTo' with the specified info. This does not actually connect the socket, it merely stores the peer info at the application level.
Referenced by attach(), close(), detatch(), isAttached(), read(), SockBroadcast::SockBroadcast(), SockUnicast::SockUnicast(), and write().
bool SockUDP::connected_ [protected]
Socket is connected.
Connectiong a socket to a specific address will produce the same behavior as attaching a socket, but will differ internally. Connecting a socket will actually connect the socket to the specified address on the kernel level. This can improve performance of UDP write operations a great deal, but means that the connected socket can only communicate with the address to which it is connected.
Referenced by close(), connect(), disconnect(), isConnected(), SockBroadcast::SockBroadcast(), SockUDP(), and SockUnicast::SockUnicast().
SockAddrInet* SockUDP::peeraddr_ [protected]
Peer network address information.
Remote port and address for a connected UDP socket When sending UDP data to a single host it will be more efficient to "connect" to that host. You are not "connecting" as you would with TCP, rather, the kernel is storing the info for the peer. This way the kernel does not have to copy the peer's info and issue a temporary connect/disconnect for every datagram sent. Connected UDP sockets can only send AND receive data to/from the connected peer. Also with a connected UDP socket, the application will receive Asyncronous errors such as EHOSTUNREACH that would otherwise not be delivered to an unconnected UDP socket.
Referenced by attach(), close(), connect(), detatch(), disconnect(), getAddress(), getPort(), SockBroadcast::SockBroadcast(), SockUDP(), SockUnicast::SockUnicast(), write(), and ~SockUDP().
The documentation for this class was generated from the following files:
SockUDP.h
SockUDP.cpp