NET: SockServer Class Reference
SockServer Class Reference
TCP server socket class.
#include <SockServer.h>
Public Member Functions
SockServer ()
Default server socket constructor.
SockServer (uint16_t port, const char *iface=NULL, int32_t backlog=32)
Server socket constructor.
SockServer (const SockAddrInet *localaddr, int32_t backlog=32)
Server socket constructor.
SockServer (SOCKET sockfd)
Server socket constructor.
bool isActive () const
Indicates an active socket.
bool isListening () const
Indicates a listening socket.
int32_t getBacklog () const
Retrieve server's backlog value.
virtual bool open ()
Start server socket.
virtual bool close ()
Close server socket.
bool listen (int32_t backlog=32)
Listen for connections.
SOCKET accept ()
Accept client connection.
Protected Attributes
bool listening_
Listening for connections.
int32_t backlog_
Connection backlog.
Detailed Description
TCP server socket class.
A TCP server socket that utilizes the TCP network protocol for reliable two-way network communication.
Constructor & Destructor Documentation
SockServer::SockServer ()
Default server socket constructor.
Creates an inactive server socket object with default data values.
SockServer::SockServer (uint16_t port, const char * iface = NULL, int32_t backlog = 32)
Server socket constructor.
Creates an actively listening server socket object with the specified data values.
Parameters:
port an unsigned 16-bit integer specifying the local port with which to bind the server socket. This is the port on which client connections shall be accepted.
iface a character string specifying the network interface to use for network communication.
backlog an integer specifying the server backlog.
See also:
backlog_
References backlog_, SockInet::bind(), SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), listen(), listening_, SockInet::localaddr_, and SockInet::sockfd_.
SockServer::SockServer (const SockAddrInet * localaddr, int32_t backlog = 32)
Server socket constructor.
Creates an actively listening server socket object with the specified data values.
Parameters:
localaddr a SockAddrInet object specifying the network information to be used when creating the server socket.
backlog an integer specifying the server backlog.
See also:
backlog_
References backlog_, SockInet::bind(), SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), listen(), listening_, SockInet::localaddr_, and SockInet::sockfd_.
SockServer::SockServer (SOCKET sockfd)
Server socket constructor.
Creates a server socket object from the specified data value.
Parameters:
sockfd a handle to a previously created socket, to be used by the server socket object.
Member Function Documentation
SOCKET SockServer::accept ()
Accept client connection.
Accepts a connection from a client socket.
Returns:
a handle to the connected clietn socket.
References SockInet::sockfd_.
bool SockServer::close () [virtual]
Close server socket.
See also:
SockInet::close
Reimplemented from SockInet.
References listening_.
int32_t SockServer::getBacklog () const
Retrieve server's backlog value.
Returns the server's curretn backlog value.
Returns:
an integer specifying the server socket's backlog.
References backlog_.
bool SockServer::isActive () const [virtual]
Indicates an active socket.
See also:
SockTCP::isActive
Implements SockTCP.
References listening_.
bool SockServer::isListening () const
Indicates a listening socket.
Indicates that the server socket object is listening for connections.
Returns:
a boolean value indicating that the socket is listening if true, not listening if false.
References listening_.
bool SockServer::listen (int32_t backlog = 32)
Listen for connections.
Starts server socket object listening for client connections.
Parameters:
backlog an integer specifying the server socket object's backlog.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References backlog_, listening_, and SockInet::sockfd_.
Referenced by SockServer().
bool SockServer::open () [virtual]
Start server socket.
See also:
SockInet::open
Implements SockTCP.
Member Data Documentation
int32_t SockServer::backlog_ [protected]
Connection backlog.
The connection backlog specifying the number of unaccepted connections may be present at a time.
Referenced by getBacklog(), listen(), and SockServer().
bool SockServer::listening_ [protected]
Listening for connections.
Indicates that the server socket is listening for client socket connections.
Referenced by close(), isActive(), isListening(), listen(), and SockServer().
The documentation for this class was generated from the following files:
SockServer.h
SockServer.cpp