NET: SockCOM Class Reference
SockCOM Class Reference
#include <SockCOM.h>
Public Member Functions
SockCOM (const std::string &comPort, unsigned int baudRate=SOCKCOM_BR9600, unsigned int dataBits=SOCKCOM_BITS8, unsigned int parity=SOCKCOM_PARITYNONE, unsigned int stopBits=SOCKCOM_STOPBITS1, unsigned int flowControl=SOCKCOM_FCNONE)
Create a new SockCOM object bound to the specified device.
SockCOM (unsigned int comPort=1, unsigned int baudRate=SOCKCOM_BR9600, unsigned int dataBits=SOCKCOM_BITS8, unsigned int parity=SOCKCOM_PARITYNONE, unsigned int stopBits=SOCKCOM_STOPBITS1, unsigned int flowControl=SOCKCOM_FCNONE)
Create a new SockCOM object bound to the specific port.
virtual ~SockCOM ()
Virtual destructor.
SockCOMIOHandle getDescriptor () const
Retrieve handle to serial device.
std::string getCOMPort () const
Retrieve name of serial device.
unsigned int getBaudRate () const
Retrieve baud rate setting for the serial device.
unsigned int getDataBits () const
Retrieve number of data bits setting for the serial device.
unsigned int getParity () const
Retrieve parity setting for the serial device.
unsigned int getStopBits () const
Retrieve number of stop bits setting for the serial device.
unsigned int getFlowControl () const
Retrieve flow control setting for the serial device.
virtual bool isValid () const
Indicates the handle references a valid (open) serial device.
bool isBlockingIO () const
Indicates blocking I/O mode.
bool setBlockingIO (bool block)
Set blocking I/O mode.
int32_t getLastError () const
Get system error code.
void setLastError (int32_t error)
Set the system error code.
virtual bool open ()
Open serial device.
virtual bool close ()
Close serial device.
virtual bool readReady (uint32_t sec=0, uint32_t usec=0) const
Indicates data is available for reading.
virtual bool writeReady (uint32_t sec=0, uint32_t usec=0) const
Indicates space is available for writing.
virtual int32_t read (void *buffer, int32_t size, int32_t flags=0) const
Read data.
virtual int32_t write (const void *buffer, int32_t size, int32_t flags=0) const
Write data.
Protected Attributes
std::string comPort_
Current COM port.
unsigned int baudRate_
Baud rate.
unsigned int dataBits_
Data bits.
unsigned int parity_
Parity.
unsigned int stopBits_
Stop bits.
unsigned int flowControl_
Flow control.
SockCOMIOHandle ioHandle_
Handle to the current port.
int currentState_
Current state of the object.
int lastError_
Last error reported.
Detailed Description
Cross-platform library for reading and writing to COM ports. Can read and write to COM 1-n.
Constructor & Destructor Documentation
SockCOM::SockCOM (const std::string & comPort, unsigned int baudRate = SOCKCOM_BR9600, unsigned int dataBits = SOCKCOM_BITS8, unsigned int parity = SOCKCOM_PARITYNONE, unsigned int stopBits = SOCKCOM_STOPBITS1, unsigned int flowControl = SOCKCOM_FCNONE)
Create a new SockCOM object bound to the specified device.
Create a new SockCOM object bound to the specified device. Intended for use with RS-232 devices with names that do not match the common pattern for an operating system, such as USB to serial adapter cables which are assigned names such as '/dev/ttyUSB0' on Linux systems
References open().
SockCOM::SockCOM (unsigned int comPort = 1, unsigned int baudRate = SOCKCOM_BR9600, unsigned int dataBits = SOCKCOM_BITS8, unsigned int parity = SOCKCOM_PARITYNONE, unsigned int stopBits = SOCKCOM_STOPBITS1, unsigned int flowControl = SOCKCOM_FCNONE)
Create a new SockCOM object bound to the specific port.
Create a new SockCOM object bound to the specific port. The device name is determind by appending the specified port number to the following strings: 'COM' + comPort for the Microsoft Windows operating system '/dev/ttyS' + comPort for Linux systems '/dev/term/' + (comPort + 'a') for SunOS systems '/dev/ttyf' + comPort for other UNIX systems
References comPort_, and open().
Member Function Documentation
bool SockCOM::close () [virtual]
Close serial device.
Close an open serial device.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
Implements SockIO.
References currentState_, ioHandle_, and isValid().
Referenced by open(), and ~SockCOM().
unsigned int SockCOM::getBaudRate () const
Retrieve baud rate setting for the serial device.
Returns the baud rate associated with the serial device.
Returns:
an unsigned integer specifying the baud rate selected for the serial device.
References baudRate_.
std::string SockCOM::getCOMPort () const
Retrieve name of serial device.
Returns the name of the associated serial device.
Returns:
a string containing an operating system specific name of the associated serial device.
References comPort_.
unsigned int SockCOM::getDataBits () const
Retrieve number of data bits setting for the serial device.
Returns the number of data bits per byte associated with the serial device.
Returns:
an unsigned integer specifying the number of data bits per byte specified for the serial device.
References dataBits_.
SockCOMIOHandle SockCOM::getDescriptor () const
Retrieve handle to serial device.
Returns the file handle for the serial device.
Returns:
an operating system specific handle to the file descriptor associated with the serial device, or 0 if the device is closed.
References ioHandle_.
unsigned int SockCOM::getFlowControl () const
Retrieve flow control setting for the serial device.
Returns the clow control setting associated with the serial device.
Returns:
an unsigned integer specifying the flow control setting selected for the serial device.
References flowControl_.
int32_t SockCOM::getLastError () const
Get system error code.
Returns the last known system error value. This function is not specific to any one serial device. The error value retrieved can be for any socket that is part of the overall application.
Returns:
an error code indicating the reason for serial device failure.
References lastError_.
Referenced by open().
unsigned int SockCOM::getParity () const
Retrieve parity setting for the serial device.
Returns the parity setting associated with the serial device.
Returns:
an unsigned integer specifying the parity setting selected for the serial device.
References parity_.
unsigned int SockCOM::getStopBits () const
Retrieve number of stop bits setting for the serial device.
Returns the number of stop bits associated with the serial device.
Returns:
an unsigned integer specifying the number of stop bits specified for the serial device.
References stopBits_.
bool SockCOM::isBlockingIO () const [virtual]
Indicates blocking I/O mode.
Indicates that the serial device is or is not using blocking I/O.
Returns:
a boolean value indicating that the serial device is using blocking I/O if true, is not using blocking I/O if false.
Implements SockIO.
References ioHandle_.
bool SockCOM::isValid () const [virtual]
Indicates the handle references a valid (open) serial device.
Indicates that the serial object's handle is valid (open).
Returns:
a boolean value indicating the serial device handle is valid if true, and invalid if false.
Reimplemented from SockIO.
References ioHandle_.
Referenced by close(), read(), readReady(), write(), writeReady(), and ~SockCOM().
bool SockCOM::open () [virtual]
Open serial device.
Opens the serial device for communication.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
Implements SockIO.
References baudRate_, close(), comPort_, currentState_, dataBits_, flowControl_, getLastError(), ioHandle_, parity_, setLastError(), and stopBits_.
Referenced by SockCOM().
int32_t SockCOM::read (void * buffer, int32_t size, int32_t flags = 0) const [virtual]
Read data.
Reads data that is available in the serial device's input buffer.
Parameters:
buffer a pointer to an object to be filled with the data in the socket buffer.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to network sockets when reading. Unused by serial devices.
Returns:
the total number of bytes read.
Implements SockIO.
References ioHandle_, and isValid().
bool SockCOM::readReady (uint32_t sec = 0, uint32_t usec = 0) const [virtual]
Indicates data is available for reading.
Indicates that data is avialable in the seral device's buffer for reading.
Parameters:
sec an unsigned integer specifying the number of seconds to wait before returning.
usec an unsinged integer specifying the number of microseconds to wait before returning.
Returns:
a boolean value indicating that data is available if true, no data is available if false.
Implements SockIO.
References ioHandle_, and isValid().
bool SockCOM::setBlockingIO (bool block) [virtual]
Set blocking I/O mode.
Sets the serial device's I/O mode to blocking or non-blocking.
Parameters:
block a boolean value indicating that the serial device should use blocking I/O if true, non-blocking I/O if false.
Returns:
a boolean value indicating that I/O mode was successfully changed if true, was not successfully changed if false.
Implements SockIO.
References ioHandle_.
void SockCOM::setLastError (int32_t error)
Set the system error code.
Sets the serial device's error code to the specified value. All serial devices share the same instance of the error code.
Parameters:
error an integer specifying the value to which the error value is to be set.
References lastError_.
Referenced by open().
int32_t SockCOM::write (const void * buffer, int32_t size, int32_t flags = 0) const [virtual]
Write data.
Writes data to the network.
Parameters:
buffer a pointer to an object filled with the data to be written.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to network sockets when writing. Unused by serial devices.
Returns:
the total number of bytes written.
Implements SockIO.
References ioHandle_, and isValid().
bool SockCOM::writeReady (uint32_t sec = 0, uint32_t usec = 0) const [virtual]
Indicates space is available for writing.
Indicates that space in the serial device's buffer is avialable for writing.
Parameters:
sec an unsigned integer specifying the number of seconds to wait before returning.
usec an unsinged integer specifying the number of milliseconds to wait before returning.
Returns:
a boolean value indicating that space is available if true, no space is available if false.
Implements SockIO.
References ioHandle_, and isValid().
The documentation for this class was generated from the following files:
SockCOM.h
SockCOM.cpp