NET: SockUnicast Class Reference
SockUnicast Class Reference
UDP unicast socket class.
#include <SockUnicast.h>
Public Member Functions
SockUnicast ()
Default unicast socket constructor.
SockUnicast (uint16_t port, const char *iface=NULL)
Unicast socket constructor.
SockUnicast (uint16_t peerport, const char *peeraddr, uint16_t port, const char *iface=NULL, bool attach=true)
Unicast socket constructor.
SockUnicast (const SockAddrInet *localaddr)
Unicast socket constructor.
SockUnicast (const SockAddrInet *peeraddr, const SockAddrInet *localaddr, bool attach=true)
Unicast socket constructor.
SockUnicast (SOCKET sockfd)
Unicast socket constructor.
virtual bool open ()
Open socket connection.
Detailed Description
UDP unicast socket class.
A UDP socket that utilizes network unicast for data transmission.
Constructor & Destructor Documentation
SockUnicast::SockUnicast ()
Default unicast socket constructor.
Creates a unicast socket object with default data values.
SockUnicast::SockUnicast (uint16_t port, const char * iface = NULL)
Unicast socket constructor.
Creates a unicast socket object with the specified data values.
Parameters:
port an unsigned 16-bit integer specifying the port to bind the socket to.
iface a character string specifying the network interface to use for network transmission.
References SockInet::bind(), SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, and SockInet::sockfd_.
SockUnicast::SockUnicast (uint16_t peerport, const char * peeraddr, uint16_t port, const char * iface = NULL, bool attach = true)
Unicast socket constructor.
Creates a unicast socket object with the specified data values, and connects it to a specified peer. When a unicast socket object is connected to a peer, data can be sent to that peer with calls to 'write' rather than calls to 'writeTo'. When a UDP socket is connected it can only communicate with the peer.
Parameters:
peerport a 16-bit integer specifying the port of the peer that the socket is to be connected/attached to.
peeraddr a character string specifying the network address of the peer that the socket is connected/attached to.
port an unsigned 16-bit integer specifying the port to bind the socket to.
iface a character string specifying the network interface to use for network transmission.
attach a boolean value specifying whether the socket is to be attached to the peer or connected to the peer. When the socket is attached, the socket object stores the peerport and peeraddr values and uses them to call 'sendto'. If the socket is connected, the socket object links the socket to the peer on the kernel level with a call to the 'connect' function and sends data with 'send'.
See also:
SockUDP::attached_
SockUDP::write
SockUDP::writeTo
References SockUDP::attached_, SockInet::bind(), SockUDP::connect(), SockUDP::connected_, SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, SockUDP::peeraddr_, and SockInet::sockfd_.
SockUnicast::SockUnicast (const SockAddrInet * localaddr)
Unicast socket constructor.
Creates a unicast socket object with the specified data values.
Parameters:
localaddr a SockAddrInet object specifying the network information to be used when creating the socket.
See also:
SockAddrInet
References SockInet::bind(), SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, and SockInet::sockfd_.
SockUnicast::SockUnicast (const SockAddrInet * peeraddr, const SockAddrInet * localaddr, bool attach = true)
Unicast socket constructor.
Creates a unicast socket object with the specified data values, and connects it to a specified peer. When a unicast socket object is connected to a peer, data can be sent to that peer with calls to 'write' rather than calls to 'writeTo'. When a UDP socket is connected it can only communicate with the peer.
Parameters:
peeraddr a SockAddrInet object specifying the network information for the peer to connect with when creating the socket.
localaddr a SockAddrInet object specifying the network information to be used when creating the socket.
attach a boolean value specifying whether the socket is to be attached to the peer or connected to the peer. When the socket is attached, the socket object stores the peerport and peeraddr values and uses them to call 'sendto'. If the socket is connected, the socket object links the socket to the peer on the kernel level with a call to the 'connect' function and sends data with 'send'.
See also:
SockUDP::attached_
SockUDP::write
SockUDP::writeTo
References SockUDP::attached_, SockInet::bind(), SockUDP::connect(), SockUDP::connected_, SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, SockUDP::peeraddr_, and SockInet::sockfd_.
SockUnicast::SockUnicast (SOCKET sockfd)
Unicast socket constructor.
Creates a socket object from the specified data value.
Parameters:
sockfd a handle to a previously created socket, to be used by the socket object.
Member Function Documentation
bool SockUnicast::open () [virtual]
Open socket connection.
See also:
SockInet::open
Implements SockUDP.
The documentation for this class was generated from the following files:
SockUnicast.h
SockUnicast.cpp