NET: SockInet Class Reference
SockInet Class Reference
Internet socket socket class.
#include <SockInet.h>
Public Member Functions
SockInet ()
Default socket constructor.
SockInet (uint16_t port, const char *iface=NULL)
Socket constructor.
SockInet (const SockAddrInet *localaddr)
Socket constructor.
SockInet (SOCKET sockfd)
Socket constructor.
virtual ~SockInet ()
Destructor.
virtual bool isValid () const
Indicates the socket handle references a valid kernel socket.
SOCKET getDescriptor () const
Retrieve the socket descriptor.
int32_t getFamily () const
Retrieve the socket address family.
uint16_t getLocalPort () const
Retrieve port value.
const char * getIface (char *iface, int32_t len) const
Retrieve network interface value.
bool getSockOpt (int32_t level, int32_t name, void *val, socklen_t *size) const
Get socket option.
bool setSockOpt (int32_t level, int32_t name, const void *val, socklen_t size)
Set socket option.
bool isBlockingIO () const
Indicates blocking I/O mode.
bool setBlockingIO (bool block)
Set blocking I/O mode.
int32_t getLastError () const
Get socket error code.
void setLastError (int32_t error)
Set the socket error code.
virtual bool open ()=0
Open socket.
virtual bool close ()
Close socket.
virtual bool shutdown (int32_t howto)
Shutdown one or both of the socket communication streams (input/output).
bool bind (uint16_t port=EPHEMERAL_PORT, const char *iface=NULL)
Bind socket.
virtual bool bind (const SockAddrInet *localaddr)
Bind socket.
virtual bool readReady (uint32_t sec=0, uint32_t usec=0) const
Indicates data is available for reading.
virtual bool writeReady (uint32_t sec=0, uint32_t usec=0) const
Indicates space is available for writing.
virtual bool errorCheck (uint32_t sec=0, uint32_t usec=0) const
Indicates that an error was encountered.
virtual int32_t read (void *buffer, int32_t size, int32_t flags=0) const
Read data.
virtual int32_t write (const void *buffer, int32_t size, int32_t flags=0) const
Write data.
Protected Attributes
bool block_
Use blocking I/O.
SOCKET sockfd_
Socket handle.
SockAddrInet * localaddr_
Local socket address settings.
Detailed Description
Internet socket socket class.
An abstract class for a socket from the ineternet socket address family.
Constructor & Destructor Documentation
SockInet::SockInet ()
Default socket constructor.
Creates an unconnected socket object with default data values.
References SockAddrFactory::create(), and localaddr_.
SockInet::SockInet (uint16_t port, const char * iface = NULL)
Socket constructor.
Creates a socket object with the specified data values.
Parameters:
port an unsigned 16-bit integer specifying the local port with which to bind the socket.
iface a character string specifying the network interface to use for network transmission.
References SockAddrFactory::create(), localaddr_, SockAddrInet::setAddress(), and SockAddrInet::setPort().
SockInet::SockInet (const SockAddrInet * localaddr)
Socket constructor.
Creates a socket object with the specified data values.
Parameters:
localaddr a SockAddrInet object specifying the network information to be used when creating the socket.
References SockAddrInet::copy(), SockAddrFactory::create(), and localaddr_.
SockInet::SockInet (SOCKET sockfd)
Socket constructor.
Creates a socket object from the specified data value.
Parameters:
sockfd a handle to a previously created socket, to be used by the socket object.
References block_, SockAddrInet::copy(), SockAddrFactory::create(), localaddr_, setBlockingIO(), and sockfd_.
SockInet::~SockInet () [virtual]
Destructor.
Virtual destructor. Will close an open/connected socket.
References close(), isValid(), and localaddr_.
Member Function Documentation
bool SockInet::bind (uint16_t port = EPHEMERAL_PORT, const char * iface = NULL)
Bind socket.
Bind the socket to the specified port an network interface.
Parameters:
port an unsigned 16-bit integer specifying the port to bind to. To let kernel pick the port use 'EPHEMERAL_PORT'.
iface a character string specifying the network address of the network interface to use for data transmission. To use any network interface (INADDR_ANY), set to NULL.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), localaddr_, SockAddrInet::setAddress(), SockAddrInet::setPort(), and sockfd_.
Referenced by bind(), SockBroadcast::SockBroadcast(), SockClient::SockClient(), SockMulticast::SockMulticast(), SockServer::SockServer(), and SockUnicast::SockUnicast().
bool SockInet::bind (const SockAddrInet * localaddr) [virtual]
Bind socket.
Bind the socket with the specified socket address data.
Parameters:
localaddr a socket address object specifying the values to be used when binding the socket.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References bind(), SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), localaddr_, and sockfd_.
bool SockInet::close () [virtual]
Close socket.
Close an open socket.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
Implements SockIO.
Reimplemented in SockUDP, SockClient, and SockServer.
References block_, and sockfd_.
Referenced by ~SockInet().
bool SockInet::errorCheck (uint32_t sec = 0, uint32_t usec = 0) const [virtual]
Indicates that an error was encountered.
Indicates that am error was encountered by the socket object.
Parameters:
sec an unsigned integer specifying the number of seconds to wait before returning.
usec an unsinged integer specifying the number of milliseconds to wait before returning.
Returns:
a boolean value indicating that an error was encountered if true, no error was encountered if false. Will always return false if the socket is invalid/not open.
References isValid(), and sockfd_.
SOCKET SockInet::getDescriptor () const
Retrieve the socket descriptor.
Returns the socket descriptor.
Returns:
a SOCKET specifying the socket descriptor if a valid socket descriptor exists, or INVALID_SOCKET if no valid socket descriptor exists.
References sockfd_.
Referenced by SockMonitor::addErrorMonitor(), SockMonitor::addReadMonitor(), SockMonitor::addWriteMonitor(), SockMonitor::removeErrorMonitor(), SockMonitor::removeReadMonitor(), and SockMonitor::removeWriteMonitor().
int32_t SockInet::getFamily () const
Retrieve the socket address family.
Returns the socket address family type.
Returns:
an integer specifying the socket address family. Currently only AF_INET is supported.
const char * SockInet::getIface (char * iface, int32_t len) const
Retrieve network interface value.
Returns value of network interface.
Parameters:
iface a character array to be filled with the IPv4 network address associated with the network interface.
len an integer specifying the size, in bytes, of 'addr'.
Returns:
a pointer to an array of characters containing the IPv4 network address for the associated network interface.
References SockAddrInet::getAddress(), and localaddr_.
int32_t SockInet::getLastError () const
Get socket error code.
Returns the last known network error value. This function is not specific to any one socket. The error value retrieved can be for any socket that is part of the overall application.
Returns:
an error code indicating the reason for socket failure.
uint16_t SockInet::getLocalPort () const
Retrieve port value.
Returns value of port.
Returns:
an unsigned 16-bit integer specifying a TCP port number for the socket object.
References SockAddrInet::getPort(), and localaddr_.
bool SockInet::getSockOpt (int32_t level, int32_t name, void * val, socklen_t * size) const
Get socket option.
Retrieves the value associated with a specific socket option. This function uses the same arguments as the BSD socket function 'getsockopt'. See the 'getsockopt' man pages or MSDN documentation for details.
Parameters:
level an integer specifying the socket protocol level for the desired option.
name an integer specifying the name of the desired option.
val a void pointer referencing an object to be filled with the desired option's associated value.
size an integer specifying the size, in bytes, of 'val'.
Returns:
a boolean value indicating success if true, failure if false.
References sockfd_.
bool SockInet::isBlockingIO () const [virtual]
Indicates blocking I/O mode.
Indicates that the socket is or is not using blocking I/O.
Returns:
a boolean value indicating that the socket is using blocking I/O if true, is not using blocking I/O if false.
Implements SockIO.
References block_.
bool SockInet::isValid () const [virtual]
Indicates the socket handle references a valid kernel socket.
Indicates that the socket object's socket handle is valid.
Returns:
a boolean value indicating the socket handle is valid if true, and invalid if false.
Reimplemented from SockIO.
References sockfd_.
Referenced by errorCheck(), readReady(), setBlockingIO(), writeReady(), SockClient::~SockClient(), ~SockInet(), and SockUDP::~SockUDP().
virtual bool SockInet::open () [pure virtual]
Open socket.
Binds socket and, depending on socket type, connects to peer or listens for connections.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
Implements SockIO.
Implemented in SockUDP, SockBroadcast, SockUnicast, SockClient, SockServer, SockMulticast, and SockTCP.
int32_t SockInet::read (void * buffer, int32_t size, int32_t flags = 0) const [virtual]
Read data.
Reads data that is available in the socket input buffer.
Parameters:
buffer a pointer to an object to be filled with the data in the socket buffer.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when reading. These are the flags used by the BSD socket function 'recv'. See the 'recv' man pages or MSDN documentation for more details.
Returns:
the total number of bytes read.
Implements SockIO.
Reimplemented in SockUDP.
References sockfd_.
Referenced by SockTCP::readAll().
bool SockInet::readReady (uint32_t sec = 0, uint32_t usec = 0) const [virtual]
Indicates data is available for reading.
Indicates that data is avialable in the socket buffer for reading.
Parameters:
sec an unsigned integer specifying the number of seconds to wait before returning.
usec an unsinged integer specifying the number of microseconds to wait before returning.
Returns:
a boolean value indicating that data is available if true, no data is available if false. Will always return false if the socket is invalid/not open.
Implements SockIO.
References isValid(), and sockfd_.
bool SockInet::setBlockingIO (bool block) [virtual]
Set blocking I/O mode.
Sets the socket's I/O mode to blocking or non-blocking.
Parameters:
block a boolean value indicating that the socket should use blocking I/O if true, non-blocking I/O if false.
Returns:
a boolean value indicating that I/O mode was successfully changed if true, was not successfully changed if false.
Implements SockIO.
References block_, isValid(), and sockfd_.
Referenced by SockInet().
void SockInet::setLastError (int32_t error)
Set the socket error code.
Sets the socket error code to the specified value. All sockets share the same instance of the error code.
Parameters:
error an integer specifying the value to which the error value is to be set.
bool SockInet::setSockOpt (int32_t level, int32_t name, const void * val, socklen_t size)
Set socket option.
Sets the value associated with a specific socket option. This function uses the same arguments as the BSD socket function 'setsockopt'. See the 'setsockopt' man pages or MSDN documentation for details.
Parameters:
level an integer specifying the socket protocol level for the desired option.
name an integer specifying the name of the desired option.
val a void pointer referencing an object filled with the value for the desired option.
size an integer specifying the size, in bytes, of 'val'.
Returns:
a boolean value indicating success if true, failure if false.
References sockfd_.
bool SockInet::shutdown (int32_t howto) [virtual]
Shutdown one or both of the socket communication streams (input/output).
Shutdown either or both of the input and output streams of a socket, without closing the socket.
Parameters:
howto an integer indicating which stream to shutdown. SHUT_RD for input, SHUT_WR for output, SHUTRDWR for both.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
References sockfd_.
int32_t SockInet::write (const void * buffer, int32_t size, int32_t flags = 0) const [virtual]
Write data.
Writes data to the network.
Parameters:
buffer a pointer to an object filled with the data to be written.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when writing. These are the flags used by the BSD socket function 'send'. See the 'send' man pages or MSDN documentation for more details.
Returns:
the total number of bytes written.
Implements SockIO.
Reimplemented in SockUDP.
References sockfd_.
bool SockInet::writeReady (uint32_t sec = 0, uint32_t usec = 0) const [virtual]
Indicates space is available for writing.
Indicates that space in the socket buffer is avialable for writing.
Parameters:
sec an unsigned integer specifying the number of seconds to wait before returning.
usec an unsinged integer specifying the number of milliseconds to wait before returning.
Returns:
a boolean value indicating that space is available if true, no space is available if false. Will always return false if the socket is invalid/not open.
Implements SockIO.
References isValid(), and sockfd_.
Member Data Documentation
bool SockInet::block_ [protected]
Use blocking I/O.
A boolean value indicating that the socket is blocking/non-blocking.
Referenced by close(), SockClient::connect(), isBlockingIO(), setBlockingIO(), and SockInet().
SockAddrInet* SockInet::localaddr_ [protected]
Local socket address settings.
A socket address object specifying the local settings for this object.
Referenced by bind(), SockClient::connect(), SockUDP::connect(), getIface(), getLocalPort(), SockBroadcast::SockBroadcast(), SockClient::SockClient(), SockInet(), SockMulticast::SockMulticast(), SockServer::SockServer(), SockUnicast::SockUnicast(), and ~SockInet().
SOCKET SockInet::sockfd_ [protected]
Socket handle.
Handle to the socket used by this object.
Referenced by SockServer::accept(), bind(), close(), SockClient::connect(), SockUDP::connect(), SockUDP::disconnect(), errorCheck(), getDescriptor(), SockMulticast::getMcastIface(), getSockOpt(), isValid(), SockMulticast::joinGroup(), SockMulticast::leaveGroup(), SockServer::listen(), read(), SockTCP::readAll(), SockUDP::readFrom(), readReady(), setBlockingIO(), SockMulticast::setMcastIface(), setSockOpt(), SockMulticast::setTTL(), shutdown(), SockBroadcast::SockBroadcast(), SockClient::SockClient(), SockInet(), SockMulticast::SockMulticast(), SockServer::SockServer(), SockUnicast::SockUnicast(), write(), SockTCP::writeAll(), writeReady(), and SockUDP::writeTo().
The documentation for this class was generated from the following files:
SockInet.h
SockInet.cpp