NET: SockIO Class Reference
SockIO Class Reference
#include <SockIO.h>
Public Member Functions
SockIO ()
Creates an empty SockIO object.
virtual ~SockIO ()
Destroys a SockIO object.
virtual bool isValid () const
Indicates the socket handle references a valid kernel socket.
virtual bool isBlockingIO () const =0
Indicates blocking I/O mode.
virtual bool setBlockingIO (bool block)=0
Set blocking I/O mode.
virtual bool open ()=0
Open socket.
virtual bool close ()=0
Close socket.
virtual bool readReady (uint32_t sec=0, uint32_t usec=0) const =0
Indicates data is available for reading.
virtual bool writeReady (uint32_t sec=0, uint32_t usec=0) const =0
Indicates space is available for writing.
virtual int32_t read (void *buffer, int32_t size, int32_t flags=0) const =0
Read data.
virtual int32_t write (const void *buffer, int32_t size, int32_t flags=0) const =0
Write data.
virtual int32_t writeAll (const void *buffer, int32_t size, int32_t flags=0) const
Write a fixed amount of data.
Detailed Description
Pure virtual class for writing to i/o sockets and devices
Member Function Documentation
virtual bool SockIO::close () [pure virtual]
Close socket.
Close an open socket.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
Implemented in SockCOM, SockUDP, SockInet, SockClient, and SockServer.
virtual bool SockIO::isBlockingIO () const [pure virtual]
Indicates blocking I/O mode.
Indicates that the socket is or is not using blocking I/O.
Returns:
a boolean value indicating that the socket is using blocking I/O if true, is not using blocking I/O if false.
Implemented in SockCOM, and SockInet.
virtual bool SockIO::isValid () const [inline, virtual]
Indicates the socket handle references a valid kernel socket.
Indicates that the socket object's socket handle is valid.
Returns:
a boolean value indicating the socket handle is valid if true, and invalid if false.
Reimplemented in SockCOM, and SockInet.
Referenced by writeAll().
virtual bool SockIO::open () [pure virtual]
Open socket.
Binds socket and, depending on socket type, connects to peer or listens for connections.
Returns:
a boolean value indicating the operation was successful if true, was unsuccessful if false.
Implemented in SockCOM, SockUDP, SockInet, SockBroadcast, SockUnicast, SockClient, SockServer, SockMulticast, and SockTCP.
virtual int32_t SockIO::read (void * buffer, int32_t size, int32_t flags = 0) const [pure virtual]
Read data.
Reads data that is available in the socket input buffer.
Parameters:
buffer a pointer to an object to be filled with the data in the socket buffer.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when reading. These are the flags used by the BSD socket function 'recv'. See the 'recv' man pages or MSDN documentation for more details.
Returns:
the total number of bytes read.
Implemented in SockCOM, SockInet, and SockUDP.
virtual bool SockIO::readReady (uint32_t sec = 0, uint32_t usec = 0) const [pure virtual]
Indicates data is available for reading.
Indicates that data is avialable in the socket buffer for reading.
Parameters:
sec an unsigned integer specifying the number of seconds to wait before returning.
usec an unsinged integer specifying the number of microseconds to wait before returning.
Returns:
a boolean value indicating that data is available if true, no data is available if false.
Implemented in SockCOM, and SockInet.
virtual bool SockIO::setBlockingIO (bool block) [pure virtual]
Set blocking I/O mode.
Sets the sockets I/O mode to blocking or non-blocking.
Parameters:
block a boolean value indicating that the socket should use blocking I/O if true, non-blocking I/O if false.
Returns:
a boolean value indicating that I/O mode was successfully changed if true, was not successfully changed if false.
Implemented in SockCOM, and SockInet.
virtual int32_t SockIO::write (const void * buffer, int32_t size, int32_t flags = 0) const [pure virtual]
Write data.
Writes data to the network.
Parameters:
buffer a pointer to an object filled with the data to be written.
size an integer specifying the size, in bytes, of 'buffer'.
flags an integer specifying the bit flags to be passed to the socket when writing. These are the flags used by the BSD socket function 'send'. See the 'send' man pages or MSDN documentation for more details.
Returns:
the total number of bytes written.
Implemented in SockCOM, SockInet, and SockUDP.
Referenced by writeAll().
int32_t SockIO::writeAll (const void * buffer, int32_t size, int32_t flags = 0) const [virtual]
Write a fixed amount of data.
Writes the total number of bytes specified.
Parameters:
buffer a pointer to an object filled with the data to be written.
size an integer specifying the size, in bytes, of 'buffer'. The function will not return until exactly this number of bytes has been written, or an error has been encountered.
flags an integer specifying the bit flags to be passed to the socket when writing. These are the flags used by the BSD socket function 'send'. See the 'send' man pages or MSDN documentation for more details.
Returns:
the total number of bytes written.
Reimplemented in SockTCP.
References isValid(), and write().
virtual bool SockIO::writeReady (uint32_t sec = 0, uint32_t usec = 0) const [pure virtual]
Indicates space is available for writing.
Indicates that space in the socket buffer is avialable for writing.
Parameters:
sec an unsigned integer specifying the number of seconds to wait before returning.
usec an unsinged integer specifying the number of milliseconds to wait before returning.
Returns:
a boolean value indicating that space is available if true, no space is available if false.
Implemented in SockCOM, and SockInet.
The documentation for this class was generated from the following files:
SockIO.h
SockIO.cpp