NET: SockMulticast Class Reference
SockMulticast Class Reference
UDP multicast socket class.
#include <SockMulticast.h>
Public Member Functions
SockMulticast ()
Default multicast socket constructor.
SockMulticast (uint16_t port, TTL_T ttl=1)
Multicast socket constructor.
SockMulticast (uint16_t port, const char *group, const char *mciface=NULL, TTL_T ttl=1, bool attach=true)
Multicast socket constructor.
bool open ()
Open socket connection.
TTL_T getTTL () const
Retrieve TTL.
bool setTTL (TTL_T ttl)
Set TTL.
char * getMcastIface (char *iface, int32_t len) const
Retrieve network interface value.
bool setMcastIface (const char *iface)
Set network interface value.
bool joinGroup (const char *group)
Join multicast group.
bool leaveGroup (const char *group)
Leave multicast group.
Protected Attributes
TTL_T ttl_
Time to live.
Detailed Description
UDP multicast socket class.
A socket that utilizes the network multicast protocol for data transmission.
Constructor & Destructor Documentation
SockMulticast::SockMulticast ()
Default multicast socket constructor.
Creates a multicast socket object with default data values.
SockMulticast::SockMulticast (uint16_t port, TTL_T ttl = 1)
Multicast socket constructor.
Creates a multicast socket object with the specified data values.
Parameters:
port an unsigned 16-bit integer specifying the port to bind the multicast socket to.
ttl an integer value specifying the time to live value to use for network transmission.
References SockInet::bind(), SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, and SockInet::sockfd_.
SockMulticast::SockMulticast (uint16_t port, const char * group, const char * mciface = NULL, TTL_T ttl = 1, bool attach = true)
Multicast socket constructor.
Creates a multicast socket object with the specified data values, and connects it to a specified multicast address. When a multicast socket object is connected to a multicast address, data can be sent to that address with calls to 'write' rather than calls to 'writeTo'. When a multicast socket is connected it can only communicate on that multicast address.
Parameters:
port an unsigned 16-bit integer specifying the port to which the multicast socket should bind.
group a character string specifying the multicast address to which the multicast socket should bind.
mciface a character string specifying the network interface to use for network transmission.
ttl an integer value specifying the time to live value to use for network transmission.
attach a boolean value specifying whether the broadcast socket is to be attached to the peer or connected to the peer. When the socket is attached, the broadcast socket object stores the peerport and peeraddr values and uses them to call 'sendto'. If the socket is connected, the broadcast socket object links the socket to the peer on the kernel level with a call to the 'connect' function and sends data witn 'send'.
See also:
SockUDP::attached_
SockUDP::write
SockUDP::writeTo
References SockInet::bind(), SockAddrInet::copy(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), joinGroup(), SockInet::localaddr_, SockAddrInet::setAddress(), setMcastIface(), and SockInet::sockfd_.
Member Function Documentation
char * SockMulticast::getMcastIface (char * iface, int32_t len) const
Retrieve network interface value.
Returns value of network interface.
Parameters:
iface a character array to be filled with the IPv4 network address associated with the network interface.
len an integer specifying the size, in bytes, of 'addr'.
Returns:
a pointer to an array of characters containing the IPv4 network address for the associated network interface.
References SockInet::sockfd_.
TTL_T SockMulticast::getTTL () const
Retrieve TTL.
Returns the current multicast socket object's time to live value.
Returns:
an integer specifying the socket's TTL.
References ttl_.
bool SockMulticast::joinGroup (const char * group)
Join multicast group.
Joins a specified multicast group.
Parameters:
group a character string specifying the multicast address for the group to join.
Returns:
a boolean value indicating that the operation succeeded if true, failed if false.
References SockInet::sockfd_.
Referenced by SockMulticast().
bool SockMulticast::leaveGroup (const char * group)
Leave multicast group.
Leaves a specified multicast group.
Parameters:
group a character string specifying the multicast address for the group to leave.
Returns:
a boolean value indicating that the operation succeeded if true, failed if false.
References SockInet::sockfd_.
bool SockMulticast::open () [virtual]
Open socket connection.
See also:
SockInet::open
Implements SockUDP.
bool SockMulticast::setMcastIface (const char * iface)
Set network interface value.
Sets the value of the network interface.
Parameters:
iface a character string specifying the network interface to use for network transmission.
Returns:
a boolean value indicating that the operation succeeded if true, failed if false.
References SockInet::sockfd_.
Referenced by SockMulticast().
bool SockMulticast::setTTL (TTL_T ttl)
Set TTL.
Sets the current multicast socket object's time to live value.
Parameters:
ttl an integer specifying the new TTL value to be used.
Returns:
a boolean value indicating that the operation succeeded if true, failed if false.
References SockInet::sockfd_, and ttl_.
Member Data Documentation
TTL_T SockMulticast::ttl_ [protected]
Time to live.
The time to live value for data transmissions.
Referenced by getTTL(), and setTTL().
The documentation for this class was generated from the following files:
SockMulticast.h
SockMulticast.cpp