NET: SockBroadcast Class Reference
SockBroadcast Class Reference
UDP boroadcast socket class.
#include <SockBroadcast.h>
Public Member Functions
SockBroadcast ()
Default broadcast socket constructor.
SockBroadcast (uint16_t port, const char *iface=NULL)
Broadcast socket constructor.
SockBroadcast (uint16_t peerport, const char *peeraddr, uint16_t port, const char *iface=NULL, bool attach=true)
Broadcast socket constructor.
SockBroadcast (const SockAddrInet *localaddr)
Broadcast socket constructor.
SockBroadcast (const SockAddrInet *peeraddr, const SockAddrInet *localaddr, bool attach=true)
Broadcast socket constructor.
SockBroadcast (SOCKET sockfd)
Broadcast socket constructor.
virtual bool open ()
Open socket connection.
Detailed Description
UDP boroadcast socket class.
A socket that utilizes the network broadcast protocol for data transmission.
Constructor & Destructor Documentation
SockBroadcast::SockBroadcast ()
Default broadcast socket constructor.
Creates a broadcast socket object with default data values.
References SockAddrFactory::create().
SockBroadcast::SockBroadcast (uint16_t port, const char * iface = NULL)
Broadcast socket constructor.
Creates a broadcast socket object with the specified data values.
Parameters:
port an unsigned 16-bit integer specifying the port to bind the broadcast socket to.
iface a character string specifying the network interface to use for network transmission. When reading data with a broadcast socket, it is best not to set the interface unless you really know what you are doing.
References SockInet::bind(), SockAddrInet::copy(), SockAddrFactory::create(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, and SockInet::sockfd_.
SockBroadcast::SockBroadcast (uint16_t peerport, const char * peeraddr, uint16_t port, const char * iface = NULL, bool attach = true)
Broadcast socket constructor.
Creates a broadcast socket object with the specified data values, and connects it to a specified broadcast address. When a broadcast socket object is connected to an address, data can be sent to that address with calls to 'write' rather than calls to 'writeTo'. When a broadcast socket is connected it can only communicate with that address. Connecting a broadcast socket to a specific broadcast address can cause problems when attempting to read from that socket, because a number of systems read all broadcast data on "0.0.0.0" or "255.255.255.255", so if the broadcast socket is connected to a specific address it may never receive any information.
Parameters:
peerport a 16-bit integer specifying the port of the peer that the broadcast socket is to be connected/attached to.
peeraddr a character string specifying the network broadcast address that the broadcast socket is connected/attached to.
port an unsigned 16-bit integer specifying the port to bind the broadcast socket to.
iface a character string specifying the network interface to use for network transmission. When reading data with a broadcast socket, it is best not to set the interface unless you really know what you are doing.
attach a boolean value specifying whether the broadcast socket is to be attached to the peer or connected to the peer. When the socket is attached, the broadcast socket object stores the peerport and peeraddr values and uses them to call 'sendto'. If the socket is connected, the broadcast socket object links the socket to the peer on the kernel level with a call to the 'connect' function and sends data with 'send'.
See also:
SockUDP::attached_
SockUDP::write
SockUDP::writeTo
References SockUDP::attached_, SockInet::bind(), SockUDP::connect(), SockUDP::connected_, SockAddrInet::copy(), SockAddrFactory::create(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, SockUDP::peeraddr_, and SockInet::sockfd_.
SockBroadcast::SockBroadcast (const SockAddrInet * localaddr)
Broadcast socket constructor.
Creates a broadcast socket object with the specified data values.
Parameters:
localaddr a SockAddrInet object specifying the network information to be used when creating the broadcast socket.
See also:
SockAddrInet
References SockInet::bind(), SockAddrInet::copy(), SockAddrFactory::create(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, and SockInet::sockfd_.
SockBroadcast::SockBroadcast (const SockAddrInet * peeraddr, const SockAddrInet * localaddr, bool attach = true)
Broadcast socket constructor.
Creates a broadcast socket object with the specified data values, and connects it to a specified broadcast address. When a broadcast socket object is connected to an address, data can be sent to that address with calls to 'write' rather than calls to 'writeTo'. When a broadcast socket is connected it can only communicate with that address. Connecting a broadcast socket to a specific broadcast address can cause problems when attempting to read from that socket, because a number of systems read all broadcast data on "0.0.0.0" or "255.255.255.255", so if the broadcast socket is connected to a specific address it may never receive any information.
Parameters:
peeraddr a SockAddrInet object specifying the network information for the broadcast address to connect with when creating the broadcast socket.
localaddr a SockAddrInet object specifying the network information to be used when creating the broadcast socket.
attach a boolean value specifying whether the broadcast socket is to be attached to the peer or connected to the peer. When the socket is attached, the broadcast socket object stores the peerport and peeraddr values and uses them to call 'sendto'. If the socket is connected, the broadcast socket object links the socket to the peer on the kernel level with a call to the 'connect' function and sends data with 'send'.
See also:
SockUDP::attached_
SockUDP::write
SockUDP::writeTo
References SockUDP::attached_, SockInet::bind(), SockUDP::connect(), SockUDP::connected_, SockAddrInet::copy(), SockAddrFactory::create(), SockAddrInet::getSockAddr(), SockAddrInet::getSockAddrLen(), SockInet::localaddr_, SockUDP::peeraddr_, and SockInet::sockfd_.
SockBroadcast::SockBroadcast (SOCKET sockfd)
Broadcast socket constructor.
Creates a broadcast socket object from the specified data value.
Parameters:
sockfd a handle to a previously created socket, to be used by the broadcast socket object.
Member Function Documentation
bool SockBroadcast::open () [virtual]
Open socket connection.
See also:
SockInet::open
Implements SockUDP.
References SockAddrFactory::create().
The documentation for this class was generated from the following files:
SockBroadcast.h
SockBroadcast.cpp